FEM solver
xuchenhan-tri/drake pull request #1
Opened 2020-09-01 04:26 UTC by xuchenhan-tri

The current state of the FEM solver. For the detailed design, see the design document [here](https://docs.google.com/document/d/1S7XRBO1T724bxJty3NnAbv6T6puXCJAqkPvl7UX3TS0/edit). The design doc is slightly out of date and will be updated ASAP.

2020-09-02 17:01 UTC, amcastro-tri requested changes
first few comments. WIP

> Reviewed 3 of 66 files at r1.
> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-:-MGEl18z4rEhIerW-HMt:bexkfjv)* status: 3 of 66 files reviewed, 18 unresolved discussions (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[fem/fem_data.h, line 29 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEgUyw3ctLPuu7kQAH:-MGEgUyw3ctLPuu7kQAI:ba9u22g) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L29)):*
> ```objc
> /** A data class that holds FEM vertex states, elements and constants. */
> template <typename T>
> class FemData {
> ```

An abstraction that I found very useful is to split `const data` from `mutable state`. Especially now I am working with the contact solvers where mutating data has quite a complex data flow. I imagine it'd prove useful here also.

Maybe you'd want `FemData` and `FemState` or similar. Having all the "state" in a single place vs. sprinkled around has the nice side effect of makings things way cleaner. 
Programatically it looks nice in that if you see `&fem_data` somewhere it'll make you think twice why you are modifying something supposed to be constant after construction. Similarly with `state_`
___
*[fem/fem_data.h, line 33 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEhe543iwrUGLRl_d0:-MGEhe543iwrUGLRl_d1:b-1shnmt) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L33)):*
> ```objc
>   FemData(double dt) : dt_(dt) {}
> 
>   int AddUndeformedObject(const std::vector<Vector4<int>>& indices,
> ```

Probably I know the answer, but do we wanna use `geometry::VolumeMesh` here?
___
*[fem/fem_data.h, line 33 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEi8CF31LJRgjEXlSR:-MGEi8CF31LJRgjEXlSS:bm4fpfw) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L33)):*
> ```objc
>   FemData(double dt) : dt_(dt) {}
> 
>   int AddUndeformedObject(const std::vector<Vector4<int>>& indices,
> ```

can I call this multiple times in principle? A lil doc might help.
___
*[fem/fem_data.h, line 35 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEhHLlEBLsgnZchLxD:-MGEhHLlEBLsgnZchLxE:b506hlz) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L35)):*
> ```objc
>   int AddUndeformedObject(const std::vector<Vector4<int>>& indices,
>                           const Matrix3X<T>& positions,
>                           const FemConfig& config);
> ```

`FemConfig` looks a lot like an abstraction for `Material`. Maybe `FemMaterial` would work best.
When I read `FemConfig` I think "number of iterations, tolerances, solver options, etc"
___
*[fem/fem_data.h, line 118 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEklG961nWgMqSMejH:-MGEklG961nWgMqSMejI:b-3o0i55) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L118)):*
> ```objc
>  private:
>   double dt_;
>   std::vector<FemElement<T>> elements_;
> ```

how are elements_ indexed?
___
*[fem/fem_data.h, line 119 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEiGnf0TAlnViyZyCF:-MGEiGnf0TAlnViyZyCG:bhd3j1q) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L119)):*
> ```objc
>   double dt_;
>   std::vector<FemElement<T>> elements_;
>   // vertex_indices_[i] gives the global vertex indices corresponding to object
> ```

Lets see if we speak the same language. With "global" you mean the all vertices for all meshes for all objects are numbered from 1 to `num_vertices_`?
Then is it fair that you call "local" to the original connectivities as read from, say a VTK file?
___
*[fem/fem_data.h, line 121 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEihYG9Esr1aiPwWZG:-MGEihYG9Esr1aiPwWZH:b-5c9816) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L121)):*
Aren't the entries in  `vertex_indices_[i] ` contiguous? like e.g. "113, 114, 115.... 234". I wonder if with a cheaper struct like `vertex_start_[i]` would be enough.
> ```
___
*[fem/fem_data.h, line 124 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEixv92THN1EQwY79f:-MGEixv92THN1EQwY79g:b-eg1qss) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L124)):*
> ```objc
>   // element_indices_[i] gives the global element indices corresponding to
>   // object i.
>   std::vector<std::vector<int>> element_indices_;
> ```

ditto question for vertices. At this scope, and without finishing the review, isn't `element_indeces_[i]` a vector of ints all arranged contiguously? 
___
*[fem/fem_data.h, line 127 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEjOdqCzy18hElRf1y:-MGEjOdqCzy18hElRf1z:b5z33i2) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L127)):*
> ```objc
>   // mesh_[i] contains the global indices of the 4 vertices in the i-th
>   // tetrahedron.
>   std::vector<Vector4<int>> mesh_;
> ```

since this is a recurring pattern. YOu might have a lil paragraph right before you declare these variables explaining how you define "global" and "local" indexes and how they relate to input data.
___
*[fem/fem_data.h, line 128 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEj_u16ArJW6XSQurw:-MGEj_u2Bko87xh1BbGq:b-9xkcxn) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L128)):*
> ```objc
>   // tetrahedron.
>   std::vector<Vector4<int>> mesh_;
>   // Initial position.
> ```

should we call this "reference configuration"? per f2f.
I know in drake we use q,v for states. But that's at the `systems::` level. I don't see why to pollute this namespace when we FEM people have our own coventions. 
I'd much rather prefer `x, v` for positions and velocities (we are outside systems:: after all)
___
*[fem/fem_data.h, line 132 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEjyzh4t4cqaL6qx4N:-MGEjyzi9w-AqiXzKbOu:b-mtj0ni) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L132)):*
> ```objc
>   // Time n position.
>   Matrix3X<T> q_;
>   // Time n position + dt * time n velocity.
> ```

I've been calling this `v0`. Maybe adopt the same symbol here?
___
*[fem/fem_data.h, line 133 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEk3jn7WDTZeh_n6Md:-MGEk3jn7WDTZeh_n6Me:b-mmui4t) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L133)):*
> ```objc
>   Matrix3X<T> q_;
>   // Time n position + dt * time n velocity.
>   Matrix3X<T> q_hat_;
> ```

I've been calling this `q_star` (for `q*`), should we use similar notation?
___
*[fem/fem_data.h, line 133 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEkFsBDBOSxT034iY6:-MGEkFsC5QUSSAG9cpth:b-gmvwa2) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L133)):*
> ```objc
>   Matrix3X<T> q_;
>   // Time n position + dt * time n velocity.
>   Matrix3X<T> q_hat_;
> ```

Haven't seen the rest. Wondering why `q*` is needed. Usually at the velocity level we see `v*` and then update later the positions. 
___
*[fem/fem_data.h, line 135 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEkQLX0l8ikWEJlRUl:-MGEkQLX0l8ikWEJlRUm:b-63giue) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L135)):*
> ```objc
>   Matrix3X<T> q_hat_;
>   // Time n velocity.
>   Matrix3X<T> v_;
> ```

It'd be nice having a `FemState` where you store `x_`  and `v_`. 
A nice abstraction is that of cache,  [...]

2020-09-02 23:02 UTC, xuchenhan-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/1)* status: 3 of 66 files reviewed, 18 unresolved discussions (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[fem/fem_data.h, line 29 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEgUyw3ctLPuu7kQAH:-MGFWjDx2_uAtPcCB1jA:b-j0ph7v) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L29)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

An abstraction that I found very useful is to split `const data` from `mutable state`. Especially now I am working with the contact solvers where mutating data has quite a complex data flow. I imagine it'd prove useful here also.

Maybe you'd want `FemData` and `FemState` or similar. Having all the "state" in a single place vs. sprinkled around has the nice side effect of makings things way cleaner. 
Programatically it looks nice in that if you see `&fem_data` somewhere it'll make you think twice why you are modifying something supposed to be constant after construction. Similarly with `state_`
</blockquote></details>

Working, will do.
___
*[fem/fem_data.h, line 33 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEhe543iwrUGLRl_d0:-MGG0EOW0LepHgbOayEU:b-g0m1rv) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L33)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Probably I know the answer, but do we wanna use `geometry::VolumeMesh` here?
</blockquote></details>

Yes, we could. Thanks for the reference. Didn't know it existed.
___
*[fem/fem_data.h, line 33 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEi8CF31LJRgjEXlSR:-MGG2Sbg-RPjnh0dEgwj:b-wr4896) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L33)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

can I call this multiple times in principle? A lil doc might help.
</blockquote></details>

Yes, you can. Will add documentation.
___
*[fem/fem_data.h, line 35 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEhHLlEBLsgnZchLxD:-MGFalNQ5z14DqNlGlRQ:bf6pjmn) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L35)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

`FemConfig` looks a lot like an abstraction for `Material`. Maybe `FemMaterial` would work best.
When I read `FemConfig` I think "number of iterations, tolerances, solver options, etc"
</blockquote></details>

How about `FemMaterialConfig`? `FemMaterial` seems to suggest it contains information more than just the physics parameters.
___
*[fem/fem_data.h, line 118 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEklG961nWgMqSMejH:-MGFaPBQ-arblSiCwYtx:b-ef50wb) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L118)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

how are elements_ indexed?
</blockquote></details>

They are globally indexed, i.e, ranging from 0 to `elements_.size()-1`.
___
*[fem/fem_data.h, line 119 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEiGnf0TAlnViyZyCF:-MGFaAUH9SC_BD4fWvFA:b-el7pm) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L119)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Lets see if we speak the same language. With "global" you mean the all vertices for all meshes for all objects are numbered from 1 to `num_vertices_`?
Then is it fair that you call "local" to the original connectivities as read from, say a VTK file?
</blockquote></details>

The answer is yes to both questions (except that, of course, I used 0-based indexing). I will write up a little example in the comment illustrating the definition of "local" vs. "global".
___
*[fem/fem_data.h, line 121 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEihYG9Esr1aiPwWZG:-MGF_cv03_Qp5IkzItfc:bvv8oka) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L121)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Aren't the entries in  `vertex_indices_[i] ` contiguous? like e.g. "113, 114, 115.... 234". I wonder if with a cheaper struct like `vertex_start_[i]` would be enough.
> ```

</blockquote></details>

Yes the entries are contiguous. I went with the more expensive way of storage to leave the door open for potentially adding vertices to the the object after initialization (e.g. fracture). In that case, the entries will no longer be contiguous.
___
*[fem/fem_data.h, line 124 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEixv92THN1EQwY79f:-MGFcEQxAZrVLXg73nO7:be3vog8) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L124)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

ditto question for vertices. At this scope, and without finishing the review, isn't `element_indeces_[i]` a vector of ints all arranged contiguously? 
</blockquote></details>

Same as in the vertices case.
___
*[fem/fem_data.h, line 127 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEjOdqCzy18hElRf1y:-MGF_BFh8_2-aDvYj7K7:bhy9ot6) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L127)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

since this is a recurring pattern. YOu might have a lil paragraph right before you declare these variables explaining how you define "global" and "local" indexes and how they relate to input data.
</blockquote></details>

Will do.
___
*[fem/fem_data.h, line 128 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEj_u16ArJW6XSQurw:-MGFZkHD-KKfDYfYCZYO:b4s94xf) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L128)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

should we call this "reference configuration"? per f2f.
I know in drake we use q,v for states. But that's at the `systems::` level. I don't see why to pollute this namespace when we FEM people have our own coventions. 
I'd much rather prefer `x, v` for positions and velocities (we are outside systems:: after all)
</blockquote></details>

Will do re. "reference configuration".
As for `x` vs. 'v'. I personally actually perfer `x`. Let me pose this question to a broader audience and see if there's any objection to `x`.
___
*[fem/fem_data.h, line 132 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEjyzh4t4cqaL6qx4N:-MGFYZUl7sZ8oYhf8SmR:b-o8k7j4) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L132)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I've been calling this `v0`. Maybe adopt the same symbol here?
</blockquote></details>

I'm not sure which quantity you are referring to here.
___
*[fem/fem_data.h, line 133 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEk3jn7WDTZeh_n6Md:-MGFYVpL67GT_Y_BzC8C:b-j0ph7v) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L133)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I've been calling this `q_star` (for `q*`), should we use similar notation?
</blockqu [...]

2020-09-08 14:40 UTC, amcastro-tri requested changes
another pass. Mostly on the hyperelastic material abstraction this time.

> Reviewed 2 of 66 files at r1.
> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-:-MGi9AQE44hKyfE-LzMN:b2f9600)* status: 5 of 66 files reviewed, 33 unresolved discussions (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[fem/corotated_linear_model.h, line 10 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGhz0hZ2Ucamw9fIxU_:-MGhz0h_CF6D_HyPh5Uf:bf4alem) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/corotated_linear_model.h#L10)):*
> ```objc
> namespace drake {
> namespace fem {
> /** Implements the constitutive model described in [Müller, 2004]. */
> ```

could you add reference here locally?
___
*[fem/corotated_linear_model.h, line 18 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGhzJ3qDeUGvHJOd1O2:-MGhzJ3r3qEstFn5RRM3:b-3hig1r) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/corotated_linear_model.h#L18)):*
> ```objc
> 
>   CorotatedLinearElasticity(T E, T nu, T alpha, T beta,
>                             const Eigen::Matrix<T, 3, 4>& vertex_positions)
> ```

could we use monogram notation? these are the positions of the vertices in what frame? in the reference configuration I assume?
___
*[fem/corotated_linear_model.cc, line 8 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGi185d-EyoTTNhVf1_:-MGi185d-EyoTTNhVf1a:b-wfmgxa) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/corotated_linear_model.cc#L8)):*
> ```cpp
> namespace fem {
> template <typename T>
> void CorotatedLinearElasticity<T>::DoUpdateDeformationBasedState(
> ```

Looking at the code here (which I shouldn't need to from the signatures) I find out that these two versions of `DoUpdateDeformationBasedState()` have different semantics. One updates the strains assuming that we do know the rotation matrix, while the other actually update the rotation component "only" and not the strains.
It might just be that:
1. Those two methods deserves different names, with different purposes, different preconditions.
2. One of these methods is superfluous and there might be a cleaner alternative.
___
*[fem/corotated_linear_model.cc, line 11 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGi65Ly3fHqOZvf8xG5:-MGi65Lz1O2Oaxzt-mM1:b-saxr8a) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/corotated_linear_model.cc#L11)):*
> ```cpp
>     const Eigen::Ref<const Matrix3<T>>& F) {
>   F_ = F;
>   Matrix3<T> RtF = R_.transpose() * F_;
> ```

I would like us to figure out the proper monogram notation here. As with the rigid dynamics code, I am thinking it will pay off greatly. I started email discussion with Paul to talk about this.

Please refer to [these docs](https://drake.mit.edu/doxygen_cxx/group__multibody__notation__basics.html) with information in monogram notation and how we talk about rotation matrices. We should be able to use the same notation for rotation matrices for as long as we have well defined frames. For tensors....well, I started discussion with Paul.
___
*[fem/corotated_linear_model.cc, line 20 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGi1fk-C2xLCQ37-zRZ:-MGi1fk-C2xLCQ37-zR_:b38syiz) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/corotated_linear_model.cc#L20)):*
> ```cpp
>     const Eigen::Ref<const Eigen::Matrix<T, 3, 4>>& q) {
>   Matrix4<T> Q;
>   Q.template topLeftCorner<3, 4>() = q;
> ```

This surprised me.
I was hoping you'd take the deformation gradient F, and perform a polar decomposition to find out the rigid rotation component and the deformation component.
That approach has the nice side effect that with a single signature  for `DoUpdateDeformationBasedState()` (the one taking the gradients) you are done. It also has the nice side effect that this class represents an abstraction for a hyperelastic material more faithfully, that is, a function (rather complicated) of F only (nothing else like positions).

Now, you might have taken this approach instead because..... is it faster? some sort of optimization? 
___
*[fem/corotated_linear_model.cc, line 103 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGi92xCAcutMlkKYaZU:-MGi92xCAcutMlkKYaZV:b-7aeqq8) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/corotated_linear_model.cc#L103)):*
> ```cpp
>   Eigen::Matrix<T, 9, 9> dPdF = mu * Eigen::Matrix<T, 9, 9>::Identity();
>   for (int i = 0; i < 3; ++i) {
>     for (int j = 0; j < 3; ++j) {
> ```

this is expensive, do we need it explicitly?
___
*[fem/fem_data.h, line 3 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGhiiCaEhomO_Js5cl1:-MGhiiCb0o29TQe2_-RS:b-gpov44) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L3)):*
> ```objc
> #pragma once
> 
> #include <memory>
> ```

To be clear in this file what I meant on the separation between "data",  "state" and, possibly, "cache" (the last one being a nice way to organize things, not necessarily needed).

I am not thinking of a complicated cache framework as we do have in `systems::`, that'd be an overkill. I am rather thinking of a way to organize data in a simple way that does make sense in this scope were we know very well the dependencies.

I am thinking of something like this:
```c++
class FemData {
public:
int AddUndeformedObject(const MyMeshDataStructWhateveItIs& mesh,
                                              const MaterialProperties& properties);

int num_objects() const;

// Number of vertices for __all__ objects.
int num_vertices() const;

// Number of vertices for object `object_index`.
int num_vertices(ObjectIndex object_index) const;

// docs. Per element I assume?
const VectorX<T>& get_mass() const;

// Returns the reference configuration for __all__ meshes. Data storage is in this particular order... blah...
const Matrix3X<T>& get_Q() const;

// ....
};
```

Notice that `FemData` is `const` after the user is done adding data. Therefore if we see a mutable pointer to a `FemData` we'll think twice, because that should only happen at "registration" time, when the data is being provided. At "computation time", this is const (unless something like fracture happens, but we at least communicated that clearly).


For state/cache I am thinking super primitive here. In practical terms, nothing fancy. Something like:


```c++
class FemState {
public:
// State has full copy and move semantics.
// E.g. state0  = state makes sense and does what we expect.
DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN(FemState)

const FemCache& cache() const;
FemCache& mutable_cache() const;  // Notice that we still mark this method as `const`, since modifying the cache does not change the `state`. It's only an optimization.

// Getter/setter methods....

private:
std::vector<FemElement<T>> elements_;
Matrix3X<T> q_;
Matrix3X<T> v_;
mutable FemCache cache_;
};

struct FemCache {
DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN(FemCache)

// All these are "knonw" if I know the state. But we compute them here so that we don't need to recompute them when we need them.
// It might be that a std::vector<FemElement> is what we need, I only tried to convey the idea, not the fine details.
Matrix3<T> F_;
Matrix3<T> Dm_inv_;
T element_measure_;
T density_;
};
```
___
*[fem/fem_data.h, line 119 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEiGnf0TAlnViyZyCF:-MGhgE5O8fp6q1knjbYv:b-g2a604) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L119)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

The answer is yes to both questions (except that, of course, I used 0-based indexing). I will write up a little  [...]

2020-09-08 19:34 UTC, xuchenhan-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/1)* status: 5 of 66 files reviewed, 33 unresolved discussions (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[fem/corotated_linear_model.h, line 10 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGhz0hZ2Ucamw9fIxU_:-MGiTMVd6rkshpXgzmVT:bhy9ot6) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/corotated_linear_model.h#L10)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

could you add reference here locally?
</blockquote></details>

Will do.
___
*[fem/corotated_linear_model.h, line 18 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGhzJ3qDeUGvHJOd1O2:-MGiNlbqBWlmDWdSFdS_:b-8e250) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/corotated_linear_model.h#L18)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

could we use monogram notation? these are the positions of the vertices in what frame? in the reference configuration I assume?
</blockquote></details>

Yes, they are the vertex positions in the reference configuration. They are in world frame. Should I rename them to `p_WP`?
___
*[fem/corotated_linear_model.cc, line 8 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGi185d-EyoTTNhVf1_:-MGiTU-4DdatjHRdVIGa:bn4syhl) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/corotated_linear_model.cc#L8)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Looking at the code here (which I shouldn't need to from the signatures) I find out that these two versions of `DoUpdateDeformationBasedState()` have different semantics. One updates the strains assuming that we do know the rotation matrix, while the other actually update the rotation component "only" and not the strains.
It might just be that:
1. Those two methods deserves different names, with different purposes, different preconditions.
2. One of these methods is superfluous and there might be a cleaner alternative.
</blockquote></details>

There is only one version of `DoUpdateDeformationBasedState()`. I believe the other version you are referring to is `DoUpdatePostionBasedState()`?
___
*[fem/corotated_linear_model.cc, line 11 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGi65Ly3fHqOZvf8xG5:-MGiU-D78akIGs3uLYjg:b61q6h3) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/corotated_linear_model.cc#L11)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I would like us to figure out the proper monogram notation here. As with the rigid dynamics code, I am thinking it will pay off greatly. I started email discussion with Paul to talk about this.

Please refer to [these docs](https://drake.mit.edu/doxygen_cxx/group__multibody__notation__basics.html) with information in monogram notation and how we talk about rotation matrices. We should be able to use the same notation for rotation matrices for as long as we have well defined frames. For tensors....well, I started discussion with Paul.
</blockquote></details>

Not sure what the frames are here. I will follow the discussion with Paul.
___
*[fem/corotated_linear_model.cc, line 20 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGi1fk-C2xLCQ37-zRZ:-MGiUMWQ2G7iPB4m8WCP:b-a7isgd) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/corotated_linear_model.cc#L20)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

This surprised me.
I was hoping you'd take the deformation gradient F, and perform a polar decomposition to find out the rigid rotation component and the deformation component.
That approach has the nice side effect that with a single signature  for `DoUpdateDeformationBasedState()` (the one taking the gradients) you are done. It also has the nice side effect that this class represents an abstraction for a hyperelastic material more faithfully, that is, a function (rather complicated) of F only (nothing else like positions).

Now, you might have taken this approach instead because..... is it faster? some sort of optimization? 
</blockquote></details>

Again, `DoUpdateDeformationBasedState()` and `DoUpdatePositionBasedState()` are two different methods. I took this approach because it is the approached described in the referenced paper. I agree that taking the rotation part of the polar decomposition of `F` is also a good way of measuring the rotation of the element.

Another reason why it's done this way is because the `DoUpdatePositionBasedState()` is only called once per time step and the argument it takes in is the position at the end of the previous time step `q₀`. In other words, we are freezing the rotation back to the reference configuration. It reduces the system to a linear one instead of a nonlinear one if you rotate based on `F` which is a function of the current position `q`. Whether that's an approximation we want to make is another discussion.
___
*[fem/corotated_linear_model.cc, line 103 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGi92xCAcutMlkKYaZU:-MGib0821ZdRJKMX5vgH:b-al6jcf) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/corotated_linear_model.cc#L103)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

this is expensive, do we need it explicitly?
</blockquote></details>

Maybe there's a way around it but I don't see it. It's used in `FemForce::TensorContraction` if you want to take a look at potential optimization. We do provide the operator version `DoCalcFirstPiolaDifferential()` though.
___
*[fem/fem_data.h, line 3 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGhiiCaEhomO_Js5cl1:-MGicK1K5Jg1lKwe9-tI:b-ltm6x8) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L3)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

To be clear in this file what I meant on the separation between "data",  "state" and, possibly, "cache" (the last one being a nice way to organize things, not necessarily needed).

I am not thinking of a complicated cache framework as we do have in `systems::`, that'd be an overkill. I am rather thinking of a way to organize data in a simple way that does make sense in this scope were we know very well the dependencies.

I am thinking of something like this:
```c++
class FemData {
public:
int AddUndeformedObject(const MyMeshDataStructWhateveItIs& mesh,
                                              const MaterialProperties& properties);

int num_objects() const;

// Number of vertices for __all__ objects.
int num_vertices() const;

// Number of vertices for object `object_index`.
int num_vertices(ObjectIndex object_index) const;

// docs. Per element I assume?
const VectorX<T>& get_mass() const;

// Returns the reference configuration for __all__ meshes. Data storage is in this particular order... blah...
const Matrix3X<T>& get_Q() const;

// ....
};
```

Notice that `FemData` is `const` after the user is done adding data. Therefore if we see a mutable pointer to a `FemData` we'll think twice, because that should only happen at "registration" time, when the data is being provided. At "computation time", this is const (unless something like fracture happens, but we at least communicated that clearly).


For state/cache I am thinking super primitive here. In practical terms, nothing fancy. Something like:


```c++
class FemState {
public:
// State has full copy and move semantics.
// E.g. state0  = state makes sense and does what we expect.
DRAKE_DE [...]

2020-09-09 00:13 UTC, xuchenhan-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/1)* status: 5 of 66 files reviewed, 32 unresolved discussions (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[fem/corotated_linear_model.h, line 10 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGhz0hZ2Ucamw9fIxU_:-MGk9LAIBuNb-vm5DMhW:b-896fix) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/corotated_linear_model.h#L10)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Will do.
</blockquote></details>

Done.
___
*[fem/fem_data.h, line 33 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEhe543iwrUGLRl_d0:-MGjq-7hEfIBrYc4NpwY:birtss8) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L33)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Yes, we could. Thanks for the reference. Didn't know it existed.
</blockquote></details>

On second thought, I want to make sure it's a good idea to use `geometry::VolumeMesh`. I can see arguments both ways. 

Pro: using `geometry::VolumeMesh` is arguably better naming than `indices` and `positions`, and it makes sense to group these quantities together.
Con: I really only needs the indices and positions, and that's exactly the quantities I read in from vtk files. So if we are using `geometry::VolumeMesh`, I would find myself packing those quantities when reading the file only to unpack them here. 

Any thoughts on the trade-off? Thanks!
___
*[fem/fem_data.h, line 33 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEi8CF31LJRgjEXlSR:-MGjxkKRDP02Sns-gR7f:b-896fix) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L33)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Yes, you can. Will add documentation.
</blockquote></details>

Done.
___
*[fem/fem_data.h, line 119 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEiGnf0TAlnViyZyCF:-MGk17zD5Y2nGwtQYA5d:b-896fix) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L119)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Will do.
</blockquote></details>

Done.
___
*[fem/fem_data.h, line 124 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEixv92THN1EQwY79f:-MGk50wA2B5Lt3AMgGcc:b-896fix) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L124)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Will do.
</blockquote></details>

Done.
___
*[fem/fem_data.h, line 127 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEjOdqCzy18hElRf1y:-MGk0D9h1hadw1IWCa3X:b-k58y7t) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L127)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Will do.
</blockquote></details>

Done, how does it look?
___
*[fem/fem_data.h, line 132 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEjyzh4t4cqaL6qx4N:-MGk6isD0q_GzX4kHzz8:b-896fix) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L132)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Got it, will do.
</blockquote></details>

Done.
___
*[fem/fem_data.h, line 133 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEk3jn7WDTZeh_n6Md:-MGk98r51lbyklhnh39P:b-896fix) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L133)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Working, will do.
</blockquote></details>

Done.
___
*[fem/hyperelastic_constitutive_model.h, line 12 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGhp6SC3A0iK2ilKFWY:-MGkAR6b1k25AqZc4qbN:b-896fix) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/hyperelastic_constitutive_model.h#L12)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Working.
We definitely care about simulating viscosity and plasticity in the future (e.g. when we do fractures), but usually they are done through modifications to the deformation gradient not through the stress strain relationship. I'll add a note here to clarify that.
</blockquote></details>

Done.
___
*[fem/hyperelastic_constitutive_model.h, line 23 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGhvkEHEAJalqTSr53T:-MGkAX1HENLTBzH03SZF:b-896fix) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/hyperelastic_constitutive_model.h#L23)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Will do.
</blockquote></details>

Done.
___
*[fem/vtk_parser.h, line 17 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEeY9X2FeCArQsXt6C:-MGk9ICm2CkTCwGkkaD7:b-896fix) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/vtk_parser.h#L17)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

It's the result of a poorly done refactor. Will change to a free method.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-09 15:33 UTC, amcastro-tri requested changes
I just replied a few threads and resolved others. Thanks for the replies @xuchenhan-tri.  I will keep studying this.

> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-:-MGnUv6o1LQ38r_CNPSL:b-lgi8gb)* status: 1 of 66 files reviewed, 23 unresolved discussions (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[fem/corotated_linear_model.cc, line 11 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGi65Ly3fHqOZvf8xG5:-MGnJwR_DJ5Qe3JTEPeW:b-vu8f5e) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/corotated_linear_model.cc#L11)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Not sure what the frames are here. I will follow the discussion with Paul.
</blockquote></details>

Well, a rotation matrix usually relates two frames, that's why usually we write in monogram something like R_AB. Here we have that F = dx/dX, so there are two frames; a reference configuration frame, say E(X), and a deformed configuration frame, say e(x) (usually we use upper case for frames, but here I took the liberty  to use lower case at least for the sake of discussion). Notice these frames are a function of the material coordinate X, each material coordinate has an associated frame, I believe. Therefore F is at least associated with two frames, E and e. 
This is not a finished idea, I am just doing a brain dump, we need to clean up this idea a bit more.
___
*[fem/corotated_linear_model.cc, line 20 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGi1fk-C2xLCQ37-zRZ:-MGnLovt0FuOPMS0zmSL:b992ts8) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/corotated_linear_model.cc#L20)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Again, `DoUpdateDeformationBasedState()` and `DoUpdatePositionBasedState()` are two different methods. I took this approach because it is the approached described in the referenced paper. I agree that taking the rotation part of the polar decomposition of `F` is also a good way of measuring the rotation of the element.

Another reason why it's done this way is because the `DoUpdatePositionBasedState()` is only called once per time step and the argument it takes in is the position at the end of the previous time step `q₀`. In other words, we are freezing the rotation back to the reference configuration. It reduces the system to a linear one instead of a nonlinear one if you rotate based on `F` which is a function of the current position `q`. Whether that's an approximation we want to make is another discussion.
</blockquote></details>

what I am afraid of, is that `DoUpdatePositionBasedState()` only exists because we are trying to hack Muller's approach in this beautiful abstraction you put together. Do other material models need to overwrite this method?

It is not clear for me that Muller's approach is different from taking the polar decomposition of `F₀ = F(q₀)`, is it?
___
*[fem/corotated_linear_model.cc, line 103 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGi92xCAcutMlkKYaZU:-MGnMRjd2f6JFt-jnkKo:b-o9kkgt) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/corotated_linear_model.cc#L103)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Maybe there's a way around it but I don't see it. It's used in `FemForce::TensorContraction` if you want to take a look at potential optimization. We do provide the operator version `DoCalcFirstPiolaDifferential()` though.
</blockquote></details>

The problem here is that you are reaching the boundary of my knowledge haha. But this is my train of thought at this level; In linear elasticity we write `σᵢⱼ=cᵢⱼₖₗ εₖₗ`. While `cᵢⱼₖₗ` in principle has 81 coefficients, it is highly sparse (only 3 are independent for isotropic materials). This is due to the symmetries in the Cauchy and stress tensors (both major and minor symmetries). I'd like to understand the properties for dPdF and if these properties can lead to simpler and possibly cheaper calculations. 
As an example of what I mean, you never write `cᵢⱼₖₗ` explicitly when implementing FEM for linear elasticity and thus you don't need this four levels of nested loops. Is this unavoidable for general non-linear elasticity? 
___
*[fem/fem_data.h, line 29 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEgUyw3ctLPuu7kQAH:-MGnPm0J8OHogISX0In9:b-ulsrjc) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L29)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Working, will do.
</blockquote></details>

ok, lets talk more about this f2f so that we are sure we are on the same page. Remember I am always on Slack or the forever hangouts.
___
*[fem/fem_data.h, line 33 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEhe543iwrUGLRl_d0:-MGnQEPM9apLeW5LgpFr:bn4ju4e) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L33)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

On second thought, I want to make sure it's a good idea to use `geometry::VolumeMesh`. I can see arguments both ways. 

Pro: using `geometry::VolumeMesh` is arguably better naming than `indices` and `positions`, and it makes sense to group these quantities together.
Con: I really only needs the indices and positions, and that's exactly the quantities I read in from vtk files. So if we are using `geometry::VolumeMesh`, I would find myself packing those quantities when reading the file only to unpack them here. 

Any thoughts on the trade-off? Thanks!
</blockquote></details>

I don't have a quick answer. On the one hand, to store the "problem data" it could be nice. You can always use `VolumeMesh::vertices()` and `VolumeMesh::tetrahedra()` to access the raw data.
Then I can see how for "post-processed data" you'd store your own `std::vector`s with the global indexes. So it might be that a dual representation is best depending on the use?
___
*[fem/fem_data.h, line 127 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEjOdqCzy18hElRf1y:-MGnR5Px7EyGvreVwxjx:b-67qff3) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L127)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Done, how does it look?
</blockquote></details>

Thank you! very useful.
___
*[fem/fem_data.h, line 128 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEj_u16ArJW6XSQurw:-MGnRBVk3FZG_9sELpnC:b5jyn1o) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L128)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Sorry, it was a typo. I meant `x` vs. `q`.
</blockquote></details>

From Slack discussion it looks like people at least like `q` for the big "configuration vector storing the positions". I am ok with that. Local methods for instance computing a gradient or strain can the extract from q the relevant pieces and uses either FEM or monogram notation locally. All other quantities like stress and strain tensors can still use the standard FEM literature notation given they are "functions of state" and pretty much we have freedom for those.
___
*[fem/fem_data.h, line 133 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEkFsBDBOSxT034iY6:-MGnRn27BwF297w8Mjrf:b-4armyq) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L133)):*
> q* = qₙ + dt * vₙ,

I'll need to revisit this since it has different meaning for instance, from the ContactSolver referencing Duriez work (in which I am using the "star" variables to denote the predictor step which actually is implicit). 
N [...]

2020-09-09 16:39 UTC, xuchenhan-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/1)* status: 1 of 66 files reviewed, 23 unresolved discussions (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[fem/corotated_linear_model.cc, line 20 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGi1fk-C2xLCQ37-zRZ:-MGngkKU9wFunTDjFefB:b-xj5yin) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/corotated_linear_model.cc#L20)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

what I am afraid of, is that `DoUpdatePositionBasedState()` only exists because we are trying to hack Muller's approach in this beautiful abstraction you put together. Do other material models need to overwrite this method?

It is not clear for me that Muller's approach is different from taking the polar decomposition of `F₀ = F(q₀)`, is it?
</blockquote></details>

I took another look at this. I think you are right that 
```
Muller's approach is [not] different from taking the polar decomposition of F₀ = F(q₀).
```
Let me show you f2f and see if you agree.
___
*[fem/fem_data.h, line 133 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEkFsBDBOSxT034iY6:-MGnhWyH0n8aeaBasrrh:bxy9k6x) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L133)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

> q* = qₙ + dt * vₙ,

I'll need to revisit this since it has different meaning for instance, from the ContactSolver referencing Duriez work (in which I am using the "star" variables to denote the predictor step which actually is implicit). 
No big deal. Leh me finish looking at the math in this PR and I'll be back to this.
</blockquote></details>

Ah, yes, this would be a different use of "star". Here `q*` is just a handy temporary quantity.
___
*[fem/hyperelastic_constitutive_model.h, line 44 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGhwsRHEGUqmxSfAN4v:-MGnhxUzAmy-hwG6nBZX:btqzm7t) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/hyperelastic_constitutive_model.h#L44)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I replied in the CorotatedLinearModel. You put here a very nice abstraction, my fear is that this one method signature is only needed to implement Muller's paper (which IMO is not that great of a reference unless I am missing something important).

My question to you is (considering my lack of knowledge on the subject); how's Muller's formulation different from doing a polar decomposition on `F₀`? If we could write it like that, then this class would nicely encode Muller's work while maintaining this nice abstraction you came up with.


</blockquote></details>

Let's close this thread here and move the discussion to the other thread.
___
*[fem/hyperelastic_constitutive_model.h, line 56 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGhxNqz44WrvjgseW38:-MGniNAPB3w2rLEzA5SD:b-yqtv7a) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/hyperelastic_constitutive_model.h#L56)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I guess it depends on how it gets used, I need to keep reading. If this method is called withing a loop over all elements, I can see ways that would be efficient and cost us nothing (I am thinking of checking a boolean essentially).

Still, we should at least put a big warning in the docs if nothing else.
</blockquote></details>

Actually, `CalcEnergyDensity` exist only for testing purposes. `CalcFirstPiola` and `CalcFirstPiolaDifferential()`/`CalcFirstPiolaDerivative()` are called with in a loop over all elements. See `FemForce::AccumulateScaledElasticForce` for example.


<!-- Sent from Reviewable.io -->

2020-09-09 16:53 UTC, amcastro-tri requested changes
> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/1)* status: 1 of 66 files reviewed, 21 unresolved discussions (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[fem/corotated_linear_model.cc, line 20 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGi1fk-C2xLCQ37-zRZ:-MGnlniy7t3XB3ctZanQ:b-ohbt2l) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/corotated_linear_model.cc#L20)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I took another look at this. I think you are right that 
```
Muller's approach is [not] different from taking the polar decomposition of F₀ = F(q₀).
```
Let me show you f2f and see if you agree.
</blockquote></details>

oh, that'd be great, thank you.
___
*[fem/hyperelastic_constitutive_model.h, line 44 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGhwsRHEGUqmxSfAN4v:-MGnmB0p8Oc731O0fZ9R:bb73djm) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/hyperelastic_constitutive_model.h#L44)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Let's close this thread here and move the discussion to the other thread.
</blockquote></details>

SGTM


<!-- Sent from Reviewable.io -->

2020-09-09 17:05 UTC, amcastro-tri requested changes
> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/1)* status: 1 of 66 files reviewed, 24 unresolved discussions (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[fem/fem_force.h, line 15 at r2](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGnniU0AGU-vpS23Xpd:-MGnniU0AGU-vpS23Xpe:b-e66h5y) ([raw file](https://github.com/xuchenhan-tri/drake/blob/339d96ea63453ac1abaa31fd7152ea08903422b4/fem/fem_force.h#L15)):*
> ```objc
> namespace fem {
> /**
> FemForce calculates the elastic and damping forces from the constitutive models.
> ```

Here I see a mix of physics and numerical method.

I like the way for instance Hughes uses:
1. Describe the continuous equations in strong form with additional BCs. There is no numerics here.
2. Formulate the problem in the weak form. No numerics either, but lower requirements on the functional spaces.
3. Apply Galerkin approximation. Now the functional spaces are discrete, still integrations are exact (I don't need to think about qudratures)
4. Introduce quadratures to compute integrals.

I like that approach in that it is easy to describe. While the approach here requires to go through every step, in a nutshel I can describe Hughes approach (which in my mind is the classic approach) just saying: 1) These are my PDEs, 2) apply Galerking approximation on the weak formulation with these isoparametric elements and this quadrature. Done, no need to say anything else since all those steps are standard and apply to all FEM formulations. 

I wonder what the connection between those steps and the ones outlined here are.
___
*[fem/fem_force.h, line 18 at r2](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGnnWlR-Bc931PCWryp:-MGnnWlR-Bc931PCWryq:b33z7ol) ([raw file](https://github.com/xuchenhan-tri/drake/blob/339d96ea63453ac1abaa31fd7152ea08903422b4/fem/fem_force.h#L18)):*
> ```objc
> 
> Elastic Force:
> The elastic force comes from an energy E(q), and fₑ(q*) = -dE/dq(q*). The
> ```

What are the units of E? is it total energy or energy density? ditto for fₑ.
___
*[fem/fem_force.h, line 22 at r2](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGnnIXj0pxUGBgzuX3G:-MGnnIXkEBo2Sv0N3M0n:bs4cbol) ([raw file](https://github.com/xuchenhan-tri/drake/blob/339d96ea63453ac1abaa31fd7152ea08903422b4/fem/fem_force.h#L22)):*
> ```objc
>         w.r.t. q, we get
> 
>     fₑ(q) = -∑ₑ dϕ/dF * dF/dq * Vₑ = ∑ₑ P(F) * dF/dq * Vₑ.
> ```

I'd like to understand, if true, how this approach relates to the standard variational form used in FEM. That'd allow us to leverage on the strong theory results in FEM.


<!-- Sent from Reviewable.io -->

2020-09-10 22:00 UTC, xuchenhan-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/1)* status: 0 of 66 files reviewed, 23 unresolved discussions (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[fem/corotated_linear_model.cc, line 11 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGi65Ly3fHqOZvf8xG5:-MGtvH1ICMA2K80EiidF:b-gzetib) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/corotated_linear_model.cc#L11)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Well, a rotation matrix usually relates two frames, that's why usually we write in monogram something like R_AB. Here we have that F = dx/dX, so there are two frames; a reference configuration frame, say E(X), and a deformed configuration frame, say e(x) (usually we use upper case for frames, but here I took the liberty  to use lower case at least for the sake of discussion). Notice these frames are a function of the material coordinate X, each material coordinate has an associated frame, I believe. Therefore F is at least associated with two frames, E and e. 
This is not a finished idea, I am just doing a brain dump, we need to clean up this idea a bit more.
</blockquote></details>

I agree that F is associated with a relatively clear set of frames. I was not sure about R where is the concept of frames is a bit more elusive.
___
*[fem/corotated_linear_model.cc, line 20 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGi1fk-C2xLCQ37-zRZ:-MGtvbai4FJoSgHUfnaF:bq0efpf) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/corotated_linear_model.cc#L20)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

oh, that'd be great, thank you.
</blockquote></details>

Working on this.
___
*[fem/corotated_linear_model.cc, line 103 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGi92xCAcutMlkKYaZU:-MGtw7oc5yKeI_IKCEoD:bov983w) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/corotated_linear_model.cc#L103)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

The problem here is that you are reaching the boundary of my knowledge haha. But this is my train of thought at this level; In linear elasticity we write `σᵢⱼ=cᵢⱼₖₗ εₖₗ`. While `cᵢⱼₖₗ` in principle has 81 coefficients, it is highly sparse (only 3 are independent for isotropic materials). This is due to the symmetries in the Cauchy and stress tensors (both major and minor symmetries). I'd like to understand the properties for dPdF and if these properties can lead to simpler and possibly cheaper calculations. 
As an example of what I mean, you never write `cᵢⱼₖₗ` explicitly when implementing FEM for linear elasticity and thus you don't need this four levels of nested loops. Is this unavoidable for general non-linear elasticity? 
</blockquote></details>

I don't think there is anything in general you can exploit here. See the documentation for this method for example. We have entries in the rotation matrix appearing all over the 81 entries of the matrix. There may be things you can exploit on various levels for individual constitutive models, but I will need to spend more time to figure them out case-by-case.
___
*[fem/fem_data.h, line 33 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEhe543iwrUGLRl_d0:-MGtx1Nj1P6tkVXNiXgS:b-ub2gop) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L33)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I don't have a quick answer. On the one hand, to store the "problem data" it could be nice. You can always use `VolumeMesh::vertices()` and `VolumeMesh::tetrahedra()` to access the raw data.
Then I can see how for "post-processed data" you'd store your own `std::vector`s with the global indexes. So it might be that a dual representation is best depending on the use?

</blockquote></details>

Can you elaborate on what you mean by dual representation?
___
*[fem/fem_data.h, line 128 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEj_u16ArJW6XSQurw:-MGtxEfnE9GbQ8PbKdJM:b-9mfs3c) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L128)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

From Slack discussion it looks like people at least like `q` for the big "configuration vector storing the positions". I am ok with that. Local methods for instance computing a gradient or strain can the extract from q the relevant pieces and uses either FEM or monogram notation locally. All other quantities like stress and strain tensors can still use the standard FEM literature notation given they are "functions of state" and pretty much we have freedom for those.
</blockquote></details>

The sense I got from Slack discussion is to avoid using `x` for position, period.
___
*[fem/fem_force.h, line 15 at r2](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGnniU0AGU-vpS23Xpd:-MGu-Q6U6eVQXiRO6rPN:b-c43wp7) ([raw file](https://github.com/xuchenhan-tri/drake/blob/339d96ea63453ac1abaa31fd7152ea08903422b4/fem/fem_force.h#L15)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Here I see a mix of physics and numerical method.

I like the way for instance Hughes uses:
1. Describe the continuous equations in strong form with additional BCs. There is no numerics here.
2. Formulate the problem in the weak form. No numerics either, but lower requirements on the functional spaces.
3. Apply Galerkin approximation. Now the functional spaces are discrete, still integrations are exact (I don't need to think about qudratures)
4. Introduce quadratures to compute integrals.

I like that approach in that it is easy to describe. While the approach here requires to go through every step, in a nutshel I can describe Hughes approach (which in my mind is the classic approach) just saying: 1) These are my PDEs, 2) apply Galerking approximation on the weak formulation with these isoparametric elements and this quadrature. Done, no need to say anything else since all those steps are standard and apply to all FEM formulations. 

I wonder what the connection between those steps and the ones outlined here are.

</blockquote></details>

I'm not sure what you mean by "a mix of physics and numerical methods". "Physics" and "numerics" should be orthogonal concepts. Most methods here are routines that calculate numerical values for a physical quantity. 

If we are to fit this class into 4 steps you listed, it should be 4. In fact, everything (function space/BC/integral/etc) in the namespace fem is discrete. Everything continuous is pen and paper and belong to the (largely missing) documentation.
___
*[fem/fem_force.h, line 18 at r2](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGnnWlR-Bc931PCWryp:-MGtxR4F9kAR-cBWFC63:b-47bigq) ([raw file](https://github.com/xuchenhan-tri/drake/blob/339d96ea63453ac1abaa31fd7152ea08903422b4/fem/fem_force.h#L18)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

What are the units of E? is it total energy or energy density? ditto for fₑ.
</blockquote></details>

They are all densities.
___
*[fem/fem_force.h, line 22 at r2](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGnnIXj0pxUGBgzuX3G:-MGtxZEj8XN1HW3nHLGm:b-p2wxiv) ([raw file](https://github.com/xuchenhan-tri/drake/blob/339d96ea63453ac1abaa31fd7152ea08903422b4/fem/fem_force.h#L22)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I'd like to understand, if true, how this approach relates to the standard variational form used in FEM. That'd allow us to leverage o [...]

2020-09-14 17:09 UTC, amcastro-tri requested changes
Reading more code.....

But I wanted to share with you that I read "The Finite Element Method. VII" by Zienkiewicz, a classic.
Chapter 10 is a great read in that it captures very nicely your approach using the energy function, while still connecting to the (traditional?) variational formulation. I like several things about this chapter that capture some of the thoughts I wasn't able to articulate myself to you:
1. It does all derivations without resourcing to elements (discrete) first.
2. Introduces elements as a second step. I like that nothing in that math says anything about the order of the element, which is nice because an abstraction of those concepts would enable this off the shelf. 
3. This one I'm fuzzy, but I wanted to run it by you.  Zienkiewicz advocates that writing the formulation in the current configuration leads to simpler code that exploits the structure from linear code. He does the derivations in the reference configuration, but seems to prefer the actual code in current configuration because he claims it is simpler.

Re bullet (3), leh me rephrase what Zienkiewicz says in section 10.3 of the book:

> The simplest approach is to start from a reference configuration since here
integrals are all expressed over domains which do not change during the deformation
process and thus are not affeccted by variation or linearization steps. Later the results
can be transformed and written in terms of the deformed configuration. Using the
reference configuration form variations and linearizations can be carried out in an
identical manner as was done in the small deformation case. Thus, all the steps out-
lined in Chapter 1 immediately can be extended to the finite deformation problem. We
shall discover that the final equations obtained by this approach are very diferent
from those of the small deformation problem. However, after all derivation steps
are completed a transformation to expressions integrated over the current configura-
tion will yield a form which is nearly identical to the small deformation problem and
thus greatly simplifies the development of the final force and stiffness terms as well as
programming steps.

Another excellent point (or claim?) by Zienkiewicz. The use of PK2 instead of PK1. Given PK2 is symmetric, using it along its conjugate Green strain (also symmetric), leads to a great deal of simplification on the derivatives (as far as I understand it). Zienkiewicz calls this derivative the "tangent moduli" and it is a 6x6 matrix, instead of the 9x9 matrix we have now in `DoCalcFirstPiolaDerivative()`. 
The approach seems standard, also Hughes uses it in Section 2 of his book. The "trick" seems to be to expresses second order tensors (stress and strain) as 6-dimensional vectors. Using the physical geometries of conjugate pairings, you can express the tangent moduli (derivative of stress with respect of strain) as a 6x6 matrix.

I'd like to take these formulations seriously, since it seems it is the standard practice. Thoughts?

I'd like you if possible to read this chapter so that we can discuss. I'll keep reviewing the code.

> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-:-MHCOpqZ2Fo9VdphZKCt:b8ryteg)* status: 0 of 66 files reviewed, 21 unresolved discussions (waiting on @amcastro-tri, @SeanCurtis-TRI, and @xuchenhan-tri)

___
*[fem/corotated_linear_model.cc, line 20 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGi1fk-C2xLCQ37-zRZ:-MHBtKr148CyyaY5ndTx:bu4lpmg) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/corotated_linear_model.cc#L20)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Working on this.
</blockquote></details>

ok. In the meantime I can keep looking at the rest.
___
*[fem/fem_data.h, line 121 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEihYG9Esr1aiPwWZG:-MHBtXr5--EDGFGjcxeb:br4mz1q) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L121)):*
> Unless you are thinking about a big VolumeMesh that include all the deformable geometries?

Definitely not.

Just something to ponder on. Maybe the input could be fed using VolumeMesh (wich does encode the proper local indexing) and then internally you do use std::vector of the quantities you need for internal computation. The advantage I could see is so that we wouldn't need to rewrite geometry code. Something you'd need to play with. I'd say, list pros- and cons- of each approach and then make an educated decision based on that data. Maybe @seancurtis-tri could help us here.
___
*[fem/fem_data.h, line 128 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEj_u16ArJW6XSQurw:-MHBu7oxEAYz-jS6kDi3:bmlw7mu) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L128)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

The sense I got from Slack discussion is to avoid using `x` for position, period.
</blockquote></details>

That's right, that's exactly what I wrote above.
___
*[fem/fem_force.h, line 35 at r4](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MHBwBrP7cz20PFbWQiP:-MHBwBrQ3ZdPxaEKzvNV:b-134dpu) ([raw file](https://github.com/xuchenhan-tri/drake/blob/eed968222c85d9aff069eae2fe412453a39288ca/fem/fem_force.h#L35)):*
> ```objc
>     Q(0,0,0) = Q0, Q(1,0,0) = Q1, Q(0,1,0) = q2, Q(0,0,1) = Q3.
> 
> then qi = FQi+b for i=0,1,2,3.
> ```

What is FQi here?


<!-- Sent from Reviewable.io -->

2020-09-14 17:30 UTC, xuchenhan-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/1)* status: 0 of 66 files reviewed, 20 unresolved discussions (waiting on @amcastro-tri, @SeanCurtis-TRI, and @xuchenhan-tri)

___
*[fem/fem_data.h, line 128 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEj_u16ArJW6XSQurw:-MHCdxiC2RhNCBXjSv5M:b-el4uqh) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L128)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

That's right, that's exactly what I wrote above.
</blockquote></details>

Ok, all `x` should be gone the next time I push.
___
*[fem/fem_force.h, line 35 at r4](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MHBwBrP7cz20PFbWQiP:-MHCeZKG1MCrunRaVhdQ:b-v8ud6m) ([raw file](https://github.com/xuchenhan-tri/drake/blob/eed968222c85d9aff069eae2fe412453a39288ca/fem/fem_force.h#L35)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

What is FQi here?
</blockquote></details>

It's F * Qi.


<!-- Sent from Reviewable.io -->

2020-09-15 14:25 UTC, amcastro-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/1)* status: 0 of 68 files reviewed, 20 unresolved discussions (waiting on @amcastro-tri, @SeanCurtis-TRI, and @xuchenhan-tri)

___
*[fem/fem_data.h, line 128 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEj_u16ArJW6XSQurw:-MHH8a_C0Fbnw073NKtl:b-m9171a) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L128)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Ok, all `x` should be gone the next time I push.
</blockquote></details>

that's fine, no rush. We'll clean these up as you push into master. I am ok with any notation for the prototype. Though of course if you keep changes here more or less in sync with what you push into master, it'll simplify your rebasing process. 


<!-- Sent from Reviewable.io -->

2020-09-15 14:59 UTC, amcastro-tri requested changes
great progress!. Studying the new changes.

> Reviewed 1 of 10 files at r2, 2 of 28 files at r5.
> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-:-MHHGmL273nGZnnti1hw:b-g2wjpp)* status: 3 of 68 files reviewed, 24 unresolved discussions (waiting on @amcastro-tri, @SeanCurtis-TRI, and @xuchenhan-tri)

___
*[fem/fem_state.h, line 16 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MHHEymyDQE9swJA50Lq:-MHHEymyDQE9swJA50Lr:bgnhser) ([raw file](https://github.com/xuchenhan-tri/drake/blob/4d9bfd29617fbccbd401dc823815a39fa5d2be29/fem/fem_state.h#L16)):*
> ```objc
> class FemState {
>  public:
>   const Matrix3X<T>& get_v0() const { return v0_; }
> ```

In Drake the concept of state has to do with "what is the minimum set of variables that describes the physical state of my system".

For a mechanical system that'd be `q(t)` and `v(t)` at some specified time `t`.

Therefore, "state" `s(t)` should only store `q(t)` and `v(t)`, not needing `q0` nor `v0`.

But, where do we put q0 and v0!!? well... we put those in `state0` :-). Makes sense?

Then `FemState` would be this very small class with copy semantics that we can move and copy around easily and cheaply, with clear understanding of what state it represents for a particular time instance.
___
*[fem/fem_state.h, line 22 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MHHFzFhB-GInU5Sn7XA:-MHHFzFhB-GInU5Sn7XB:b-ebkga4) ([raw file](https://github.com/xuchenhan-tri/drake/blob/4d9bfd29617fbccbd401dc823815a39fa5d2be29/fem/fem_state.h#L22)):*
> ```objc
>   }
> 
>   const Matrix3X<T>& get_v_star() const { return v_star_; }
> ```

didn't read there yet, but I'd argue that things like `q_star` and `v_star` are `FemSolver` states, not "modeling states. 
We can discuss this point f2f.
___
*[fem/fem_state.h, line 61 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MHHGG8z0uvOJbDRuw0H:-MHHGG8z0uvOJbDRuw0I:bzdofjm) ([raw file](https://github.com/xuchenhan-tri/drake/blob/4d9bfd29617fbccbd401dc823815a39fa5d2be29/fem/fem_state.h#L61)):*
> ```objc
>   }
> 
>   const std::vector<Matrix3<T>>& get_F0() const { return F0_; }
> ```

ditto, this would live in `state0`.
___
*[fem/fem_state.h, line 89 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MHHGMNNBjpg9Z3tI9Kh:-MHHGMNNBjpg9Z3tI9Ki:bng9kfc) ([raw file](https://github.com/xuchenhan-tri/drake/blob/4d9bfd29617fbccbd401dc823815a39fa5d2be29/fem/fem_state.h#L89)):*
> ```objc
>   }
> 
>   const std::vector<Eigen::Matrix<T, 9, 9>>& get_dPdF() const { return dPdF_; }
> ```

I'd like to nail this down because I think it is both physically and computationally important.
Zienkiewics uses dSdE (derivative of PK2 with respect to Green strain, it's energy conjugate), a symmetric 6x6 matrix (i.e. 21 vs 81 coefficients).
___
*[fem/hyperelastic_constitutive_model.h, line 18 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGhvQk63GL_TLlQJEd-:-MHH96hkCfgbWXhLiSDn:b-ikjjdf) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/hyperelastic_constitutive_model.h#L18)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

How about moving `E` and `nu' to the inherited class and keep `alpha` and `beta` in here?
</blockquote></details>

I believe this class should have no actual data, but the specific material models do. I can be convince otherwise if you have a specific argument.
___
*[fem/hyperelastic_constitutive_model.h, line 102 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGhxuuzDHbKA9Py9dXG:-MHH9cHM5UdF69U5sZob:b-9me0ne) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/hyperelastic_constitutive_model.h#L102)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

The only symmetry I see that is i <-> alpha and j <-> beta, which is essentially the symmetry coming from second order derivatives.
</blockquote></details>

Right, you lost an additional symmetry given PK1 is non-symmetric. That is why I am wondering if PK2 would be best for performance and simplicity. 

Per Zienkiewicks book, I wonder if a better abstraction layer here would be `CalcTangentModuli()` which would compute a 6x6 symmetric matrix instead. That is 21 coefficients vs. 81. If correct, that's a factor of four faster! And probably even more, given that now the product B̂ᵀ⋅D̂ₜ⋅B̂ in Zienkiewicks, Eq. 10.66 (which encapsulates the contraction) is much smaller and can even exploit the symmetry of D.


<!-- Sent from Reviewable.io -->

2020-09-15 15:50 UTC, xuchenhan-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/1)* status: 3 of 68 files reviewed, 24 unresolved discussions (waiting on @amcastro-tri, @SeanCurtis-TRI, and @xuchenhan-tri)

___
*[fem/fem_data.h, line 121 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEihYG9Esr1aiPwWZG:-MHHOzff1XYSqvG5-DjJ:b-6myrl6) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L121)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

> Unless you are thinking about a big VolumeMesh that include all the deformable geometries?

Definitely not.

Just something to ponder on. Maybe the input could be fed using VolumeMesh (wich does encode the proper local indexing) and then internally you do use std::vector of the quantities you need for internal computation. The advantage I could see is so that we wouldn't need to rewrite geometry code. Something you'd need to play with. I'd say, list pros- and cons- of each approach and then make an educated decision based on that data. Maybe @seancurtis-tri could help us here.
</blockquote></details>

From what I understood from the discussion in the softsim meeting, Sean's suggestion is not to use `geometry::VolumeMesh`. Do you agree?
___
*[fem/fem_state.h, line 16 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MHHEymyDQE9swJA50Lq:-MHHRwVsEA9cM204THhZ:b6agza3) ([raw file](https://github.com/xuchenhan-tri/drake/blob/4d9bfd29617fbccbd401dc823815a39fa5d2be29/fem/fem_state.h#L16)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

In Drake the concept of state has to do with "what is the minimum set of variables that describes the physical state of my system".

For a mechanical system that'd be `q(t)` and `v(t)` at some specified time `t`.

Therefore, "state" `s(t)` should only store `q(t)` and `v(t)`, not needing `q0` nor `v0`.

But, where do we put q0 and v0!!? well... we put those in `state0` :-). Makes sense?

Then `FemState` would be this very small class with copy semantics that we can move and copy around easily and cheaply, with clear understanding of what state it represents for a particular time instance.
</blockquote></details>

Let's discuss this more f2f.
___
*[fem/fem_state.h, line 89 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MHHGMNNBjpg9Z3tI9Kh:-MHHS0vDCA14JM629OSc:bab5y83) ([raw file](https://github.com/xuchenhan-tri/drake/blob/4d9bfd29617fbccbd401dc823815a39fa5d2be29/fem/fem_state.h#L89)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I'd like to nail this down because I think it is both physically and computationally important.
Zienkiewics uses dSdE (derivative of PK2 with respect to Green strain, it's energy conjugate), a symmetric 6x6 matrix (i.e. 21 vs 81 coefficients).
</blockquote></details>

In general I don't see how to calculate dSdE if the energy density is written as a function of F instead of E (other than calculating dPdF first).
___
*[fem/hyperelastic_constitutive_model.h, line 18 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGhvQk63GL_TLlQJEd-:-MHHIFPB8m6rwMgnAVnC:bu74otg) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/hyperelastic_constitutive_model.h#L18)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I believe this class should have no actual data, but the specific material models do. I can be convince otherwise if you have a specific argument.
</blockquote></details>

I don't have too much experience modelling damping. Currently I'm using Rayleigh damping for all models and thus `alpha` and `beta` being in this class. Do you have some other models in mind?
___
*[fem/hyperelastic_constitutive_model.h, line 102 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGhxuuzDHbKA9Py9dXG:-MHHKG1o4jy783kZ7_E0:b-d4z2wi) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/hyperelastic_constitutive_model.h#L102)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Right, you lost an additional symmetry given PK1 is non-symmetric. That is why I am wondering if PK2 would be best for performance and simplicity. 

Per Zienkiewicks book, I wonder if a better abstraction layer here would be `CalcTangentModuli()` which would compute a 6x6 symmetric matrix instead. That is 21 coefficients vs. 81. If correct, that's a factor of four faster! And probably even more, given that now the product B̂ᵀ⋅D̂ₜ⋅B̂ in Zienkiewicks, Eq. 10.66 (which encapsulates the contraction) is much smaller and can even exploit the symmetry of D.
</blockquote></details>

The reason this formulation works out nicely is because St-Venant Kirchhoff can be written as a quadratic function in E with a constant D. For a general constitutive model, I don't see a way to calculate PK2 and D other than through PK1 and dPdF. 

You mentioned multiple times that this is an abstraction level thing, but I don't see it that way. The formulation here is B = dE/du and D = dS/dE. I could easily use the same abstraction but swap the underlying implementation to B = dF/du and D = dP/dF and we are back in the world of PK1.

Either way, how much speed gain does it give us? This all happens within building the A matrix, at the scale we are running, the majority of the time is spent on solving the linear system based on experience and my profiling for the demo.


<!-- Sent from Reviewable.io -->

2020-09-16 15:37 UTC, amcastro-tri requested changes
> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/1)* status: 3 of 68 files reviewed, 16 unresolved discussions (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[fem/fem_data.h, line 121 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEihYG9Esr1aiPwWZG:-MHMWYko8zIN2dTPClE4:b-d34lwe) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L121)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

From what I understood from the discussion in the softsim meeting, Sean's suggestion is not to use `geometry::VolumeMesh`. Do you agree?
</blockquote></details>

I agree. 
___
*[fem/fem_force.h, line 35 at r4](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MHBwBrP7cz20PFbWQiP:-MHMWbtfAaantCO3pZDk:b-7z9okm) ([raw file](https://github.com/xuchenhan-tri/drake/blob/eed968222c85d9aff069eae2fe412453a39288ca/fem/fem_force.h#L35)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

It's F * Qi.
</blockquote></details>

thanks. I advocate for writing F*Qi from now on.
___
*[fem/hyperelastic_constitutive_model.h, line 18 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGhvQk63GL_TLlQJEd-:-MHMY2vy-6kAzhoUvYIL:b1jrts4) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/hyperelastic_constitutive_model.h#L18)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I don't have too much experience modelling damping. Currently I'm using Rayleigh damping for all models and thus `alpha` and `beta` being in this class. Do you have some other models in mind?
</blockquote></details>

I actually think Rayleigh is  ok for most practical cases. I was wondering you you really wanted to set this model in stone.
Another options is that `HyperelasticConstitutiveModel` only computes the energy part of the stresses, and we move the computation of damping somewhere else (even to FemSolver if practical).
I just liked the idea of `HyperelasticConstitutiveModel` representing this idea of an energy function of state. It is clear and clean. 

However, if you believe more practical this way, I could live with damping in this class for now. For you to consider.


<!-- Sent from Reviewable.io -->

2020-09-16 15:38 UTC, amcastro-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/1)* status: 3 of 68 files reviewed, 16 unresolved discussions (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[fem/fem_data.h, line 33 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MGEhe543iwrUGLRl_d0:-MHMZAM-6IqntcrIGEHR:bfd0oy) ([raw file](https://github.com/xuchenhan-tri/drake/blob/da899e217d2df74797a313ac4428b926971f5be7/fem/fem_data.h#L33)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Can you elaborate on what you mean by dual representation?
</blockquote></details>

ignore. Per f2f with Sean, it does not seem convenient to use VolumeMehsh


<!-- Sent from Reviewable.io -->

2020-09-16 16:25 UTC, amcastro-tri requested changes
working, working, working.....

> Reviewed 2 of 28 files at r5.
> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-:-MHMj173DlrFYeWANrkc:beb26f6)* status: 5 of 68 files reviewed, 30 unresolved discussions (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[fem/backward_euler_objective.h, line 20 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MHMZSwj0t0A4CnsX0CD:-MHMZSwj0t0A4CnsX0CE:b8zzjw9) ([raw file](https://github.com/xuchenhan-tri/drake/blob/4d9bfd29617fbccbd401dc823815a39fa5d2be29/fem/backward_euler_objective.h#L20)):*
> ```objc
>  Using qⁿ⁺¹ = qⁿ + dt * vⁿ⁺¹, we get
> 
>  G(x) = M*x - f(qⁿ + dt * (vⁿ + x), vⁿ + x) * dt.
> ```

not sure having an additional symbol `x` buys anything here. Unless there is a specific reason, why not to just write everything as a function of ` vⁿ⁺¹`, the resulting expressions seem  to have the same length.
___
*[fem/backward_euler_objective.h, line 22 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MHMZjPkE_toyrYljFZ1:-MHMZjPkE_toyrYljFZ2:bx7156e) ([raw file](https://github.com/xuchenhan-tri/drake/blob/4d9bfd29617fbccbd401dc823815a39fa5d2be29/fem/backward_euler_objective.h#L22)):*
> ```objc
>  G(x) = M*x - f(qⁿ + dt * (vⁿ + x), vⁿ + x) * dt.
> 
>  and dG/dx = M - ∂f/∂q * dt² - ∂f/∂v * dt.
> ```

why not just `dG/dv`, which gives you the same results and avoid an extra symbol x.
___
*[fem/backward_euler_objective.h, line 25 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MHMZqmjBov5pinNG6zy:-MHMZqmjBov5pinNG6zz:b1zyz3) ([raw file](https://github.com/xuchenhan-tri/drake/blob/4d9bfd29617fbccbd401dc823815a39fa5d2be29/fem/backward_euler_objective.h#L25)):*
> ```objc
> 
>  Update quantities depending on x to prepare for residual calculation and
>  the linear solve. More specifically, we need v* = vⁿ + x and q* = qⁿ + dt *
> ```

per definition above `x = dv = vⁿ⁺¹ - vⁿ`, it seems like `v* = vⁿ⁺¹`? 
___
*[fem/backward_euler_objective.h, line 31 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MHM_F8cBkDdL1fO8acJ:-MHM_F8d8pj0RDJj87vc:b-wzo9m4) ([raw file](https://github.com/xuchenhan-tri/drake/blob/4d9bfd29617fbccbd401dc823815a39fa5d2be29/fem/backward_euler_objective.h#L31)):*
> ```objc
> 
> 
>  We need to solve A * dx = b for dx where b = -G(x) calculated with
> ```

I believe you could write this as `A*dv = -G(v)` also?
___
*[fem/backward_euler_objective.h, line 40 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MHMb16g5t7Kj3xMP9I5:-MHMb16g5t7Kj3xMP9I6:bo15e9d) ([raw file](https://github.com/xuchenhan-tri/drake/blob/4d9bfd29617fbccbd401dc823815a39fa5d2be29/fem/backward_euler_objective.h#L40)):*
> Vₑ

What volume is this? reference configuration? did you purposely use capital V to denote reference configuration?
___
*[fem/backward_euler_objective.h, line 40 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MHMbMI05QtREV01frm1:-MHMbMI05QtREV01frm2:b-il0c8f) ([raw file](https://github.com/xuchenhan-tri/drake/blob/4d9bfd29617fbccbd401dc823815a39fa5d2be29/fem/backward_euler_objective.h#L40)):*
> ```objc
>  time:
> 
>  dfₑ/dq = -K(q) = -d²E/dq² = -∑ₑ (dF/dq) : dP/dF : dF/dq * Vₑ. There is no
> ```

I assume `∑ₑ` covers the elements adjacent to a particular node. Confusing a bit because not sure if `fe` contains all nodal forces, or a particular node.
Unless there is a reason to include the idea of "element" as this level, I'd prefer equations in terms of integrals, which quickly connect to the continuum model. 
Then only when needed you go down all the way to element.

Also, I'd include the term d²F/dq² as you explained it to me, and then just say "from now on we assume it equal to zero since F is linear for linear FEM".
___
*[fem/backward_euler_objective.h, line 52 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MHMcgA3EDXUQEj-_p_b:-MHMcgA3EDXUQEj-_p_c:b-mj0x5v) ([raw file](https://github.com/xuchenhan-tri/drake/blob/4d9bfd29617fbccbd401dc823815a39fa5d2be29/fem/backward_euler_objective.h#L52)):*
> ```objc
>  We omit it as does in [Sifakis, 2012] which claims that this modification
>  does not affect convergence of Newton's method. Therefore, technically we
>  are using a modified Newton's method.
> ```

nit, not sure if "modified" is the term of art. I've seen quasi-Newton most often, if that's what you mean.
___
*[fem/backward_euler_objective.h, line 54 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MHMct53EYvmEv48XXHh:-MHMct53EYvmEv48XXHi:b-aox3x3) ([raw file](https://github.com/xuchenhan-tri/drake/blob/4d9bfd29617fbccbd401dc823815a39fa5d2be29/fem/backward_euler_objective.h#L54)):*
> ```objc
>  are using a modified Newton's method.
> 
>  ∂fd/∂v = D = alpha * M + beta * K.
> ```

let's see if I understand. You are saying this is only used to approximate the Jacobian?

Not sure if it belongs her or in FemForce but, could you provide the expression of the damping force somewhere? I much rather prefer the continuum version rather that some sort of discrete version that depends on the particular choice of FEM.
___
*[fem/backward_euler_objective.h, line 60 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MHMdI_L4GO2qwPzDzPp:-MHMdI_L4GO2qwPzDzPq:bbyvx0p) ([raw file](https://github.com/xuchenhan-tri/drake/blob/4d9bfd29617fbccbd401dc823815a39fa5d2be29/fem/backward_euler_objective.h#L60)):*
> ```objc
>  A = (1+alpha*dt) * M + (beta * dt + dt²) * K.
> 
>  We delegate the actual calculation of forming K or calculating K*x to FemForce.
> ```

I need to study FemForce (sorry for being slow, one file at a time) but, this comment seems to indicate that `BackwardEulerObjective` is the only one that knows or takes care about damping?

I wonder if instead `FemForce` could provide an "approximate" jacobian so all the modeling responsibility lives in a single place.
___
*[fem/backward_euler_objective.h, line 69 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MHMdxVKD9sAGPUSxyOT:-MHMdxVKD9sAGPUSxyOU:b-qk5n89) ([raw file](https://github.com/xuchenhan-tri/drake/blob/4d9bfd29617fbccbd401dc823815a39fa5d2be29/fem/backward_euler_objective.h#L69)):*
> ```objc
> 
>   BackwardEulerObjective(const FemData<T>& data, FemState<T>* state,
>                          const FemForce<T>& force)
> ```

I need to read more but on a quick inspection, `BackwardEulerObjective` seems to have the flavor of "a functor that NewtonSolver can talk to".

It seems like the "interface" to talk to NewtonSolver is with methods like 
___
*[fem/backward_euler_objective.h, line 80 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MHMiGrw00OhcpNqP6uh:-MHMiGrw00OhcpNqP6ui:b6kbymf) ([raw file](https://github.com/xuchenhan-tri/drake/blob/4d9bfd29617fbccbd401dc823815a39fa5d2be29/fem/backward_euler_objective.h#L80)):*
> ```objc
>   /** Evaluate -G(x) = -M*x + f(qⁿ + dt * (vⁿ + x), vⁿ + x) * dt, where f = fe +
>    * fd + gravity. */
>   void CalcResidual(const Eigen::Ref<const VectorX<T>>& dv,
> ```

question, I wonder if you considered these signatures to take a `state_` object instead of `dv`. That is, that `NewtonSolver` does know about `FemState` and uses it to communicate with the object. I wonder this because I believe that'd help get rid of this sequence of `UpdateFoo()` calls for which it is not immediately obvious (without lots of docs) who is responsible for calling them.
Is there a reason `NewtonSolver` shold not use `FemState` as a way to communicate "iteration state"?  that might imply that you'd need to write the equations in terms of `v` instead of `dv`, but probably worth it if it cleans up things?
___
*[fem/backward_euler_objective.cc, line 28 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MHMgvKHA7Xz_J9V3MeX:-MHMgvKHA7Xz_J9V3MeY:b-dv8kyx) ([raw file](https://github.com/xuchenhan-tri/drake/blob/4d9bfd29617fbccbd401dc823815a39fa5d2be29/fem/backward_euler_objective.cc#L28)):*
> ```cpp
> template <typename T>
> void BackwardEulerObjective<T>::CalcResidual(
>     const Eigen::Ref<const VectorX<T>>& dv,
> ```

not cle [...]

2020-09-17 16:25 UTC, xuchenhan-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/1)* status: 5 of 68 files reviewed, 29 unresolved discussions (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[fem/backward_euler_objective.h, line 20 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MHMZSwj0t0A4CnsX0CD:-MHNa64b1-MaOlYcd4bt:b2n17tc) ([raw file](https://github.com/xuchenhan-tri/drake/blob/4d9bfd29617fbccbd401dc823815a39fa5d2be29/fem/backward_euler_objective.h#L20)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

not sure having an additional symbol `x` buys anything here. Unless there is a specific reason, why not to just write everything as a function of ` vⁿ⁺¹`, the resulting expressions seem  to have the same length.
</blockquote></details>

I find it helpful to be very explicit about what's the nonlinear equation we are solving for. Here I chose to formulate the set of nonlinear equations that we are solving for as `G(z) = 0`, where `z = dv`. 
___
*[fem/backward_euler_objective.h, line 22 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MHMZjPkE_toyrYljFZ1:-MHNa3bV2aTxrDPLV_gu:b-hyjmor) ([raw file](https://github.com/xuchenhan-tri/drake/blob/4d9bfd29617fbccbd401dc823815a39fa5d2be29/fem/backward_euler_objective.h#L22)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

why not just `dG/dv`, which gives you the same results and avoid an extra symbol x.
</blockquote></details>

I find it helpful to be very explicit about what's the nonlinear equation we are solving for.
___
*[fem/backward_euler_objective.h, line 25 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MHMZqmjBov5pinNG6zy:-MHNYcP-5sQhxpPZd8qP:bvu3hrf) ([raw file](https://github.com/xuchenhan-tri/drake/blob/4d9bfd29617fbccbd401dc823815a39fa5d2be29/fem/backward_euler_objective.h#L25)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

per definition above `x = dv = vⁿ⁺¹ - vⁿ`, it seems like `v* = vⁿ⁺¹`? 
</blockquote></details>

I forgot to remove all `x` as promised here. I'm changing all `x` here to `z`, the variable we are solving for in the newton iterations.
___
*[fem/backward_euler_objective.h, line 31 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MHM_F8cBkDdL1fO8acJ:-MHNYvWKEBGFZzfO2keq:b-jn3zgs) ([raw file](https://github.com/xuchenhan-tri/drake/blob/4d9bfd29617fbccbd401dc823815a39fa5d2be29/fem/backward_euler_objective.h#L31)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I believe you could write this as `A*dv = -G(v)` also?
</blockquote></details>

No. I used a separate variable name to try to avoid mistakes like this. You could write it as `A*ddv = -G(v)`. Like I said in the previous threads, I find it helpful to be very explicit about what's the nonlinear equation we are solving for. In this case, we are solving for `G(z) = 0`, where `z = dv`.  So each iteration we are solving for `A*dz = -G(z)`, which translates to `A*ddv = -G(dv)`.
___
*[fem/backward_euler_objective.h, line 40 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MHMb16g5t7Kj3xMP9I5:-MHNaxj--Hf1CmqByook:b-y1kild) ([raw file](https://github.com/xuchenhan-tri/drake/blob/4d9bfd29617fbccbd401dc823815a39fa5d2be29/fem/backward_euler_objective.h#L40)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

> Vₑ

What volume is this? reference configuration? did you purposely use capital V to denote reference configuration?


</blockquote></details>

Yes this is reference configuration.
___
*[fem/backward_euler_objective.h, line 40 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MHMbMI05QtREV01frm1:-MHNb4wp6hjXvN6vWBnc:b-dxo2r4) ([raw file](https://github.com/xuchenhan-tri/drake/blob/4d9bfd29617fbccbd401dc823815a39fa5d2be29/fem/backward_euler_objective.h#L40)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I assume `∑ₑ` covers the elements adjacent to a particular node. Confusing a bit because not sure if `fe` contains all nodal forces, or a particular node.
Unless there is a reason to include the idea of "element" as this level, I'd prefer equations in terms of integrals, which quickly connect to the continuum model. 
Then only when needed you go down all the way to element.

Also, I'd include the term d²F/dq² as you explained it to me, and then just say "from now on we assume it equal to zero since F is linear for linear FEM".


</blockquote></details>

This is an unfortunate clash of subscript `e`. I meant to denote "elastic force" with `fe`. Maybe moving the `e` to a superscript helps?
Re the d²F/dq² term, will do.
___
*[fem/backward_euler_objective.h, line 52 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MHMcgA3EDXUQEj-_p_b:-MHRsAqf2K3F0F-bMhe5:bhy9ot6) ([raw file](https://github.com/xuchenhan-tri/drake/blob/4d9bfd29617fbccbd401dc823815a39fa5d2be29/fem/backward_euler_objective.h#L52)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, not sure if "modified" is the term of art. I've seen quasi-Newton most often, if that's what you mean.
</blockquote></details>

Will do.
___
*[fem/backward_euler_objective.h, line 54 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MHMct53EYvmEv48XXHh:-MHNblDW6JAIhJuxcgG3:b8k1pg) ([raw file](https://github.com/xuchenhan-tri/drake/blob/4d9bfd29617fbccbd401dc823815a39fa5d2be29/fem/backward_euler_objective.h#L54)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

let's see if I understand. You are saying this is only used to approximate the Jacobian?

Not sure if it belongs her or in FemForce but, could you provide the expression of the damping force somewhere? I much rather prefer the continuum version rather that some sort of discrete version that depends on the particular choice of FEM.
</blockquote></details>

Not exactly sure what you are trying to say here. Are you suggesting this comment is misplaced and should belong to FemForce? In that case, I agree and will do.
___
*[fem/backward_euler_objective.h, line 60 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MHMdI_L4GO2qwPzDzPp:-MHNc4aR7Xs9sgLdV5UO:b-gd9g0v) ([raw file](https://github.com/xuchenhan-tri/drake/blob/4d9bfd29617fbccbd401dc823815a39fa5d2be29/fem/backward_euler_objective.h#L60)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I need to study FemForce (sorry for being slow, one file at a time) but, this comment seems to indicate that `BackwardEulerObjective` is the only one that knows or takes care about damping?

I wonder if instead `FemForce` could provide an "approximate" jacobian so all the modeling responsibility lives in a single place.
</blockquote></details>

Again, I believe you are complaining about the misplaced comment (correct me if I misunderstood). Will move to FemForce.
___
*[fem/backward_euler_objective.h, line 69 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MHMdxVKD9sAGPUSxyOT:-MHNcSAP-ixAolFADMFs:bmyem8e) ([raw file](https://github.com/xuchenhan-tri/drake/blob/4d9bfd29617fbccbd401dc823815a39fa5d2be29/fem/backward_euler_objective.h#L69)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I need to read more but on a quick inspection, `BackwardEulerObjective` seems to have the flavor of "a functor that NewtonSolver can talk to".

It seems like the "interface" to talk to NewtonSolver is with methods like 
</blockquote></details>

Looks like an unfinished thought here?
___
*[fem/backward_euler_objective.h, line 80 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MHMiGrw00OhcpNqP6uh:-MHRsJch-LV6n8t_teXX:b-bmnhyb) ([raw file](https://github.com/xuchenhan-tri/drake/blob/4d9bfd29617fbccbd401 [...]

2020-09-28 15:21 UTC, amcastro-tri requested changes
I resolved a number of old discussion because either we discussed f2f , because after the changes no longer apply, or simply because they are lower cost design topics that will get cleaned up during the actual PR into Drake.

I like where this is going. I'll finish with state today.

> Reviewed 1 of 28 files at r5, 3 of 26 files at r7.
> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-:-MIKHxup5MciZhC5iFSh:b-5hnfr8)* status: 4 of 73 files reviewed, 29 unresolved discussions (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[fem/backward_euler_objective.h, line 20 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MHMZSwj0t0A4CnsX0CD:-MIKD_0t25rQ5c5T2jCZ:b9mwap7) ([raw file](https://github.com/xuchenhan-tri/drake/blob/4d9bfd29617fbccbd401dc823815a39fa5d2be29/fem/backward_euler_objective.h#L20)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I find it helpful to be very explicit about what's the nonlinear equation we are solving for. Here I chose to formulate the set of nonlinear equations that we are solving for as `G(z) = 0`, where `z = dv`. 
</blockquote></details>

ok, in your answer you never used x, that's my point. Why not to write G(dv) then? so that you don't need a new symbol?
___
*[fem/backward_euler_objective.h, line 22 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MHMZjPkE_toyrYljFZ1:-MIKDjIF7pCTlOSpdR0O:b8qbqwd) ([raw file](https://github.com/xuchenhan-tri/drake/blob/4d9bfd29617fbccbd401dc823815a39fa5d2be29/fem/backward_euler_objective.h#L22)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I find it helpful to be very explicit about what's the nonlinear equation we are solving for.
</blockquote></details>

I agree. However my point is that it'd be easier to just use variable name dv instead of having an additional alias to it. That is, if you say that you are solving for dv, I believe that's equally explicit, without an alias for the same variable.
___
*[fem/backward_euler_objective.h, line 25 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MHMZqmjBov5pinNG6zy:-MIKE6Ry2BogcsSo4wDq:b-p17cy0) ([raw file](https://github.com/xuchenhan-tri/drake/blob/4d9bfd29617fbccbd401dc823815a39fa5d2be29/fem/backward_euler_objective.h#L25)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I forgot to remove all `x` as promised here. I'm changing all `x` here to `z`, the variable we are solving for in the newton iterations.
</blockquote></details>

ditto, not sure I see the reason for an alias to a variable that already does have a name, `dv`.
___
*[fem/backward_euler_objective.h, line 31 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MHM_F8cBkDdL1fO8acJ:-MIKETnb8dWyyQxg95NQ:bmh9xua) ([raw file](https://github.com/xuchenhan-tri/drake/blob/4d9bfd29617fbccbd401dc823815a39fa5d2be29/fem/backward_euler_objective.h#L31)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

No. I used a separate variable name to try to avoid mistakes like this. You could write it as `A*ddv = -G(v)`. Like I said in the previous threads, I find it helpful to be very explicit about what's the nonlinear equation we are solving for. In this case, we are solving for `G(z) = 0`, where `z = dv`.  So each iteration we are solving for `A*dz = -G(z)`, which translates to `A*ddv = -G(dv)`.
</blockquote></details>

ok, I agree about being explicit, but the problem here is that you actually did not accomplish that, that was my point. 
Question, what is the reason to say you are solving for `dv` (=z) instead of vⁿ⁺¹)? because if you say that you are solving for `v=vⁿ⁺¹`, then you can use the symbol dv for the Newton update, with no need for an extra alias.
___
*[fem/backward_euler_objective.h, line 40 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MHMbMI05QtREV01frm1:-MIKEtzF4ecWOUzIbKhM:bvej5au) ([raw file](https://github.com/xuchenhan-tri/drake/blob/4d9bfd29617fbccbd401dc823815a39fa5d2be29/fem/backward_euler_objective.h#L40)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This is an unfortunate clash of subscript `e`. I meant to denote "elastic force" with `fe`. Maybe moving the `e` to a superscript helps?
Re the d²F/dq² term, will do.
</blockquote></details>

I recommend reading the chapter in Bonet's book. Great notation there, we don't need to invent our own.
___
*[fem/backward_euler_objective.h, line 60 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MHMdI_L4GO2qwPzDzPp:-MIKF7pr1Yfmuzp8btui:bdecb6b) ([raw file](https://github.com/xuchenhan-tri/drake/blob/4d9bfd29617fbccbd401dc823815a39fa5d2be29/fem/backward_euler_objective.h#L60)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Again, I believe you are complaining about the misplaced comment (correct me if I misunderstood). Will move to FemForce.
</blockquote></details>

If I understand your desing correctly per our previous f2f, then yes, it has to do with moving the comments to where they belong.
As far as I understand this, BackwardEulerObjective does not now about FEM, but only about Mass matrix, `dRdv = ResidualGradientWithVelocities()` and `dRdq = ResidualGradientWithPositions()` per our previous f2f.
That is, the only assumption in `BackwardEulerObjective` is that we are solving for a system of the form: `R(v̇, q, v) = M⋅v̇+F(q,v)=0` and `FemModel` (FemForce here) provides the gradients with respect to v̇, q, v for BackwardEulerObjective.
___
*[fem/backward_euler_objective.h, line 80 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MHMiGrw00OhcpNqP6uh:-MIKGKtY3SNg2KtZpUn-:biuimdb) ([raw file](https://github.com/xuchenhan-tri/drake/blob/4d9bfd29617fbccbd401dc823815a39fa5d2be29/fem/backward_euler_objective.h#L80)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I made some changes and now `CalcResidual` takes `state`, PTAL.
</blockquote></details>

very nice!
___
*[fem/backward_euler_objective.h, line 68 at r7](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MIKGBSvCH16Zs_0OGpe:-MIKGBSvCH16Zs_0OGpf:bdhbfw7) ([raw file](https://github.com/xuchenhan-tri/drake/blob/28dcf1c9b49b4112fee74f1f18181a8cf746635a/fem/backward_euler_objective.h#L68)):*
> ```objc
>   DRAKE_NO_COPY_NO_MOVE_NO_ASSIGN(BackwardEulerObjective)
> 
>   BackwardEulerObjective(const FemData<T>& data,
> ```

why do we need to pass `FemData`? shouldn't data be part of `FemForce`? (or FemModel when we rename this)
___
*[fem/backward_euler_objective.h, line 88 at r7](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MIKGTdwCCDhSOLQ1HXC:-MIKGTdwCCDhSOLQ1HXD:bpgs4fw) ([raw file](https://github.com/xuchenhan-tri/drake/blob/28dcf1c9b49b4112fee74f1f18181a8cf746635a/fem/backward_euler_objective.h#L88)):*
> ```objc
> 
>   /** Returns 3 * number of vertices. */
>   int get_num_dofs() const { return fem_data_.get_Q().size(); }
> ```

nit, should probably read `fem_model_.num_veloticies()`.
___
*[fem/backward_euler_objective.h, line 90 at r7](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MIKGbVv7pFEJxDASMNY:-MIKGbVv7pFEJxDASMNZ:bhl2yu0) ([raw file](https://github.com/xuchenhan-tri/drake/blob/28dcf1c9b49b4112fee74f1f18181a8cf746635a/fem/backward_euler_objective.h#L90)):*
> ```objc
>   int get_num_dofs() const { return fem_data_.get_Q().size(); }
> 
>   const VectorX<T>& get_mass() const { return fem_data_.get_mass(); }
> ```

not sure why this is needed here.
___
*[fem/backward_euler_objective.h, line 104 at r7](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MIKGkMw8XdXTj3M5_hh:-MIKGkMw8XdXTj3M5_hi:b29lry4) ([raw file](https://github.com/xuchenhan-tri/drake/blob/28dcf1c9b49b4112fee74f1f18181a8cf746635a/fem/backward_euler_objective.h#L104)):*
> ```objc
> 
>  private:
>   const std::vector<Matrix3<T>>& EvalF() const;
> ```

why EvalF here?
___
*[fem/backward_euler_objective.h, line 106 at r7](https://reviewable.io/reviews/xuche [...]

2020-09-29 15:16 UTC, amcastro-tri requested changes
Ok, I finished my pass on state. I do like how it flows, in that you accomplished what we wanted, which is now we can call `CalcFoo(state, &foo)` and the data flow is clear.

Now, I have a question with HyperelasticCache, where for the corotated model the rotation matrix R (can we call it R0?)  seems to get recomputed every time q changes, instead of being a function of q0 only. PTAL my comments in fem_state/hydroelastic_cache files.

=== Another Subject: Notation and source symbols ==
I also added a number of comments that mostly have to do with either notation or the last discussion we had on isoparametric elements. Regarding notation, I'd like to get rid of Dm and Ds which is very Muller specific. 
Looking at Bonet's book (and having in mind that we prefer S to N given we use N already in Drake, though we can discuss if you don't like it), these are the things I'd like to clarify with notation (this also applies to Latex document): 

- Choose good notation for shape function. S(xi)? (it has the disadvantage that we use S for PK2, but may we just use PK2 and PK2 for those?)
- All books I've seen on FEM use lowercase roman characters for "local element indexes". That is, Sa(xi) would correspond to the a-th shape function for element e.
- Similarly, indexes i,j,m,n,k,p are used for "dimensions", either for derivatives or for vector components.
- I've only see Greek indexes when solving equations on manifolds, such as plates/membranes.
- We have gradients in the natural coordinates xi, current (or "spatial" as Bonet calls it) and reference configurations. We should stick to a good notation that locally communicates that. Per Bonet's (and Hughes also) I was thinking we can use dSdxi, dSdx and dSdX respectively (forget about Muller's specific Dm and Ds).
- All FEM books call dxdxi (or dXdxi) the "element's Jacobian", usually (bold) J. I think calling those dxdxi and dXdxi in code would suffice. For it's determinant, it is common to call that the jacobian also. Maybe in code we can call them "reference_jacobian" and "spatial_jacobian" respectively? 

Sorry I put those here, I just didn't want to forget. I also wanted to connect them with symbols in code. Leh me know what you think.

> Reviewed 2 of 28 files at r5, 1 of 26 files at r7.
> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-:-MIPNrULC-bJsKF7cfH4:bly3xur)* status: 7 of 73 files reviewed, 50 unresolved discussions (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[fem/backward_euler_objective.cc, line 13 at r7](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MIPBcAoEqCXsIvaK4W7:-MIPBcApBTVlF9OVo7r6:b-659kmv) ([raw file](https://github.com/xuchenhan-tri/drake/blob/28dcf1c9b49b4112fee74f1f18181a8cf746635a/fem/backward_euler_objective.cc#L13)):*
> ```cpp
>     const FemState<T>& state,
>     EigenPtr<VectorX<T>> residual) const {
>   Eigen::Map<Matrix3X<T>> impulse(residual->data(), 3, residual->size() / 3);
> ```

nit, at this scope, the arrangement into a Matrix3X ( which I agree is convenient) makes things specific to elasticity. For other problems (say scalar transport) most likely we'll like a flattened array.
Since Matrix3X might be convenient, what about doing that rearrangement at the `FemElement` level (the FemElement from our f2f) ? that'd leave all this code agnostic to the specific fem model.
___
*[fem/backward_euler_objective.cc, line 16 at r7](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MIPBD3F8JiBbPS7cuTm:-MIPBD3F8JiBbPS7cuTn:bvv9ens) ([raw file](https://github.com/xuchenhan-tri/drake/blob/28dcf1c9b49b4112fee74f1f18181a8cf746635a/fem/backward_euler_objective.cc#L16)):*
> ```cpp
>   impulse.setZero();
> 
>   const auto& dv = state.get_dv();
> ```

dv should not be in the state. After all, it is `v - v0`.
___
*[fem/backward_euler_objective.cc, line 24 at r7](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MIPBOmO2Vc9RwkDsiP6:-MIPBOmO2Vc9RwkDsiP7:b-gooxfj) ([raw file](https://github.com/xuchenhan-tri/drake/blob/28dcf1c9b49b4112fee74f1f18181a8cf746635a/fem/backward_euler_objective.cc#L24)):*
> ```cpp
>   for (int i = 0; i < mass.size(); ++i) {
>     impulse.col(i) -= mass(i) * dv.col(i);
>     impulse.col(i) += mass(i) * dt * gravity;
> ```

per f2f, this will look more like `fem_model_.MultiplyByMassMatrix(state, dv, &impulse)`.
___
*[fem/fem_force.h, line 88 at r7](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MIPCMDT2DLHIH6Ayiyt:-MIPCMDT2DLHIH6Ayiyu:bfh6z9j) ([raw file](https://github.com/xuchenhan-tri/drake/blob/28dcf1c9b49b4112fee74f1f18181a8cf746635a/fem/fem_force.h#L88)):*
> ```objc
>   /** Called by BackwardEulerObjective::CalcResidual. Calculates the elastic
>   forces, scale them by scale, and then add them to the force vector.  */
>   void AccumulateScaledElasticForce(const FemState<T>& state, T scale, EigenPtr<Matrix3X<T>> force) const;
> ```

nit, this comment is good to aid my review, but probably not what we'd like to push into master since the comment couples this class with BackwardEulerObjective. 
This class should know nothing about BackwardEulerObjective. The otherway around however is true; i.e. BackwardEulerObjective does know about this class.

This way of thinking will help us keep the distinction clean and avoid things like cyclic dependencies.

The comment should be more about what the method does, assumptions, math, formats, etc.
___
*[fem/fem_force.h, line 93 at r7](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MIPCpVu5lGLEi1a3cIA:-MIPCpVvA_4V145I6NXG:bnh56m4) ([raw file](https://github.com/xuchenhan-tri/drake/blob/28dcf1c9b49b4112fee74f1f18181a8cf746635a/fem/fem_force.h#L93)):*
> ```objc
>   forces, scale them by scale, and then add them to the force vector.  */
>   void AccumulateScaledDampingForce(const FemState<T>& state,T scale,
>                                     EigenPtr<Matrix3X<T>> force) const;
> ```

nit, if we commit her to this format with `Matrix3X`, then we won't be able to reuse this code to, for instance, solve for these "distance-like" functions or even more complex models (Imagine having an additional scalar transport equation for the modeling of crack propagation through the material).
___
*[fem/fem_force.cc, line 14 at r7](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MIPDgya2OIhm7Yu42fT:-MIPDgya2OIhm7Yu42fU:b-zfnlwv) ([raw file](https://github.com/xuchenhan-tri/drake/blob/28dcf1c9b49b4112fee74f1f18181a8cf746635a/fem/fem_force.cc#L14)):*
> ```cpp
>     T scale, EigenPtr<Matrix3X<T>> force) const {
>   // Gradient of the shape function is constant for linear interpolation.
>   Eigen::Matrix<T, 3, 4> grad_shape;
> ```

let's try to start using some common notation here. In a typical FEM code you'd have dSdxi and dSdx. In a large deformations code as the one you are writing in addition you have dSdX. 
In this case the one you are referring to is dSdxi. Could we use a stick to a notation so that within a local scope we know what the quantities are?
___
*[fem/fem_force.cc, line 16 at r7](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MIPE9_j95MU5lh1rijC:-MIPE9_j95MU5lh1rijD:bkpb6wg) ([raw file](https://github.com/xuchenhan-tri/drake/blob/28dcf1c9b49b4112fee74f1f18181a8cf746635a/fem/fem_force.cc#L16)):*
> ```cpp
>   Eigen::Matrix<T, 3, 4> grad_shape;
>   grad_shape.col(0) = -Vector3<T>::Ones();
>   grad_shape.template topRightCorner<3, 3>() = Matrix3<T>::Identity();
> ```

nit, only for discussion following up our last f2f.

Here you created a single dSdxi for ALL elements. That seems to suggest that probably FemModel owns the "distinct" IsoparametricShapeElement's that are needed and then their APIs passing xa (or Xa) can be used at each element to compute things like dSdx that depend on coordinates.

That is, it'd seem the lines above with our abstraction would simplify to:
```c+++
LinearTetrahedronInterpolant element_interpolation;   // The interpolant object's ctor would essentially do the math you have above.
```
___
*[fem/fem_force.cc, line 23 at r7](https://reviewable.i [...]

2020-09-29 18:07 UTC, xuchenhan-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/1)* status: 7 of 73 files reviewed, 49 unresolved discussions (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[fem/backward_euler_objective.h, line 20 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MHMZSwj0t0A4CnsX0CD:-MIPaiyv5Stsw9Di5lId:b-gjlkny) ([raw file](https://github.com/xuchenhan-tri/drake/blob/4d9bfd29617fbccbd401dc823815a39fa5d2be29/fem/backward_euler_objective.h#L20)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

ok, in your answer you never used x, that's my point. Why not to write G(dv) then? so that you don't need a new symbol?
</blockquote></details>

We have 4 threads for one issue. Closing this thread to consolidate. Please see the thread below.
___
*[fem/backward_euler_objective.h, line 22 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MHMZjPkE_toyrYljFZ1:-MIPb0lRBTs8KULkSsa7:b-gjlkny) ([raw file](https://github.com/xuchenhan-tri/drake/blob/4d9bfd29617fbccbd401dc823815a39fa5d2be29/fem/backward_euler_objective.h#L22)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I agree. However my point is that it'd be easier to just use variable name dv instead of having an additional alias to it. That is, if you say that you are solving for dv, I believe that's equally explicit, without an alias for the same variable.
</blockquote></details>

We have 4 threads for one issue. Closing this thread to consolidate. Please see the thread below.
___
*[fem/backward_euler_objective.h, line 25 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MHMZqmjBov5pinNG6zy:-MIPb3_w7TlFGRblr4lI:b-gjlkny) ([raw file](https://github.com/xuchenhan-tri/drake/blob/4d9bfd29617fbccbd401dc823815a39fa5d2be29/fem/backward_euler_objective.h#L25)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

ditto, not sure I see the reason for an alias to a variable that already does have a name, `dv`.
</blockquote></details>

We have 4 threads for one issue. Closing this thread to consolidate. Please see the thread below.
___
*[fem/backward_euler_objective.h, line 31 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MHM_F8cBkDdL1fO8acJ:-MIPbLJq3s84AHMbPfxg:b-gm5dz7) ([raw file](https://github.com/xuchenhan-tri/drake/blob/4d9bfd29617fbccbd401dc823815a39fa5d2be29/fem/backward_euler_objective.h#L31)):*
> ok, I agree about being explicit, but the problem here is that you actually did not accomplish that, that was my point.
Why do you think I "actually did not accomplish that"? The notation helped me avoid the mistake of writing down `A*dv = -G(v)`.

> Question, what is the reason to say you are solving for dv (=z) instead of vⁿ⁺¹)? because if you say that you are solving for v=vⁿ⁺¹, then you can use the symbol dv for the Newton update, with no need for an extra alias.
The reason I used `z` is because `dv` should not be used for the Newton update because `dv` also means `vⁿ⁺¹ - vⁿ` and I want to avoid using the same notation for two closely related but different quantities.
___
*[fem/backward_euler_objective.h, line 40 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MHMbMI05QtREV01frm1:-MIPcJI5BinzsYw3iGbl:bl7ebxh) ([raw file](https://github.com/xuchenhan-tri/drake/blob/4d9bfd29617fbccbd401dc823815a39fa5d2be29/fem/backward_euler_objective.h#L40)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I recommend reading the chapter in Bonet's book. Great notation there, we don't need to invent our own.
</blockquote></details>

Can you point me to the exact Chapter?
___
*[fem/backward_euler_objective.h, line 60 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MHMdI_L4GO2qwPzDzPp:-MIPd0pJ1NWOUTLSDaQy:b-bqk2og) ([raw file](https://github.com/xuchenhan-tri/drake/blob/4d9bfd29617fbccbd401dc823815a39fa5d2be29/fem/backward_euler_objective.h#L60)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

If I understand your desing correctly per our previous f2f, then yes, it has to do with moving the comments to where they belong.
As far as I understand this, BackwardEulerObjective does not now about FEM, but only about Mass matrix, `dRdv = ResidualGradientWithVelocities()` and `dRdq = ResidualGradientWithPositions()` per our previous f2f.
That is, the only assumption in `BackwardEulerObjective` is that we are solving for a system of the form: `R(v̇, q, v) = M⋅v̇+F(q,v)=0` and `FemModel` (FemForce here) provides the gradients with respect to v̇, q, v for BackwardEulerObjective.
</blockquote></details>

Will do.
___
*[fem/backward_euler_objective.h, line 68 at r7](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MIKGBSvCH16Zs_0OGpe:-MIPdOOLEkkOnzNdbQut:b-6lfo5d) ([raw file](https://github.com/xuchenhan-tri/drake/blob/28dcf1c9b49b4112fee74f1f18181a8cf746635a/fem/backward_euler_objective.h#L68)):*
> why do we need to pass FemData? 
I used to assemble the mass matrix in BackwardEulerObjective. It's bad, but that should answer your question of why FemData is here.

>shouldn't data be part of FemForce? (or FemModel when we rename this)
Yes, will do.
___
*[fem/backward_euler_objective.h, line 88 at r7](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MIKGTdwCCDhSOLQ1HXC:-MIPdj3PES2q1fJf-rcH:bz4w1b0) ([raw file](https://github.com/xuchenhan-tri/drake/blob/28dcf1c9b49b4112fee74f1f18181a8cf746635a/fem/backward_euler_objective.h#L88)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, should probably read `fem_model_.num_veloticies()`.
</blockquote></details>

I'm worried that `num_velocities()` would be interpreted as equal to the number of vertices instead of number of vertices * number of spatial dimensions.
___
*[fem/backward_euler_objective.h, line 90 at r7](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MIKGbVv7pFEJxDASMNY:-MIPe51UDzbQBqQmAZu-:b-x2m8lj) ([raw file](https://github.com/xuchenhan-tri/drake/blob/28dcf1c9b49b4112fee74f1f18181a8cf746635a/fem/backward_euler_objective.h#L90)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

not sure why this is needed here.
</blockquote></details>

See the comment about mass matrix above.
___
*[fem/backward_euler_objective.h, line 104 at r7](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MIKGkMw8XdXTj3M5_hh:-MIPeDkO2Zkchm4WFCxC:b-7g6hif) ([raw file](https://github.com/xuchenhan-tri/drake/blob/28dcf1c9b49b4112fee74f1f18181a8cf746635a/fem/backward_euler_objective.h#L104)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

why EvalF here?
</blockquote></details>

Oversight in the refactor, will delete.
___
*[fem/backward_euler_objective.h, line 106 at r7](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MIKGo825jEzn0AKXqsO:-MIPeKH06kAuPMeR97sM:b-7g6hif) ([raw file](https://github.com/xuchenhan-tri/drake/blob/28dcf1c9b49b4112fee74f1f18181a8cf746635a/fem/backward_euler_objective.h#L106)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

why this EvalHyperElasticCache here? As far as I understand this, the idea was that BackwardEulerObjective does not even know what FemModel is talking to?
</blockquote></details>

Oversight in the refactor, will delete.
___
*[fem/backward_euler_objective.h, line 112 at r7](https://reviewable.io/reviews/xuchenhan-tri/drake/1#-MIKH0mb5D7PD_dJXtK9:-MIPeS_D4a9e2rHwnEPb:bye6hsi) ([raw file](https://github.com/xuchenhan-tri/drake/blob/28dcf1c9b49b4112fee74f1f18181a8cf746635a/fem/backward_euler_objective.h#L112)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I believe `Project()` does not belong here but `FemModel` will compute residual and gradients with the proper BCs?
Per f2 [...]

2022-02-09 06:25 UTC, closed without merging