[WIP] Experiment with using system cache for FEM element data
xuchenhan-tri/drake pull request #10
Opened 2022-02-09 02:05 UTC by xuchenhan-tri

2022-02-09 02:26 UTC, xuchenhan-tri reviewed
+@amcastro-tri for design review.

> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-:-MvRIJ3U-x7GZNKkmJ8P:b-xmychh)* status: 0 of 13 files reviewed, all discussions resolved (waiting on @amcastro-tri)



<!-- Sent from Reviewable.io -->

2022-02-09 17:06 UTC, sherm1 reviewed
> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/10)* status: 0 of 13 files reviewed, 4 unresolved discussions (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[multibody/fem/element_data_impl.h, line 24 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-MvUQZkrAfKyF-l90EEs:-MvUQZkrAfKyF-l90EEt:b-795gce) ([raw file](https://github.com/xuchenhan-tri/drake/blob/005bae2fd02193b322886f2e36fa7ea516b72e33/multibody/fem/element_data_impl.h#L24)):*
> ```objc
>   DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN(ElementDataImpl);
> 
>   ElementData(int num_elements) : element_data_(num_elements) {}
> ```

ElementDataImpl()
___
*[multibody/fem/fem_data_manager.h, line 34 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-MvUOtc55XJDDH7GDkn6:-MvUOtc68Q9m0XQQsjXS:b5s26kj) ([raw file](https://github.com/xuchenhan-tri/drake/blob/005bae2fd02193b322886f2e36fa7ea516b72e33/multibody/fem/fem_data_manager.h#L34)):*
> ```objc
>   }
> 
>   const FemState<T>& EvalFemState() const {
> ```

nit: should be `GetFemState()` since there is no evaluation performed.
___
*[multibody/fem/fem_data_manager.h, line 47 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-MvUPJNz-NoBQkvSHIex:-MvUPJNz-NoBQkvSHIey:b-p8c2ji) ([raw file](https://github.com/xuchenhan-tri/drake/blob/005bae2fd02193b322886f2e36fa7ea516b72e33/multibody/fem/fem_data_manager.h#L47)):*
> ```objc
>   void AllocateFemData() {
>     fem_state_index_ = system_.DeclareAbstractState(
>         Value<FemState<T>>(fem_model_->MakeFemState()));
> ```

BTW does this have to be abstract state? If it is entirely floating point numbers it could be simpler discrete state. If it is a mix of indexes, counts, etc and fp numbers then abstract is right.
___
*[multibody/fem/fem_data_manager.h, line 69 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-MvUQ9nB87S8dWDqblPS:-MvUQ9nB87S8dWDqblPT:btxxzz) ([raw file](https://github.com/xuchenhan-tri/drake/blob/005bae2fd02193b322886f2e36fa7ea516b72e33/multibody/fem/fem_data_manager.h#L69)):*
> ```objc
>   // TODO(xuchenhan-tri): These quantities need not be per FemDataManager.
>   //  It's enough to have one system per FemModel.
>   systems::LeafSystem<T> system_;
> ```

BTW is this known to be a MultibodyPlant System? If so could be more explicit and call this `multibody_plant_`.
___
*[multibody/fem/fem_model.h, line 108 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-MvURJsoAwNi5nqFvnBp:-MvURJsoAwNi5nqFvnBq:b-86yu0o) ([raw file](https://github.com/xuchenhan-tri/drake/blob/005bae2fd02193b322886f2e36fa7ea516b72e33/multibody/fem/fem_model.h#L108)):*
> ```objc
>    model. */
>   void CalcTangentMatrix(const FemState<T>& state, const Vector3<T>& weights,
>                          Eigen::SparseMatrix<T>* tangent_matrix) const;
> ```

BTW should the tangent matrix be cached?


<!-- Sent from Reviewable.io -->

2022-02-09 17:53 UTC, xuchenhan-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/10)* status: 0 of 13 files reviewed, 4 unresolved discussions (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[multibody/fem/element_data_impl.h, line 24 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-MvUQZkrAfKyF-l90EEs:-MvUb_7v7jZTKG9IMufR:b-a9q4c4) ([raw file](https://github.com/xuchenhan-tri/drake/blob/005bae2fd02193b322886f2e36fa7ea516b72e33/multibody/fem/element_data_impl.h#L24)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

ElementDataImpl()
</blockquote></details>

working
___
*[multibody/fem/fem_data_manager.h, line 34 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-MvUOtc55XJDDH7GDkn6:-MvUbZ2JBjVhb0ukvyhD:b-a9q4c4) ([raw file](https://github.com/xuchenhan-tri/drake/blob/005bae2fd02193b322886f2e36fa7ea516b72e33/multibody/fem/fem_data_manager.h#L34)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: should be `GetFemState()` since there is no evaluation performed.
</blockquote></details>

working
___
*[multibody/fem/fem_data_manager.h, line 47 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-MvUPJNz-NoBQkvSHIex:-MvUbY-m9BmTyn3GGkT1:b-a9q4c4) ([raw file](https://github.com/xuchenhan-tri/drake/blob/005bae2fd02193b322886f2e36fa7ea516b72e33/multibody/fem/fem_data_manager.h#L47)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW does this have to be abstract state? If it is entirely floating point numbers it could be simpler discrete state. If it is a mix of indexes, counts, etc and fp numbers then abstract is right.
</blockquote></details>

working
___
*[multibody/fem/fem_data_manager.h, line 69 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-MvUQ9nB87S8dWDqblPS:-MvUbGrs4RXCCHifPazP:b-mbtdqd) ([raw file](https://github.com/xuchenhan-tri/drake/blob/005bae2fd02193b322886f2e36fa7ea516b72e33/multibody/fem/fem_data_manager.h#L69)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW is this known to be a MultibodyPlant System? If so could be more explicit and call this `multibody_plant_`.
</blockquote></details>

In fact this is a standalone system that only handles the state and data from a particular FEM model. 


<!-- Sent from Reviewable.io -->

2022-02-12 02:37 UTC, xuchenhan-tri reviewed
I finally more or less got this into a shape that I don't hate. I plumbed through all the FEM classes (modulo some dummy class used for testing) to verify it still works nicely with the FEM APIs. 

But as discussed in the slack thread [here](https://drakedevelopers.slack.com/archives/C2CHRT98E/p1644629569410789?thread_ts=1644621112.226229&cid=C2CHRT98E), there needs to be some manual cache management, so I'm not convinced that this is better than the original bespoke caching mechanism.

I'd like to solicit some feedback again. Perhaps we can discuss in Softsim on Monday as a group? Thanks again for your help! 

> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-:-MvflTjc29LH_5BoiJi-:bclw16z)* status: 0 of 32 files reviewed, 3 unresolved discussions (waiting on @amcastro-tri and @xuchenhan-tri)



<!-- Sent from Reviewable.io -->

2022-02-12 02:41 UTC, xuchen-han reviewed
> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/10)* status: 0 of 32 files reviewed, 2 unresolved discussions (waiting on @amcastro-tri, @sherm1, and @xuchenhan-tri)

___
*[multibody/fem/fem_data_manager.h, line 47 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-MvUPJNz-NoBQkvSHIex:-MvfnPAT0mYhvj8_vo6u:baojw85) ([raw file](https://github.com/xuchenhan-tri/drake/blob/005bae2fd02193b322886f2e36fa7ea516b72e33/multibody/fem/fem_data_manager.h#L47)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

working
</blockquote></details>

The scratch state is a cache entry now, which I think we agree is the right abstraction.
___
*[multibody/fem/fem_model.h, line 108 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-MvURJsoAwNi5nqFvnBp:-MvfmxGuBD6UBxFFoqr3:b-xkluxy) ([raw file](https://github.com/xuchenhan-tri/drake/blob/005bae2fd02193b322886f2e36fa7ea516b72e33/multibody/fem/fem_model.h#L108)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW should the tangent matrix be cached?
</blockquote></details>

Not quite. The tangent matrix is different for different time stepping schemes. It's perceivable that we can include the integration scheme in the context as well, but I'd like to get into that rabbit hole later.


<!-- Sent from Reviewable.io -->

2022-02-15 00:59 UTC, sherm1 requested changes
This is looking much better! There are still a few things to clear up -- please see my comments. Once we get all the pieces in place I will provide some CacheEntry sugar so you don't have to do the magic incantations here, but that won't change the overall structure.

> Reviewed 2 of 27 files at r3.
> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-:-MvuskUK-T7-zp6_ELNm:bwt7db4)* status: 2 of 32 files reviewed, 12 unresolved discussions (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[multibody/fem/element_data.h, line 16 at r3](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-MvudnnNAISveXUHAnXy:-MvudnnNAISveXUHAnXz:b-ninl5) ([raw file](https://github.com/xuchenhan-tri/drake/blob/a6784973836dc1f16113825917d148b93098a862/multibody/fem/element_data.h#L16)):*
> ```objc
> class ElementData {
>  public:
>   DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN(ElementData);
> ```

Likely you want to suppress these to avoid slicing. Anyone who wants a proper duplicate can call the Clone() method.
___
*[multibody/fem/fem_data_manager.h, line 82 at r3](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-MvugWR21wtvE3vQDGUJ:-MvugWR21wtvE3vQDGUK:blkiomz) ([raw file](https://github.com/xuchenhan-tri/drake/blob/a6784973836dc1f16113825917d148b93098a862/multibody/fem/fem_data_manager.h#L82)):*
> ```objc
>     // TODO(xuchenhan-tri): Per slack discussion, GetKnownUpToDate() should be
>     // preferred here. But I don't see how that's correct when the element data
>     // is out of date?
> ```

Right, you should mark it up to date when the value has been updated. Using Eval() implies that there exists a Calc() method that can bring the entry up to date; that's not true here. (Actually all that happens is the NoOp gets executed followed by the "up to date" flag getting set -- you should instead do that when you really do make the value up to date.) CacheEntryValue::mark_up_to_date() can do that.
___
*[multibody/fem/fem_data_manager.h, line 122 at r3](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-MvuhSOj54NS2agj-Q-L:-MvuhSOj54NS2agj-Q-M:bpl06pw) ([raw file](https://github.com/xuchenhan-tri/drake/blob/a6784973836dc1f16113825917d148b93098a862/multibody/fem/fem_data_manager.h#L122)):*
> ```objc
>   int num_dofs_{0};
>   systems::CacheIndex scratch_state_index_;
>   systems::CacheIndex element_data_index_;
> ```

Shouldn't this just be a FemDataInfo member, plus a Context member?
___
*[multibody/fem/fem_model.h, line 81 at r3](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-MvuonGf-dkAolUx0uYO:-MvuonGf-dkAolUx0uYP:bv3uk2i) ([raw file](https://github.com/xuchenhan-tri/drake/blob/a6784973836dc1f16113825917d148b93098a862/multibody/fem/fem_model.h#L81)):*
> ```objc
>     const auto& scratch_state_cache_entry = system->DeclareCacheEntry(
>         "FEM scratch state",
>         systems::ValueProducer(model_state, &systems::ValueProducer::NoopCalc),
> ```

This should not be using NoopCalc(). Instead it should use a dummy calc method that unconditionally throws -- no one should ever call it because you calculate it with your own bespoke code.

Also, this is not what we would call a "scratch" space in the sense of #15943. A scratch entry should never be marked up to date and no one should declare downstream dependencies on it. This is instead the initial piece of an important multi-phase computation and in fact ends up being the final solution. I would call it something like `next_state_cache_entry`. 

As I mentioned before, an ideal implementation would simply swap `next_state_cache_entry` for the actual `state` once we're done with it to avoid the final copy. Nothing scratch about it in that case!
___
*[multibody/fem/fem_model.h, line 92 at r3](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-MvuiIyW3hfq0r2iRIM1:-MvuiIyW3hfq0r2iRIM2:b-ppqb78) ([raw file](https://github.com/xuchenhan-tri/drake/blob/a6784973836dc1f16113825917d148b93098a862/multibody/fem/fem_model.h#L92)):*
> ```objc
>         systems::ValueProducer(
>             *model_element_data,
>             std::function<void(const systems::Context<T>&, ElementData<T>*)>{
> ```

Is this std::function cast necessary? I would have expected the lambda alone to satisfy the ValueProducer signature.
___
*[multibody/fem/fem_model.h, line 98 at r3](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-MvuiZGhCkmVri50JqvW:-MvuiZGhCkmVri50JqvX:b-w5544h) ([raw file](https://github.com/xuchenhan-tri/drake/blob/a6784973836dc1f16113825917d148b93098a862/multibody/fem/fem_model.h#L98)):*
> ```objc
>                   const FemState<T>& fem_state =
>                       system->get_cache_entry(scratch_state_index)
>                           .template Eval<FemState<T>>(context);
> ```

This should be GetKnownUpToDate()
___
*[multibody/fem/fem_model.h, line 107 at r3](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-Mvuiyv-76etKmX-hhJL:-Mvuiyv-76etKmX-hhJM:bslhki2) ([raw file](https://github.com/xuchenhan-tri/drake/blob/a6784973836dc1f16113825917d148b93098a862/multibody/fem/fem_model.h#L107)):*
> ```objc
> 
>   // TODO(xuchenhan-tri): This needs to take an additional argument for
>   // ElementData, or takes FemDataManager instead.
> ```

BTW TODO not needed now? (Several more below)
___
*[multibody/fem/fem_model.h, line 121 at r3](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-MvujB0h8ks4l-MC-1yq:-MvujB0h8ks4l-MC-1yr:b-vdmy9d) ([raw file](https://github.com/xuchenhan-tri/drake/blob/a6784973836dc1f16113825917d148b93098a862/multibody/fem/fem_model.h#L121)):*
> ```objc
>    is given by a weight sum of stiffness matrix, damping matrix, and mass
>    matrix.
>    @param[in] state            The FemDataManager at which the tangent matrix is
> ```

nit state -> fem_data
___
*[multibody/fem/fem_model.h, line 140 at r3](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-MvujPCn0yICcVY0TQJC:-MvujPCn0yICcVY0TQJD:bruetsx) ([raw file](https://github.com/xuchenhan-tri/drake/blob/a6784973836dc1f16113825917d148b93098a862/multibody/fem/fem_model.h#L140)):*
> ```objc
>   /* Alternative signature for calculating tangent matrix that writes to a
>    PETSc matrix.
>    @param[in] state            The FemDataManager at which the tangent matrix is
> ```

nit: state -> fem_data
___
*[multibody/fem/fem_solver.cc, line 55 at r3](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-MvuoRRP2oSBILgCsjF4:-MvuoRRQ3KfgtrRznwi1:b-36ym5h) ([raw file](https://github.com/xuchenhan-tri/drake/blob/a6784973836dc1f16113825917d148b93098a862/multibody/fem/fem_solver.cc#L55)):*
> ```cpp
> 
> template <typename T>
> int FemSolver<T>::SolveWithInitialGuess(FemDataManager<T>* state) const {
> ```

nit: would be easier to read the code here with state -> fem_data
___
*[multibody/fem/fem_solver.cc, line 58 at r3](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-MvulowD07VL9GmqcEXk:-MvulowD07VL9GmqcEXl:bwicsd6) ([raw file](https://github.com/xuchenhan-tri/drake/blob/a6784973836dc1f16113825917d148b93098a862/multibody/fem/fem_solver.cc#L58)):*
> ```cpp
>   /* Make sure the scratch quantities are of the correct sizes. */
>   ResetScratchDataIfNecessary();
>   model_->ApplyBoundaryCondition(&state->GetMutableFemState());
> ```

Needs a comment here. What I think this should do:
- GetMutableFemState() marks the mutable state cache entry out of date and invalidates all downstream dependents.
- Then ApplyBoundaryCondition() sets the mutable state to our first guess.
- Missing: now mark the cache entry "up to date" so downstream computations can be done safely.
___
*[multibody/fem/fem_solver.cc, line 90 at r3](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-Mvuo-Hn1Oo0dp1BNJZa:-Mvuo-Hn1Oo0dp1BNJZb:bgfmlsk) ([raw file](https://github.com/xuchenhan-tri/drake/blob/a6784973836dc1f16113825917d148b93098a862/multibody/fem/fem_solver.cc#L90)):*
> ```cpp
>       dz_ = eigen_tangent_matrix_solver_.solve(-b_);
>     }
>     integrator_->UpdateStateFromChangeInUnknowns(dz_,
> ```

Comment here should read:
- GetMutableFemState() marks out [...]

2022-02-15 01:46 UTC, sherm1 reviewed
> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/10)* status: 2 of 32 files reviewed, 12 unresolved discussions (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[multibody/fem/fem_model.h, line 81 at r3](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-MvuonGf-dkAolUx0uYO:-Mvv1r535cRQ27xDYbUl:bg00n75) ([raw file](https://github.com/xuchenhan-tri/drake/blob/a6784973836dc1f16113825917d148b93098a862/multibody/fem/fem_model.h#L81)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

This should not be using NoopCalc(). Instead it should use a dummy calc method that unconditionally throws -- no one should ever call it because you calculate it with your own bespoke code.

Also, this is not what we would call a "scratch" space in the sense of #15943. A scratch entry should never be marked up to date and no one should declare downstream dependencies on it. This is instead the initial piece of an important multi-phase computation and in fact ends up being the final solution. I would call it something like `next_state_cache_entry`. 

As I mentioned before, an ideal implementation would simply swap `next_state_cache_entry` for the actual `state` once we're done with it to avoid the final copy. Nothing scratch about it in that case!
</blockquote></details>

BTW currently `next_state_cache_entry` is marked as having no prerequisites. But consider whether it actually should have a dependency on the current state. It doesn't seem like next_state should ever be valid if current_state has just changed. That might not have a practical implication here but it might express the real dependencies here more accurately and could possibly catch some (future) bugs.


<!-- Sent from Reviewable.io -->

2022-02-15 02:25 UTC, xuchenhan-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/10)* status: 1 of 32 files reviewed, 9 unresolved discussions (waiting on @amcastro-tri, @sherm1, and @xuchenhan-tri)

___
*[multibody/fem/element_data.h, line 16 at r3](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-MvudnnNAISveXUHAnXy:-Mvv0pd02uB30X0P9lmd:bneqig0) ([raw file](https://github.com/xuchenhan-tri/drake/blob/a6784973836dc1f16113825917d148b93098a862/multibody/fem/element_data.h#L16)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Likely you want to suppress these to avoid slicing. Anyone who wants a proper duplicate can call the Clone() method.
</blockquote></details>

Done. Moved it to protected so that derived class can invoke the copy constructor.
___
*[multibody/fem/fem_data_manager.h, line 82 at r3](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-MvugWR21wtvE3vQDGUJ:-Mvv16es7C-iw5Aw6D8A:bn616r2) ([raw file](https://github.com/xuchenhan-tri/drake/blob/a6784973836dc1f16113825917d148b93098a862/multibody/fem/fem_data_manager.h#L82)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Right, you should mark it up to date when the value has been updated. Using Eval() implies that there exists a Calc() method that can bring the entry up to date; that's not true here. (Actually all that happens is the NoOp gets executed followed by the "up to date" flag getting set -- you should instead do that when you really do make the value up to date.) CacheEntryValue::mark_up_to_date() can do that.
</blockquote></details>

I think you are referring to `FemState` instead of `ElementData`, right? `ElementData` does have a Calc() method that brings the entry up to date, and it depends on FemState.

I changed the implementation of GetFemState() to use GetKnownUpToDate(). Now it doesn't thrash the cache every time it's invoked.
___
*[multibody/fem/fem_data_manager.h, line 122 at r3](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-MvuhSOj54NS2agj-Q-L:-MvuwVUuA1OkoBZ-fhwi:b-f0qo0c) ([raw file](https://github.com/xuchenhan-tri/drake/blob/a6784973836dc1f16113825917d148b93098a862/multibody/fem/fem_data_manager.h#L122)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Shouldn't this just be a FemDataInfo member, plus a Context member?
</blockquote></details>

Yeah, this was a half-ass refactor as I shove the indexes into FemDataInfo. 
Done.
___
*[multibody/fem/fem_model.h, line 81 at r3](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-MvuonGf-dkAolUx0uYO:-Mvv8vqPEFGa6fnQsJ01:bwudxt) ([raw file](https://github.com/xuchenhan-tri/drake/blob/a6784973836dc1f16113825917d148b93098a862/multibody/fem/fem_model.h#L81)):*
> This should not be using NoopCalc(). Instead it should use a dummy calc method that unconditionally throws -- no one should ever call it because you calculate it with your own bespoke code.

Done.

Re naming: I agree this is not the scratch in the sense of #15943, but I'm hesitant to call this `next_state_cache_entry` for the reason I describe below.

Re having the cache entry depend on current state: I think this might be doable, but it's a non-goal for `FemDataManager`. I design `FemDataManager` for one purpose and one purpose only: to replace the bespoke caching in what used be be `FemState`. The goal is to keep the API's we like about FEM the same as much as possible. In particular, we have the freedom to create a FEM state, move it to where-ever we want, and ask FEM model to provide information at that state (e.g. residual, tangent matrix etc). That's the core functionality of FEM and it provides us with lots of flexibility. If we think of the cached state as the "next time step's state", then we can't avoid bringing a time stepping scheme and a solver into the picture. That, IMO, makes the code structure less modular.
___
*[multibody/fem/fem_model.h, line 92 at r3](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-MvuiIyW3hfq0r2iRIM1:-Mvv4imACBtN3b0T7FwK:b7y7ufj) ([raw file](https://github.com/xuchenhan-tri/drake/blob/a6784973836dc1f16113825917d148b93098a862/multibody/fem/fem_model.h#L92)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Is this std::function cast necessary? I would have expected the lambda alone to satisfy the ValueProducer signature.
</blockquote></details>

It seems to be necessary. This is constructor 3b of ValueProducer.
___
*[multibody/fem/fem_model.h, line 98 at r3](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-MvuiZGhCkmVri50JqvW:-Mvv7n1b4u2K8p-rree6:b-896fix) ([raw file](https://github.com/xuchenhan-tri/drake/blob/a6784973836dc1f16113825917d148b93098a862/multibody/fem/fem_model.h#L98)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

This should be GetKnownUpToDate()
</blockquote></details>

Done.
___
*[multibody/fem/fem_model.h, line 107 at r3](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-Mvuiyv-76etKmX-hhJL:-Mvv592oBE5dWRT5eNdT:b6vh1xi) ([raw file](https://github.com/xuchenhan-tri/drake/blob/a6784973836dc1f16113825917d148b93098a862/multibody/fem/fem_model.h#L107)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW TODO not needed now? (Several more below)
</blockquote></details>

Done (removed). There are quite a few places I need to modify the comment/documentation to reflect the changes we are making here. I'll make a more careful pass once we decide we like the design and settle on naming of the new class.
___
*[multibody/fem/fem_model.h, line 121 at r3](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-MvujB0h8ks4l-MC-1yq:-Mvv5blgBjnD2pSSDLV9:b8e58qq) ([raw file](https://github.com/xuchenhan-tri/drake/blob/a6784973836dc1f16113825917d148b93098a862/multibody/fem/fem_model.h#L121)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit state -> fem_data
</blockquote></details>

working. I'll go through these changes once we settle on a name for what's currently `FemDataManager`. 
___
*[multibody/fem/fem_model.h, line 140 at r3](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-MvujPCn0yICcVY0TQJC:-Mvv5jco9FeGIm0zrzEo:b-a9q4c4) ([raw file](https://github.com/xuchenhan-tri/drake/blob/a6784973836dc1f16113825917d148b93098a862/multibody/fem/fem_model.h#L140)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: state -> fem_data
</blockquote></details>

working
___
*[multibody/fem/fem_solver.cc, line 55 at r3](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-MvuoRRP2oSBILgCsjF4:-Mvv62oDAoEqLMcn_f5Z:b-a9q4c4) ([raw file](https://github.com/xuchenhan-tri/drake/blob/a6784973836dc1f16113825917d148b93098a862/multibody/fem/fem_solver.cc#L55)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: would be easier to read the code here with state -> fem_data
</blockquote></details>

working
___
*[multibody/fem/fem_solver.cc, line 58 at r3](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-MvulowD07VL9GmqcEXk:-Mvv6SeV1qzuUejT2yyp:bu1quhl) ([raw file](https://github.com/xuchenhan-tri/drake/blob/a6784973836dc1f16113825917d148b93098a862/multibody/fem/fem_solver.cc#L58)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Needs a comment here. What I think this should do:
- GetMutableFemState() marks the mutable state cache entry out of date and invalidates all downstream dependents.
- Then ApplyBoundaryCondition() sets the mutable state to our first guess.
- Missing: now mark the cache entry "up to date" so downstream computations can be done safely.

</blockquote></details>

Done for the first two bullet points.
Re the 3rd point: should we  have the user of `FemDataManager` manually mark the state cache up to date? It seems to be inviting trouble. I'd rather have it don [...]

2022-02-15 16:38 UTC, amcastro-tri requested changes
I added my very high level comments at the call site. I am not sure I can dive deep into the implementation without first nailing down what we want the call sites to look like. 
As far as I understand it, the purpose of this prototype is to make effective use of the `systems::` caching while still being able to design the APIs that we believe are useful to users of FemModel (highly trained users/developers) and useful to FEM developers. This not only includes simulation (right now through MBP+DiscreteUpdateManager) but also examples for instance for control (at some point someone is going to want to perform an "inverse dynamics" computation or QP control of a soft robot)

> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-:-MvyCsn_0tjM1eHk9NhD:b-3ai9cl)* status: 1 of 32 files reviewed, 11 unresolved discussions (waiting on @amcastro-tri, @sherm1, and @xuchenhan-tri)

___
*[multibody/fem/test/volumetric_model_test.cc, line 131 at r4](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-Mvy8K_63szpRRTjWnOq:-Mvy8K_63szpRRTjWnOr:bojcc3l) ([raw file](https://github.com/xuchenhan-tri/drake/blob/a99900a384631eb2c8d6cf30d68298f1401a24ab/multibody/fem/test/volumetric_model_test.cc#L131)):*
> ```cpp
>       double_context_ = double_system_.CreateDefaultContext();
>       auto fem_data = std::make_unique<FemDataManager<double>>(
>           fem_data_info, double_context_.get());
> ```

I don't find this calling site very satisfactory. The reason is that this forces the user of a `FemModel` to own a system and make sure that system outlives the FemModel instance. I find that clunky. Say I want to write a controller, not even withing the `systems::` framework (very much like lots of Anzu code), that'd force us to bring in a system just to be able to use the math offered by the model. 
I think this is what I would like to see at the call sites, and then of course if we agree, we can then try to figure out what the software should be to satisfy this requirement:
```c++
// Someone creates/owns a model (for simulation, say MultibodyPlant, or to be more specific, a DiscreteUpdateManager)
std::unique_ptr<FemModel> model = MakeVolumentricFemModel();


// Say I am within the scope of a discrete update method where a const context storing the current state is available.
void DoCalcDiscreteVariableUpdates(const Context& context, DiscreteValues* updates) {

// Now the model needs a place where to store the state and cache entries. 
// I'll reuse here Xuchen's proposed name of FemData, though others such as FemWorkspace or similar might work. 
// CrateFemData will declare cache entries with values to be stored (somehow) in FemData and calc methods (somehow) provided by FemModel.
std::unique_ptr<FemData> data = model->CreateFemData();

// Now, our client (say MultibodyPlant), has state declared for this model. Say that state was declared as a discrete state group.
const VectorX<T> fem_positions = context0.get_discrete_state(fem_gropu).get_value();

// Recall here FemData stores the state, so we do that. Also, we want cache invalidation to happen here. 
data->SetPositions(fem_positions); 

// Now that we copied (cheap, even for large states) the fem state from the MultibodyPlant's context into data, we can evaluate FEM computations performed by the model.
const VectorX& residual = model->EvalResidual(*data);

}

```


For something like a controller, say outside of the system framework, notice that the API above does not require to either have a system nor a context floating around. As a user, I'd find that very pleasant.


Thoughts @xuchenhan-tri, @sherm1, @jwnimmer-tri ?
___
*[multibody/fem/test/volumetric_model_test.cc, line 138 at r4](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-MvyCgCp-XMm1BFSEJPz:-MvyCgCp-XMm1BFSEJQ-:bho6n9t) ([raw file](https://github.com/xuchenhan-tri/drake/blob/a99900a384631eb2c8d6cf30d68298f1401a24ab/multibody/fem/test/volumetric_model_test.cc#L138)):*
> ```cpp
>                                                                 kBeta);
>       double_integrator.AdvanceOneTimeStep(fem_data->GetFemState(), perturbed_a,
>                                            &fem_data->GetMutableFemState());
> ```

with the API I propose above, doing `data->GetMutableFemState()` still is allowed since we do have a mutable FemData around. 


<!-- Sent from Reviewable.io -->

2022-02-15 19:29 UTC, xuchen-han reviewed
> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/10)* status: 1 of 32 files reviewed, 11 unresolved discussions (waiting on @amcastro-tri, @jwnimmer-tri, @sherm1, and @xuchenhan-tri)

___
*[multibody/fem/test/volumetric_model_test.cc, line 131 at r4](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-Mvy8K_63szpRRTjWnOq:-Mvyp-AJCik_Q-XH3yxI:bl0nq59) ([raw file](https://github.com/xuchenhan-tri/drake/blob/a99900a384631eb2c8d6cf30d68298f1401a24ab/multibody/fem/test/volumetric_model_test.cc#L131)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I don't find this calling site very satisfactory. The reason is that this forces the user of a `FemModel` to own a system and make sure that system outlives the FemModel instance. I find that clunky. Say I want to write a controller, not even withing the `systems::` framework (very much like lots of Anzu code), that'd force us to bring in a system just to be able to use the math offered by the model. 
I think this is what I would like to see at the call sites, and then of course if we agree, we can then try to figure out what the software should be to satisfy this requirement:
```c++
// Someone creates/owns a model (for simulation, say MultibodyPlant, or to be more specific, a DiscreteUpdateManager)
std::unique_ptr<FemModel> model = MakeVolumentricFemModel();


// Say I am within the scope of a discrete update method where a const context storing the current state is available.
void DoCalcDiscreteVariableUpdates(const Context& context, DiscreteValues* updates) {

// Now the model needs a place where to store the state and cache entries. 
// I'll reuse here Xuchen's proposed name of FemData, though others such as FemWorkspace or similar might work. 
// CrateFemData will declare cache entries with values to be stored (somehow) in FemData and calc methods (somehow) provided by FemModel.
std::unique_ptr<FemData> data = model->CreateFemData();

// Now, our client (say MultibodyPlant), has state declared for this model. Say that state was declared as a discrete state group.
const VectorX<T> fem_positions = context0.get_discrete_state(fem_gropu).get_value();

// Recall here FemData stores the state, so we do that. Also, we want cache invalidation to happen here. 
data->SetPositions(fem_positions); 

// Now that we copied (cheap, even for large states) the fem state from the MultibodyPlant's context into data, we can evaluate FEM computations performed by the model.
const VectorX& residual = model->EvalResidual(*data);

}

```


For something like a controller, say outside of the system framework, notice that the API above does not require to either have a system nor a context floating around. As a user, I'd find that very pleasant.


Thoughts @xuchenhan-tri, @sherm1, @jwnimmer-tri ?
</blockquote></details>

This proposed requirement can be easily be done by asking the FemModel to own (a separate) system that manages the data consumed by the FemModel, instead of inviting an outside system to do the job. This would imply that each FemData would own that context where the FemData resides. This is similar to the previous iteration of the prototype that, IIRC, @sherm1 and @jwnimmer-tri dislike. 

It seems to me that both approaches achieve our goal of removing the bespoke caching mechanism, and I'd like to understand the defect that you see (if any) in them.


<!-- Sent from Reviewable.io -->

2022-02-15 20:56 UTC, amcastro-tri requested changes
> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/10)* status: 1 of 32 files reviewed, 11 unresolved discussions (waiting on @amcastro-tri, @jwnimmer-tri, @sherm1, and @xuchenhan-tri)

___
*[multibody/fem/test/volumetric_model_test.cc, line 131 at r4](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-Mvy8K_63szpRRTjWnOq:-Mvz9WOtBJbY3pSOgz8v:bt3mvwo) ([raw file](https://github.com/xuchenhan-tri/drake/blob/a99900a384631eb2c8d6cf30d68298f1401a24ab/multibody/fem/test/volumetric_model_test.cc#L131)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This proposed requirement can be easily be done by asking the FemModel to own (a separate) system that manages the data consumed by the FemModel, instead of inviting an outside system to do the job. This would imply that each FemData would own that context where the FemData resides. This is similar to the previous iteration of the prototype that, IIRC, @sherm1 and @jwnimmer-tri dislike. 

It seems to me that both approaches achieve our goal of removing the bespoke caching mechanism, and I'd like to understand the defect that you see (if any) in them.
</blockquote></details>

Re the defect on this design, if any, I believe I tried to be as clearly as possible above. If not, lets discuss tomorrow in detail.

Now that you went through these two designs, TBH I am not sure or I don't recall why @sherm1 and @jwnimmer-tri didn't like the original proposal. I think the discussion went too deep into details and that's why I decided to take a step back and look at what we'd like at call sites.


<!-- Sent from Reviewable.io -->

2022-02-16 17:37 UTC, sherm1 requested changes
> Reviewed 2 of 27 files at r3, 1 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/10)* status: 4 of 32 files reviewed, 10 unresolved discussions (waiting on @amcastro-tri, @jwnimmer-tri, and @xuchenhan-tri)

___
*[multibody/fem/fem_data_manager.h, line 52 at r4](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-Mw2UCNu5EK6YLxuDUzC:-Mw2UCNu5EK6YLxuDUzD:bfxth1w) ([raw file](https://github.com/xuchenhan-tri/drake/blob/a99900a384631eb2c8d6cf30d68298f1401a24ab/multibody/fem/fem_data_manager.h#L52)):*
> ```objc
>     systems::CacheEntryValue& value =
>         cache_entry.get_mutable_cache_entry_value(*context_);
>     value.mark_up_to_date();
> ```

Why would this be up to date here? Wouldn't it just contain garbage at this point?
___
*[multibody/fem/fem_data_manager.h, line 94 at r4](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-Mw2Usq_E-I6Z-D47yVb:-Mw2Usq_E-I6Z-D47yVc:b4rnobp) ([raw file](https://github.com/xuchenhan-tri/drake/blob/a99900a384631eb2c8d6cf30d68298f1401a24ab/multibody/fem/fem_data_manager.h#L94)):*
> ```objc
> 
>     /* Any new value is treated as the up-to-date value. */
>     value.mark_up_to_date();
> ```

This seems wrong since no up-to-date value has been written to the state yet. The flag should reflect the true condition of the cache entry, not something anticipated.
___
*[multibody/fem/fem_model.h, line 81 at r3](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-MvuonGf-dkAolUx0uYO:-Mw2W39l7xD1rt6HSubG:bjzlpos) ([raw file](https://github.com/xuchenhan-tri/drake/blob/a6784973836dc1f16113825917d148b93098a862/multibody/fem/fem_model.h#L81)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

> This should not be using NoopCalc(). Instead it should use a dummy calc method that unconditionally throws -- no one should ever call it because you calculate it with your own bespoke code.

Done.

Re naming: I agree this is not the scratch in the sense of #15943, but I'm hesitant to call this `next_state_cache_entry` for the reason I describe below.

Re having the cache entry depend on current state: I think this might be doable, but it's a non-goal for `FemDataManager`. I design `FemDataManager` for one purpose and one purpose only: to replace the bespoke caching in what used be be `FemState`. The goal is to keep the API's we like about FEM the same as much as possible. In particular, we have the freedom to create a FEM state, move it to where-ever we want, and ask FEM model to provide information at that state (e.g. residual, tangent matrix etc). That's the core functionality of FEM and it provides us with lots of flexibility. If we think of the cached state as the "next time step's state", then we can't avoid bringing a time stepping scheme and a solver into the picture. That, IMO, makes the code structure less modular.
</blockquote></details>

Hmmm. This has wondering whether "cache" (bespoke or otherwise) is not really the right design pattern for the computation you are performing. Looking forward to discussion f2f.
___
*[multibody/fem/fem_solver.cc, line 58 at r3](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-MvulowD07VL9GmqcEXk:-Mw2ZnpCDpnljWKCf1Qu:b-1x6sdq) ([raw file](https://github.com/xuchenhan-tri/drake/blob/a6784973836dc1f16113825917d148b93098a862/multibody/fem/fem_solver.cc#L58)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Done for the first two bullet points.
Re the 3rd point: should we  have the user of `FemDataManager` manually mark the state cache up to date? It seems to be inviting trouble. I'd rather have it done automatically. Obviously there's pitfall to that as well (see my comments in front of `FemDataManager::GetMutableFemState()`, but a developer familiar with Drake should realize that they need to be extra cautious around GetMutable methods.
</blockquote></details>

Agreed -- but because of the need for a caller of GetMutable to be cautious, they should be managing the up-to-date flag here at the same level so that it can be determined by inspection that the code is correct. At least if some called function fiddles with the flag the comments here should make it clear that the caller of GetMutable has taken their flag-management responsibility seriously.
___
*[multibody/fem/fem_solver.cc, line 90 at r3](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-Mvuo-Hn1Oo0dp1BNJZa:-Mw2__hDACmo3UIatucB:bn9kokz) ([raw file](https://github.com/xuchenhan-tri/drake/blob/a6784973836dc1f16113825917d148b93098a862/multibody/fem/fem_solver.cc#L90)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Partly done. See reply above.
</blockquote></details>

But now what is the state of the up-to-date flag?
___
*[multibody/fem/velocity_newmark_scheme.cc, line 34 at r4](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-Mw2_yrJCWGqeY7MFIFb:-Mw2_yrJCWGqeY7MFIFc:b-82oiae) ([raw file](https://github.com/xuchenhan-tri/drake/blob/a99900a384631eb2c8d6cf30d68298f1401a24ab/multibody/fem/velocity_newmark_scheme.cc#L34)):*
> ```cpp
>   state->SetAccelerations(one_over_dt_gamma_ * (v - vn) -
>                           (1.0 - gamma()) / gamma() * an);
>   state->SetVelocities(v);
> ```

Doesn't this change convert the method from semi-implicit to explicit? Previously the positions were updated with the _new_ value of vn but now they are updated with the _prev_ value of vn.
___
*[multibody/fem/test/volumetric_model_test.cc, line 131 at r4](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-Mvy8K_63szpRRTjWnOq:-Mw2ad9d3FJFaxSOo_3P:bexgpe9) ([raw file](https://github.com/xuchenhan-tri/drake/blob/a99900a384631eb2c8d6cf30d68298f1401a24ab/multibody/fem/test/volumetric_model_test.cc#L131)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Re the defect on this design, if any, I believe I tried to be as clearly as possible above. If not, lets discuss tomorrow in detail.

Now that you went through these two designs, TBH I am not sure or I don't recall why @sherm1 and @jwnimmer-tri didn't like the original proposal. I think the discussion went too deep into details and that's why I decided to take a step back and look at what we'd like at call sites.
</blockquote></details>

Again this makes me wonder whether "cache" is the right way to think about the internal computation.


<!-- Sent from Reviewable.io -->

2022-02-16 17:51 UTC, amcastro-tri requested changes
> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/10)* status: 4 of 32 files reviewed, 10 unresolved discussions (waiting on @amcastro-tri, @jwnimmer-tri, and @xuchenhan-tri)

___
*[multibody/fem/test/volumetric_model_test.cc, line 131 at r4](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-Mvy8K_63szpRRTjWnOq:-Mw2decz9bQwdG76LoJY:b2o7qgc) ([raw file](https://github.com/xuchenhan-tri/drake/blob/a99900a384631eb2c8d6cf30d68298f1401a24ab/multibody/fem/test/volumetric_model_test.cc#L131)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Again this makes me wonder whether "cache" is the right way to think about the internal computation.
</blockquote></details>

I'd love to hear what new mental picture you have after this example. Lets discuss f2f.
IMO "cache" is the right way to think about this, but we just have to make sure we don't think too hard on how to hack around the `systems::` framework. First the requirements, second whether the `systems::` framework has what we need.
I'd like to hear also if the example I give above makes any sense at all.


<!-- Sent from Reviewable.io -->

2022-02-16 17:59 UTC, xuchenhan-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/10)* status: 4 of 32 files reviewed, 10 unresolved discussions (waiting on @amcastro-tri, @jwnimmer-tri, @sherm1, and @xuchenhan-tri)

___
*[multibody/fem/fem_data_manager.h, line 52 at r4](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-Mw2UCNu5EK6YLxuDUzC:-Mw2enXA4dZOA8Qgf4-5:bq6t5tq) ([raw file](https://github.com/xuchenhan-tri/drake/blob/a99900a384631eb2c8d6cf30d68298f1401a24ab/multibody/fem/fem_data_manager.h#L52)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Why would this be up to date here? Wouldn't it just contain garbage at this point?
</blockquote></details>

I'm assuming that the model value is the desired initial data here. 
___
*[multibody/fem/fem_data_manager.h, line 94 at r4](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-Mw2Usq_E-I6Z-D47yVb:-Mw2fDlX80J-sFBBMNXe:b-62sivr) ([raw file](https://github.com/xuchenhan-tri/drake/blob/a99900a384631eb2c8d6cf30d68298f1401a24ab/multibody/fem/fem_data_manager.h#L94)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

This seems wrong since no up-to-date value has been written to the state yet. The flag should reflect the true condition of the cache entry, not something anticipated.
</blockquote></details>

I'd hate to ask the user to constantly remember marking state up-to-date. It defeats the purpose of the design. I can imagine not exposing the GetMutable method and have only Set methods that mark the value as up-to-date, at the cost of copying some states.
___
*[multibody/fem/velocity_newmark_scheme.cc, line 34 at r4](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-Mw2_yrJCWGqeY7MFIFb:-Mw2ft7p8Ql8aUeN66LC:b-x7lw31) ([raw file](https://github.com/xuchenhan-tri/drake/blob/a99900a384631eb2c8d6cf30d68298f1401a24ab/multibody/fem/velocity_newmark_scheme.cc#L34)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Doesn't this change convert the method from semi-implicit to explicit? Previously the positions were updated with the _new_ value of vn but now they are updated with the _prev_ value of vn.
</blockquote></details>

I don't think so. vn should always be the value at the previous time step.


<!-- Sent from Reviewable.io -->

2022-02-22 01:54 UTC, xuchenhan-tri reviewed
I pushed a new iteration. Even though it still needs some cleaning up, I like the way it looks right now. Take a look at `fem_data.h` and how they are used at call sites in `volumetric_model_test.cc`.

Essentially we have the same set of APIs throughout FEM except that what used to be called "FemState" is now "FemData". I have also done away with some annoying static casts along with the other changes. 

I'll clean this up and PR small pieces upstream.

> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-:-MwU6hEj1x6jlQOaUwU0:b-gyp5hn)* status: 0 of 40 files reviewed, 10 unresolved discussions (waiting on @amcastro-tri, @jwnimmer-tri, @sherm1, and @xuchenhan-tri)



<!-- Sent from Reviewable.io -->

2022-02-22 15:37 UTC, amcastro-tri requested changes
I like this iteration a lot @xuchenhan-tri! I only sprinkled a few nits and comments but overall I do like it and I find this the way to go. You did an excellent job here. Hopefully @jwnimmer-tri and @sherm1 like this also!

I tried to focus on the big picture of the design rather than implementation details. There are some places where I thought we could've done things differently but I think we can iron things out as you push this into a Drake PR.

>  what used to be called "FemState" is now "FemData"

It looks to me that what used to be `FemState` is no longer used? if that's the case, I much rather prefer `FemState` instead of `FemData`. 

> Reviewed 6 of 38 files at r5.
> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-:-MwX37M07xNw5PkhV3fO:b-y0rew6)* status: 6 of 40 files reviewed, 11 unresolved discussions (waiting on @amcastro-tri, @sherm1, and @xuchenhan-tri)

___
*[multibody/fem/fem_data.h, line 35 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-MwX-aU81ARwNqQygkQ4:-MwX-aU81ARwNqQygkQ5:bdf1wp1) ([raw file](https://github.com/xuchenhan-tri/drake/blob/89e9325487a887eeeef2d6c1433dd0238a4268d0/multibody/fem/fem_data.h#L35)):*
> ```objc
>  construction. */
> template <typename T>
> class FemData {
> ```

I think I like this a lot.
I'd only suggest thinking a bit harder about the name for this class. Suggestions/buzzwords I can think of:
1. Workspace, since this is state+cache.
2. Evaluator, since this provides evaluation methods.
3. State, since this really conveys the state idea, again state+cache
4. Manager, since this manages state + cache (I only added this one for completeness. I actually don't like it overloads this term already in master)

So combinations of those could be:
1. FemWorkspace
2. FemStateEvaluator
3. FemStateManager


Re "data". I don't know why but to me "data" sounds more like "model data", frozen, independent of state. But I don't think we use this term anywhere in Drake so I'd be open to this term if that's what we converge to.
___
*[multibody/fem/fem_model.h, line 164 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-MwX2JPc-m_pOkY9vnGu:-MwX2JPc-m_pOkY9vnGv:b-8g44tu) ([raw file](https://github.com/xuchenhan-tri/drake/blob/89e9325487a887eeeef2d6c1433dd0238a4268d0/multibody/fem/fem_model.h#L164)):*
> ```objc
>   2. if they have different number of dofs, or
>   3. if they have different number of elements. */
>   void ThrowIfModelDataIncompatible(const char* func,
> ```

btw, very nice, i love you also thought about this.
___
*[multibody/fem/test/volumetric_model_test.cc, line 182 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-MwWyfwyDeKBZQeZr5eO:-MwWyfwyDeKBZQeZr5eP:b9vkdwp) ([raw file](https://github.com/xuchenhan-tri/drake/blob/89e9325487a887eeeef2d6c1433dd0238a4268d0/multibody/fem/test/volumetric_model_test.cc#L182)):*
> ```cpp
>  that calculated as Eigen::SparseMatrix. */
> TEST_F(VolumetricModelTest, TangentMatrixParity) {
>   const FemData<AutoDiffXd> fem_data = MakeDeformedFemData(model_);
> ```

random question. I find it confusing we are using AutoDiffXd in this test? is that necessary?
Maybe for the version in master we'd like to document why AutoDiffXd is being used here.
___
*[multibody/fem/test/volumetric_model_test.cc, line 184 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-MwWxckN7mYbLCJBfpzi:-MwWxckO7Rvtu8xMvvcQ:baal4mr) ([raw file](https://github.com/xuchenhan-tri/drake/blob/89e9325487a887eeeef2d6c1433dd0238a4268d0/multibody/fem/test/volumetric_model_test.cc#L184)):*
> ```cpp
>   const FemData<AutoDiffXd> fem_data = MakeDeformedFemData(model_);
>   Eigen::SparseMatrix<AutoDiffXd> eigen_tangent_matrix =
>       model_.MakeEigenSparseTangentMatrix();
> ```

nit, this `MakeEigenSparseTangentMatrix() ` confused me. Maybe if we follow Drake's lingo we can call this `AllocEigenSparseTangentMatrix()`?
___
*[multibody/fem/test/volumetric_model_test.cc, line 186 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-MwWyO5pCJ6YH4YEztRA:-MwWyO5pCJ6YH4YEztRB:b-5bbs0o) ([raw file](https://github.com/xuchenhan-tri/drake/blob/89e9325487a887eeeef2d6c1433dd0238a4268d0/multibody/fem/test/volumetric_model_test.cc#L186)):*
> ```cpp
>       model_.MakeEigenSparseTangentMatrix();
>   model_.CalcTangentMatrix(fem_data, integrator_.weights(),
>                            &eigen_tangent_matrix);
> ```

btw, these calls read very nice!


<!-- Sent from Reviewable.io -->

2022-02-22 17:44 UTC, xuchenhan-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/10)* status: 6 of 40 files reviewed, 7 unresolved discussions (waiting on @amcastro-tri, @sherm1, and @xuchenhan-tri)

___
*[multibody/fem/fem_solver.cc, line 58 at r3](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-MvulowD07VL9GmqcEXk:-MwXWxk-DRmsPyIfl2gZ:ba8r316) ([raw file](https://github.com/xuchenhan-tri/drake/blob/a6784973836dc1f16113825917d148b93098a862/multibody/fem/fem_solver.cc#L58)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Agreed -- but because of the need for a caller of GetMutable to be cautious, they should be managing the up-to-date flag here at the same level so that it can be determined by inspection that the code is correct. At least if some called function fiddles with the flag the comments here should make it clear that the caller of GetMutable has taken their flag-management responsibility seriously.
</blockquote></details>

Resolving this discussion in light of new design.
___
*[multibody/fem/fem_solver.cc, line 90 at r3](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-Mvuo-Hn1Oo0dp1BNJZa:-MwXX5Am0KyJftsycI_3:bxeve40) ([raw file](https://github.com/xuchenhan-tri/drake/blob/a6784973836dc1f16113825917d148b93098a862/multibody/fem/fem_solver.cc#L90)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

But now what is the state of the up-to-date flag?
</blockquote></details>

Resolving this discussion in light of new design.
___
*[multibody/fem/test/volumetric_model_test.cc, line 138 at r4](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-MvyCgCp-XMm1BFSEJPz:-MwXX90YCtza7vc5vrRt:ba8r316) ([raw file](https://github.com/xuchenhan-tri/drake/blob/a99900a384631eb2c8d6cf30d68298f1401a24ab/multibody/fem/test/volumetric_model_test.cc#L138)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

with the API I propose above, doing `data->GetMutableFemState()` still is allowed since we do have a mutable FemData around. 
</blockquote></details>

Resolving this discussion in light of new design.
___
*[multibody/fem/test/volumetric_model_test.cc, line 182 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-MwWyfwyDeKBZQeZr5eO:-MwXWEdX0puoV4E-Er8J:b-x9sg5l) ([raw file](https://github.com/xuchenhan-tri/drake/blob/89e9325487a887eeeef2d6c1433dd0238a4268d0/multibody/fem/test/volumetric_model_test.cc#L182)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

random question. I find it confusing we are using AutoDiffXd in this test? is that necessary?
Maybe for the version in master we'd like to document why AutoDiffXd is being used here.
</blockquote></details>

working. AutoDiffXd is not necessary in this particular test. AutoDiffXd is used to verify tangent matrix is the derivative of the residual in the test above.
___
*[multibody/fem/test/volumetric_model_test.cc, line 184 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-MwWxckN7mYbLCJBfpzi:-MwXW2p-1dI2PqY23pBz:b-y91ihq) ([raw file](https://github.com/xuchenhan-tri/drake/blob/89e9325487a887eeeef2d6c1433dd0238a4268d0/multibody/fem/test/volumetric_model_test.cc#L184)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, this `MakeEigenSparseTangentMatrix() ` confused me. Maybe if we follow Drake's lingo we can call this `AllocEigenSparseTangentMatrix()`?
</blockquote></details>

working.


<!-- Sent from Reviewable.io -->

2022-02-22 19:06 UTC, xuchenhan-tri reviewed
I'm not strong about FemState vs. FemData, but I dislike the other proposed names.
Per f2f with @sherm1, he is ok with FemState as well, so I'm going with that since you (@amcastro-tri) like it.

> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-:-MwXYWxK96lpSAQuZd--:b-b7pnig)* status: 6 of 40 files reviewed, 7 unresolved discussions (waiting on @amcastro-tri, @sherm1, and @xuchenhan-tri)

___
*[multibody/fem/fem_data.h, line 35 at r5](https://reviewable.io/reviews/xuchenhan-tri/drake/10#-MwX-aU81ARwNqQygkQ4:-MwXYe2_7FXE9rF3DIgV:b-s0ixto) ([raw file](https://github.com/xuchenhan-tri/drake/blob/89e9325487a887eeeef2d6c1433dd0238a4268d0/multibody/fem/fem_data.h#L35)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I think I like this a lot.
I'd only suggest thinking a bit harder about the name for this class. Suggestions/buzzwords I can think of:
1. Workspace, since this is state+cache.
2. Evaluator, since this provides evaluation methods.
3. State, since this really conveys the state idea, again state+cache
4. Manager, since this manages state + cache (I only added this one for completeness. I actually don't like it overloads this term already in master)

So combinations of those could be:
1. FemWorkspace
2. FemStateEvaluator
3. FemStateManager


Re "data". I don't know why but to me "data" sounds more like "model data", frozen, independent of state. But I don't think we use this term anywhere in Drake so I'd be open to this term if that's what we converge to.
</blockquote></details>

Working, see reply in the main thread.


<!-- Sent from Reviewable.io -->

2022-05-24 16:24 UTC, xuchenhan-tri commented
Closing as the caching system has landed in Drake main.

2022-05-24 16:24 UTC, closed without merging