Quadrature
xuchenhan-tri/drake pull request #4
Opened 2020-10-05 17:47 UTC by xuchenhan-tri

A prototype for quadrature points.

2020-10-05 20:14 UTC, amcastro-tri requested changes
Very nice work @xuchenhan-tri, I loved the unit tests.

I see a mixture of template fixed sizes and heap allocations at runtime for weighs. I guess I'd go all in on fix sizes or just have a simple NVI implementation with heap allocations but not a mix.
IMO your fixed template sizes is very nice. I believe it'd be betther if we have Quadrature to have those templates as well so that we know everything at compile time. PTAL

> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-:-MIuO5p198x863JTu2L9:btzvs0u)* status: 2 of 3 files reviewed, 15 unresolved discussions (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[fem/quadrature.h, line 12 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-MIuLGd7-x0_V17CJ0gN:-MIuLGd82pENn4BTJUF5:bs33vhr) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2e683c970bc11d0246a4381ccfd93593d9f7899/fem/quadrature.h#L12)):*
> ```objc
> namespace drake {
> namespace fem {
> template <typename T, int D>
> ```

wondering if we don't want N here? that'd allow getting rid of the heap allocation in `points_` and in` weights_`
___
*[fem/quadrature.h, line 49 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-MIuLV7mBff8Il7QCEkZ:-MIuLV7mBff8Il7QCEk_:bkv2fxz) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2e683c970bc11d0246a4381ccfd93593d9f7899/fem/quadrature.h#L49)):*
> ```objc
> 
>  private:
>   std::vector<VecType> points_;
> ```

you could probably pass these on the constructor, that way the implementer does not have to remember to call `set_points()` nor `set_weights()`.
___
*[fem/quadrature.h, line 57 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-MIuG9ELAsL8OFpqyyoy:-MIuG9ELAsL8OFpqyyoz:bpbh64r) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2e683c970bc11d0246a4381ccfd93593d9f7899/fem/quadrature.h#L57)):*
> ```objc
> The 2D unit triangle has vertices located at (0,0), (1,0) and (0,1). The 3D unit
> tetrahedron has vertices located at (0,0,0), (1,0,0), (0,1,0) and (0,0,1).
>  @tparam N order of the quadrature rule. Must be 1, 2, or 3.
> ```

nit, maybe name N -> QuadratureOrder? or similar
___
*[fem/quadrature.h, line 58 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-MIuGGrN7ZSeS72bp9H9:-MIuGGrN7ZSeS72bp9HA:bkb3sup) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2e683c970bc11d0246a4381ccfd93593d9f7899/fem/quadrature.h#L58)):*
> ```objc
> tetrahedron has vertices located at (0,0,0), (1,0,0), (0,1,0) and (0,0,1).
>  @tparam N order of the quadrature rule. Must be 1, 2, or 3.
>  @tparam D dimension of the unit simplex. Must be 2, or 3.
> ```

nit, maybe name SpatialDimension? or similar

BTW, these abbreviations are discouraged (forbidden for the most part) by the GSG: https://drake.mit.edu/styleguide/cppguide.html
___
*[fem/quadrature.h, line 70 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-MIuHPrz0StWJrojSgdY:-MIuHPrz0StWJrojSgdZ:b-76k4wl) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2e683c970bc11d0246a4381ccfd93593d9f7899/fem/quadrature.h#L70)):*
> ```objc
>   SimplexGaussianQuadrature() {
>     // We only support linear, quadratic and cubic integration.
>     if constexpr (N < 1 || N > 3) {
> ```

nit, usually if there is something we know at compile time, we'd like to abort the compilation at compile time, no need to wait to runtime. 
Therefore here you can use `static_assert( 1<=N && N <=3, "Only N = 1,2 or, 3 is supported");`
___
*[fem/quadrature.h, line 70 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-MIuLixS6rLZlfQqKqbA:-MIuLixS6rLZlfQqKqbB:b4czeun) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2e683c970bc11d0246a4381ccfd93593d9f7899/fem/quadrature.h#L70)):*
> ```objc
>   SimplexGaussianQuadrature() {
>     // We only support linear, quadratic and cubic integration.
>     if constexpr (N < 1 || N > 3) {
> ```

if all this setup to get points and weights was in some templated method, you could probably pass this info at construction. Something like:
```c++
SimplexGaussianQuadrature : Quadrature(GetPoints<N,D>(), GetWeights<N,D>()) {}
```
___
*[fem/quadrature.h, line 77 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-MIuI2rP-E0Rsmofko7a:-MIuI2rP-E0Rsmofko7b:b-m8ronr) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2e683c970bc11d0246a4381ccfd93593d9f7899/fem/quadrature.h#L77)):*
> ```objc
>       this->ThrowNotImplemented(N);
>     }
>     std::vector<VecType> points;
> ```

here you can use `std::array` to avoid heap allocation, since you know the size.
___
*[fem/quadrature.h, line 91 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-MIuJKZ30raY_uCxJz27:-MIuJKZ30raY_uCxJz28:b-we7urn) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2e683c970bc11d0246a4381ccfd93593d9f7899/fem/quadrature.h#L91)):*
> ```objc
>         //  (2/3, 1/6)                     1/3
>         //  (1/6, 2/3)                     1/3
>         points.resize(3);
> ```

nit, no need to resize, you know the size at compile time.
___
*[fem/quadrature.h, line 92 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-MIuIhiR68TT4wSLWjKD:-MIuIhiS4VHxXFlYDBKq:b-pin9cp) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2e683c970bc11d0246a4381ccfd93593d9f7899/fem/quadrature.h#L92)):*
> ```objc
>         //  (1/6, 2/3)                     1/3
>         points.resize(3);
>         points[0] = (Vector2<T>() << 1.0 / 6.0, 1.0 / 6.0).finished();
> ```

I wonder, does the inializer list work here? Like `points = {{1/6, 1/6}, {2/3, 1/6}, {1/6,2/3}}
___
*[fem/test/simplex_gaussian_quadrature_test.cc, line 14 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-MIuMYQq6990IIMYe6O6:-MIuMYQq6990IIMYe6O7:b2ewx0e) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2e683c970bc11d0246a4381ccfd93593d9f7899/fem/test/simplex_gaussian_quadrature_test.cc#L14)):*
> ```cpp
> using Eigen::Vector2d;
> using Eigen::Vector3d;
> class LinearTestFunction2D {
> ```

nit, if everything will be public might as well use a struct.
___
*[fem/test/simplex_gaussian_quadrature_test.cc, line 93 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-MIuMloHAfscnY6EiZ80:-MIuMloHAfscnY6EiZ81:b-27nvzb) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2e683c970bc11d0246a4381ccfd93593d9f7899/fem/test/simplex_gaussian_quadrature_test.cc#L93)):*
> ```cpp
>  protected:
>   std::unique_ptr<SimplexGaussianQuadrature<double, 1, 2>>
>       linear_2d_quadrature_;
> ```

why in the heap? could we just have stack variables? or is there a limitation I'm missing?
___
*[fem/test/simplex_gaussian_quadrature_test.cc, line 118 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-MIuN3qa2NZ-ztzI2ubN:-MIuN3qa2NZ-ztzI2ubO:b92idvv) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2e683c970bc11d0246a4381ccfd93593d9f7899/fem/test/simplex_gaussian_quadrature_test.cc#L118)):*
> ```cpp
>   double analytic_integral = 0.5 * LinearTestFunction2D::a0 +
>                              1.0 / 6.0 * LinearTestFunction2D::a1 +
>                              1.0 / 6.0 * LinearTestFunction2D::a2;
> ```

I'd place this in `LinearTestFunction2D::AnalyticalIntegralOverUnitTriangle()` or similar name. Point is, it's seem to belong there.
___
*[fem/test/simplex_gaussian_quadrature_test.cc, line 151 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-MIuNUZiE8rij4X3MpMI:-MIuNUZiE8rij4X3MpMJ:b-bu89r2) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2e683c970bc11d0246a4381ccfd93593d9f7899/fem/test/simplex_gaussian_quadrature_test.cc#L151)):*
> ```cpp
>   // quadrature point and xᵢ is the location of the i-th quadrature point.
>   double numerical_integral = 0;
>   for (int i = 0; i < quadratic_2d_quadrature_->num_points(); ++i) {
> ```

maybe place this in a lil method in your test fixture? since you use it several times in all tests.
___
*[fem/test/simplex_gaussian_quadrature_test.cc, line 205 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-MIuNbmS6YMuo [...]

2020-10-05 22:24 UTC, xuchenhan-tri reviewed
Thanks for the quick review @amcastro-tri. I was debating between fixed vs. dynamic quite a bit, and I was tempted to go all in on fixed sizes but had some concerns (see the thread below). Maybe the issue will be clearer when we see more pieces of the puzzle (when FemElement is done). 

You can consider all the comments I did not respond to as responded with "Will do." I will get to them when I finish FemElement. Hopefully at that point we will have clear answer as to whether we want fixed size everything in quadrature.

> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-:-MIuqM5z8Z-myv4CFmY7:bugi0dd)* status: 2 of 3 files reviewed, 15 unresolved discussions (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[fem/quadrature.h, line 12 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-MIuLGd7-x0_V17CJ0gN:-MIunodP6YKPy540eHKU:bghmttk) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2e683c970bc11d0246a4381ccfd93593d9f7899/fem/quadrature.h#L12)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

wondering if we don't want N here? that'd allow getting rid of the heap allocation in `points_` and in` weights_`
</blockquote></details>

I initially had N in the template so that we can get rid of heap allocations, but I found that it makes using the quadrature points a little inconvenient. Most notably:

1) The isoparametric element class has functions that take quadratures which would have to be templated on N as well.
2) The FemElement class holds onto the quadrature point it uses, so it would have to be templatized on the order of quadrature rule as well.

I want to hear your thoughts on this. If you think full-on templated everything is the way to go, then we can add N as another template parameter.
___
*[fem/quadrature.h, line 92 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-MIuIhiR68TT4wSLWjKD:-MIuq3DTA3DsZSV4CUv6:b123boy) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2e683c970bc11d0246a4381ccfd93593d9f7899/fem/quadrature.h#L92)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I wonder, does the inializer list work here? Like `points = {{1/6, 1/6}, {2/3, 1/6}, {1/6,2/3}}
</blockquote></details>

I always thought Eigen doesn't support initializer list, but I tested it and it works. Thanks.


<!-- Sent from Reviewable.io -->

2020-10-06 13:18 UTC, amcastro-tri requested changes
That makes sense @xuchenhan-tri, thanks for the explanation.

> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-:-MIxz2_5180GMeHYCQP9:b-k26n6z)* status: 2 of 3 files reviewed, 17 unresolved discussions (waiting on @amcastro-tri and @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-MIy1pYM21x4GG4MLXuT:-MIy1pYN69EGHqh41acd:b-f7tv9c) (no related file):*
ok , based on your replies this is what I think:
1. I do like your `get_point()` `get_weight()` are not virtual and therefore do not go through a virtual table (faster).
2. The fact that we do want polymorphism throws away having N as a template, that's ok.
3. I'd remove the set_point() and set_weight() methods for the reasons I stated before and I'd instead have a protected `Quadrature(std::vector<VectorN<T>> points, std::vector<T> weights)`. That forces subclasses to use that constructor in their own subclass public constructor. 

What do you think?

---
___
*[fem/quadrature.h, line 12 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-MIuLGd7-x0_V17CJ0gN:-MIxz7SREWfsbDqHx1Ym:b-8d4e6g) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2e683c970bc11d0246a4381ccfd93593d9f7899/fem/quadrature.h#L12)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I initially had N in the template so that we can get rid of heap allocations, but I found that it makes using the quadrature points a little inconvenient. Most notably:

1) The isoparametric element class has functions that take quadratures which would have to be templated on N as well.
2) The FemElement class holds onto the quadrature point it uses, so it would have to be templatized on the order of quadrature rule as well.

I want to hear your thoughts on this. If you think full-on templated everything is the way to go, then we can add N as another template parameter.
</blockquote></details>

ah, great point. Therefore I'd summarize this as "we do want to support polymorphism".
I'd imagine the use case for quadrature would be:
1. It gets instantiated outiside a big loop over elements (I believe the notes on isoparametric elements do this) or,
2. The FemModel class stores the set of quadratures needed (for us I believe will always be a single one).

Therefore, the initialization at construction, even if we make it on the heap, will be negligible. So probably not worth trying to premature optimize with fixed size templates?
___
*[fem/quadrature.h, line 17 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-MIy2bdCBjfiBjBBKcDO:-MIy2bdCBjfiBjBBKcDP:b-t6accu) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2e683c970bc11d0246a4381ccfd93593d9f7899/fem/quadrature.h#L17)):*
> ```objc
>   virtual ~Quadrature() = default;
>   using VecType = Eigen::Matrix<T, D, 1>;
>   /// The number of quadrature points for the quadrature rule.
> ```

nit, given in Drake we use Vector2, Vector3, VectorX, ect, here we could provably use `VectorD` to sort of abide to the same mnemonics. 
___
*[fem/quadrature.h, line 92 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-MIuIhiR68TT4wSLWjKD:-MIxzz9u-GHgwcgrd8hA:b-m2twzr) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2e683c970bc11d0246a4381ccfd93593d9f7899/fem/quadrature.h#L92)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I always thought Eigen doesn't support initializer list, but I tested it and it works. Thanks.
</blockquote></details>

it's a c++11 feature, not an Eigen feature. I believe the only requirement for them to work is that you have a ctor that takes whatever you put inside braces, but I'm a bit fuzzy on that requirement. 


<!-- Sent from Reviewable.io -->

2020-10-06 16:06 UTC, xuchenhan-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/4)* status: 2 of 3 files reviewed, 17 unresolved discussions (waiting on @amcastro-tri and @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-MIy1pYM21x4GG4MLXuT:-MIyeS4jEhiTJ1rgjRr6:brxp9sd) (no related file):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

ok , based on your replies this is what I think:
1. I do like your `get_point()` `get_weight()` are not virtual and therefore do not go through a virtual table (faster).
2. The fact that we do want polymorphism throws away having N as a template, that's ok.
3. I'd remove the set_point() and set_weight() methods for the reasons I stated before and I'd instead have a protected `Quadrature(std::vector<VectorN<T>> points, std::vector<T> weights)`. That forces subclasses to use that constructor in their own subclass public constructor. 

What do you think?
</blockquote></details>

Sounds good!

---


<!-- Sent from Reviewable.io -->

2020-10-09 05:01 UTC, xuchenhan-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/4)* status: 2 of 3 files reviewed, 10 unresolved discussions (waiting on @amcastro-tri)

___
*[fem/quadrature.h, line 12 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-MIuLGd7-x0_V17CJ0gN:-MJ9lL1xBDOqCOAAGznU:b4a7pgh) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2e683c970bc11d0246a4381ccfd93593d9f7899/fem/quadrature.h#L12)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

ah, great point. Therefore I'd summarize this as "we do want to support polymorphism".
I'd imagine the use case for quadrature would be:
1. It gets instantiated outiside a big loop over elements (I believe the notes on isoparametric elements do this) or,
2. The FemModel class stores the set of quadratures needed (for us I believe will always be a single one).

Therefore, the initialization at construction, even if we make it on the heap, will be negligible. So probably not worth trying to premature optimize with fixed size templates?
</blockquote></details>

I currently have each isoparametric element own a quadrature it uses, and each FemElement owns an isoparametric element. The cost should all be at initialization time so it's probably okay?
___
*[fem/quadrature.h, line 17 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-MIy2bdCBjfiBjBBKcDO:-MJ9mUNC-FM6A3Y4vtSn:b-896fix) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2e683c970bc11d0246a4381ccfd93593d9f7899/fem/quadrature.h#L17)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, given in Drake we use Vector2, Vector3, VectorX, ect, here we could provably use `VectorD` to sort of abide to the same mnemonics. 
</blockquote></details>

Done.
___
*[fem/quadrature.h, line 49 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-MIuLV7mBff8Il7QCEkZ:-MJA_p2p6KtM_5k5iMkf:b-896fix) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2e683c970bc11d0246a4381ccfd93593d9f7899/fem/quadrature.h#L49)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

you could probably pass these on the constructor, that way the implementer does not have to remember to call `set_points()` nor `set_weights()`.
</blockquote></details>

Done.
___
*[fem/quadrature.h, line 57 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-MIuG9ELAsL8OFpqyyoy:-MJAQNWFBBgfDWgN1eJ_:b-896fix) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2e683c970bc11d0246a4381ccfd93593d9f7899/fem/quadrature.h#L57)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, maybe name N -> QuadratureOrder? or similar
</blockquote></details>

Done.
___
*[fem/quadrature.h, line 58 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-MIuGGrN7ZSeS72bp9H9:-MJAQvf3D_dhJPKh8xpa:b-896fix) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2e683c970bc11d0246a4381ccfd93593d9f7899/fem/quadrature.h#L58)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, maybe name SpatialDimension? or similar

BTW, these abbreviations are discouraged (forbidden for the most part) by the GSG: https://drake.mit.edu/styleguide/cppguide.html
</blockquote></details>

Done.
___
*[fem/quadrature.h, line 70 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-MIuHPrz0StWJrojSgdY:-MJARAtbAdUJ9dldZeKm:b-896fix) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2e683c970bc11d0246a4381ccfd93593d9f7899/fem/quadrature.h#L70)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, usually if there is something we know at compile time, we'd like to abort the compilation at compile time, no need to wait to runtime. 
Therefore here you can use `static_assert( 1<=N && N <=3, "Only N = 1,2 or, 3 is supported");`
</blockquote></details>

Done.
___
*[fem/quadrature.h, line 70 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-MIuLixS6rLZlfQqKqbA:-MJA_qyK4DVa2qR8vPFp:b-896fix) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2e683c970bc11d0246a4381ccfd93593d9f7899/fem/quadrature.h#L70)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

if all this setup to get points and weights was in some templated method, you could probably pass this info at construction. Something like:
```c++
SimplexGaussianQuadrature : Quadrature(GetPoints<N,D>(), GetWeights<N,D>()) {}
```
</blockquote></details>

Done.
___
*[fem/quadrature.h, line 77 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-MIuI2rP-E0Rsmofko7a:-MJA_rTlAehVR9t3-RHj:b-896fix) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2e683c970bc11d0246a4381ccfd93593d9f7899/fem/quadrature.h#L77)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

here you can use `std::array` to avoid heap allocation, since you know the size.
</blockquote></details>

Done.
___
*[fem/quadrature.h, line 91 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-MIuJKZ30raY_uCxJz27:-MJARP82-eLnZbxOFb49:b-896fix) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2e683c970bc11d0246a4381ccfd93593d9f7899/fem/quadrature.h#L91)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, no need to resize, you know the size at compile time.
</blockquote></details>

Done.
___
*[fem/quadrature.h, line 92 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-MIuIhiR68TT4wSLWjKD:-MJARVIG5sAIwbhVOImE:b-hu4u3u) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2e683c970bc11d0246a4381ccfd93593d9f7899/fem/quadrature.h#L92)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

it's a c++11 feature, not an Eigen feature. I believe the only requirement for them to work is that you have a ctor that takes whatever you put inside braces, but I'm a bit fuzzy on that requirement. 
</blockquote></details>

I see, thanks for the pointer!
___
*[fem/test/simplex_gaussian_quadrature_test.cc, line 14 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-MIuMYQq6990IIMYe6O6:-MJAaRbU-TfPFPdxX0fk:b6c5tvx) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2e683c970bc11d0246a4381ccfd93593d9f7899/fem/test/simplex_gaussian_quadrature_test.cc#L14)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, if everything will be public might as well use a struct.
</blockquote></details>

I was under the impression that struct is not allowed to have anything more than just data. Changed to struct.
___
*[fem/test/simplex_gaussian_quadrature_test.cc, line 93 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-MIuMloHAfscnY6EiZ80:-MJAaD4wCy9zkKnQiWBu:b8lxh2p) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2e683c970bc11d0246a4381ccfd93593d9f7899/fem/test/simplex_gaussian_quadrature_test.cc#L93)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

why in the heap? could we just have stack variables? or is there a limitation I'm missing?
</blockquote></details>

Nope, it's the force of habit. Done.
___
*[fem/test/simplex_gaussian_quadrature_test.cc, line 118 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-MIuN3qa2NZ-ztzI2ubN:-MJAeigg0t0U5vIeAiPp:b-896fix) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2e683c970bc11d0246a4381ccfd93593d9f7899/fem/test/simplex_gaussian_quadrature_test.cc#L118)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I'd place this in `LinearTestFunction2D::AnalyticalIntegralOverUnitTriangle()` or similar name. Point is, it's seem to belong there.
</blockquote></details>

Done.
___
*[fem/test/simplex_gaussian_quadrature_test.cc, line  [...]

2020-10-09 05:03 UTC, xuchenhan-tri reviewed
@amcastro-tri PTAL, thanks! 
Do you think it makes sense to start pushing this to the dev folder?

> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-:-MJAjD9P2E-grRp8A21I:brz7rxz)* status: 0 of 3 files reviewed, 10 unresolved discussions (waiting on @amcastro-tri)



<!-- Sent from Reviewable.io -->

2020-10-12 19:35 UTC, amcastro-tri requested changes
This is great. I still have questions myself whether to use dynamic vs. fixed plus/minus constexpr tricks.
I think it is a great idea to push this into dev and while at it, make someone else review it to get other eyes on it.

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-:-MJTIgp49pcQ5D4hN_RY:bf6o2fu)* status: 2 of 3 files reviewed, 6 unresolved discussions (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[fem/quadrature.h, line 12 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-MIuLGd7-x0_V17CJ0gN:-MJSuDag18eJGKm01Vp0:b94oyat) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2e683c970bc11d0246a4381ccfd93593d9f7899/fem/quadrature.h#L12)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I currently have each isoparametric element own a quadrature it uses, and each FemElement owns an isoparametric element. The cost should all be at initialization time so it's probably okay?
</blockquote></details>

I would need to see that code. But besides the cost, I find it strange the IsoparametricElement knows anything about quadratures. Why? a link to that code would help.
___
*[fem/quadrature.h, line 77 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-MIuI2rP-E0Rsmofko7a:-MJTHaQJ2TWCAIhUXUbW:b-241119) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2e683c970bc11d0246a4381ccfd93593d9f7899/fem/quadrature.h#L77)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Done.
</blockquote></details>

sorry for misleading you. I realize that in the end the parent class stores a `std::vector`, so really there is no advantage on returning an array here (I believe, double check me on that).
___
*[fem/quadrature.h, line 20 at r2](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-MJSvLNS2-4RtHgdF36i:-MJSvLNS2-4RtHgdF36j:b-iqfzjh) ([raw file](https://github.com/xuchenhan-tri/drake/blob/feadbab87583cd1e3cafc8aa79e74f7704e5d3c6/fem/quadrature.h#L20)):*
> ```objc
> 
>   template <long unsigned int NumQuads>
>   Quadrature(std::array<VectorD, NumQuads> points,
> ```

What is the advantage of a templated constructor when in the end the underlying data has dynamic size? why not make these `std::vector`? it could be a move ctor if you are worried about copies.
___
*[fem/quadrature.h, line 20 at r2](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-MJSvR-5CHFGbNOq9_T4:-MJSvR-5CHFGbNOq9_T5:b-1zzbk4) ([raw file](https://github.com/xuchenhan-tri/drake/blob/feadbab87583cd1e3cafc8aa79e74f7704e5d3c6/fem/quadrature.h#L20)):*
> ```objc
> 
>   template <long unsigned int NumQuads>
>   Quadrature(std::array<VectorD, NumQuads> points,
> ```

public or protected?
___
*[fem/quadrature.h, line 53 at r2](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-MJSvzte7JOehnwaI8PN:-MJSvzte7JOehnwaI8PO:b-ju3mc1) ([raw file](https://github.com/xuchenhan-tri/drake/blob/feadbab87583cd1e3cafc8aa79e74f7704e5d3c6/fem/quadrature.h#L53)):*
> ```objc
> The 2D unit triangle has vertices located at (0,0), (1,0) and (0,1). The 3D unit
> tetrahedron has vertices located at (0,0,0), (1,0,0), (0,1,0) and (0,0,1).
>  @tparam N order of the quadrature rule. Must be 1, 2, or 3.
> ```

nit, N -> QuadratureOrder
___
*[fem/quadrature.h, line 67 at r2](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-MJSwRXQ-SknF6X-uJwS:-MJSwRXQ-SknF6X-uJwT:bv9l58x) ([raw file](https://github.com/xuchenhan-tri/drake/blob/feadbab87583cd1e3cafc8aa79e74f7704e5d3c6/fem/quadrature.h#L67)):*
> ```objc
>       : Quadrature<T, NaturalDimension>(GetPoints(), GetWeights()) {}
> 
>   decltype(auto) GetPoints() {
> ```

This return type I believe violates the GSG, which would usually encourage being explicit about what type we return.
In this case we do know the type and we can spell it, `std::array<VectorD, num_points()>`

Also, what are we trying to acomplish here? as far as I understand, `GetPoints()` and `GetWeights()` are only used at construction. If the ctor used move semantics, then I believe you could return here a `std::vector` with no impact on performance.
Then the allocation would happen in this method, however the memory and data would get "moved" to the parent class through the move constructor. If so, then here you can safely spell out the return and avoid the difficult to parse `decltype()` at no cost.
___
*[fem/test/simplex_gaussian_quadrature_test.cc, line 14 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-MIuMYQq6990IIMYe6O6:-MJTI2UmEBi4Zss7ut5a:bozbqbl) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2e683c970bc11d0246a4381ccfd93593d9f7899/fem/test/simplex_gaussian_quadrature_test.cc#L14)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I was under the impression that struct is not allowed to have anything more than just data. Changed to struct.
</blockquote></details>

not really. I believe the distinction is a bit fuzzy though. I think the "rule" is that if you need some special semantics on a struct then just make it a class (I believe the GSG says something like "when in doubt make it a class". Usually we do tend to use structs only to pack data. Though a sugar constructor or some helper might be ok. In this case you have packed data plus two static methods, IMO struct is best. We'll see what other reviewers say.


<!-- Sent from Reviewable.io -->

2020-10-12 20:38 UTC, xuchenhan-tri reviewed
@amcastro-tri, I addressed the new comments, PTAL, thank you!
Could you provide some pointers on how to push into dev? I've never done it before.

> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-:-MJTWsu0DpqhkvBkE6qe:bwokq1p)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @amcastro-tri)

___
*[fem/quadrature.h, line 12 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-MIuLGd7-x0_V17CJ0gN:-MJTOfx06nWgfJNjm--F:b7j54gz) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2e683c970bc11d0246a4381ccfd93593d9f7899/fem/quadrature.h#L12)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I would need to see that code. But besides the cost, I find it strange the IsoparametricElement knows anything about quadratures. Why? a link to that code would help.
</blockquote></details>

I will send the code your way as soon as I finish cleaning it up.
The reasons I put quadrature inside IsoparametricElement are:
1) I realized every API for IsoparametricElement takes a quadrature as an argument and almost always the same quadrature over and over, so it's convenient to have the quadrature inside the element at construction.
2) Having the quadrature when IsoparametricElement is initialized facilitates precomputes like S(xi_q) and dSdxi(xi_q).
If cost is the concern we could have the IsoparametricElement only keep a pointer to the quadrature and have the quadrature outlive the element. I doubt the cost would be significant though.
___
*[fem/quadrature.h, line 77 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-MIuI2rP-E0Rsmofko7a:-MJTSxL5Dm9QiPhes04b:b3svj6s) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2e683c970bc11d0246a4381ccfd93593d9f7899/fem/quadrature.h#L77)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

sorry for misleading you. I realize that in the end the parent class stores a `std::vector`, so really there is no advantage on returning an array here (I believe, double check me on that).
</blockquote></details>

Agreed. Changing back to `std::vector`.
___
*[fem/quadrature.h, line 20 at r2](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-MJSvLNS2-4RtHgdF36i:-MJTRFKT2_ubaO_1LHK-:b-wcmsw3) ([raw file](https://github.com/xuchenhan-tri/drake/blob/feadbab87583cd1e3cafc8aa79e74f7704e5d3c6/fem/quadrature.h#L20)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

What is the advantage of a templated constructor when in the end the underlying data has dynamic size? why not make these `std::vector`? it could be a move ctor if you are worried about copies.
</blockquote></details>

I was blindly following your `std::array` idea without realizing eventually data needs to be stored in a `std::vector` because the Quadrature base class does not know about the number of quadrature points.

Changed to `std::vector`.
___
*[fem/quadrature.h, line 20 at r2](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-MJSvR-5CHFGbNOq9_T4:-MJTRa1L4SpWqKiR0eg8:b-a93olp) ([raw file](https://github.com/xuchenhan-tri/drake/blob/feadbab87583cd1e3cafc8aa79e74f7704e5d3c6/fem/quadrature.h#L20)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

public or protected?
</blockquote></details>

Changed to protected, thank you.
___
*[fem/quadrature.h, line 53 at r2](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-MJSvzte7JOehnwaI8PN:-MJTQ7gU3NdICS7sh5F6:b-896fix) ([raw file](https://github.com/xuchenhan-tri/drake/blob/feadbab87583cd1e3cafc8aa79e74f7704e5d3c6/fem/quadrature.h#L53)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, N -> QuadratureOrder
</blockquote></details>

Done.
___
*[fem/quadrature.h, line 67 at r2](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-MJSwRXQ-SknF6X-uJwS:-MJTSQ_G-OVPnejQlNy8:b-ihjwrc) ([raw file](https://github.com/xuchenhan-tri/drake/blob/feadbab87583cd1e3cafc8aa79e74f7704e5d3c6/fem/quadrature.h#L67)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

This return type I believe violates the GSG, which would usually encourage being explicit about what type we return.
In this case we do know the type and we can spell it, `std::array<VectorD, num_points()>`

Also, what are we trying to acomplish here? as far as I understand, `GetPoints()` and `GetWeights()` are only used at construction. If the ctor used move semantics, then I believe you could return here a `std::vector` with no impact on performance.
Then the allocation would happen in this method, however the memory and data would get "moved" to the parent class through the move constructor. If so, then here you can safely spell out the return and avoid the difficult to parse `decltype()` at no cost.



</blockquote></details>

Same as before, I was trying to shoehorn everything into `std::array` without realizing it has no advantage over `std::vector`.

The reason I used `decltype(auto)` is because I believe `std::array<VectorD, num_points()>` is not viable since `num_points()` is unknown to the base class at compile time.
___
*[fem/test/simplex_gaussian_quadrature_test.cc, line 14 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/4#-MIuMYQq6990IIMYe6O6:-MJTQi_y8zeBRjptQSza:bgs9hww) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2e683c970bc11d0246a4381ccfd93593d9f7899/fem/test/simplex_gaussian_quadrature_test.cc#L14)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

not really. I believe the distinction is a bit fuzzy though. I think the "rule" is that if you need some special semantics on a struct then just make it a class (I believe the GSG says something like "when in doubt make it a class". Usually we do tend to use structs only to pack data. Though a sugar constructor or some helper might be ok. In this case you have packed data plus two static methods, IMO struct is best. We'll see what other reviewers say.
</blockquote></details>

I see, I'll keep it a struct unless other reviewers complain.


<!-- Sent from Reviewable.io -->

2020-10-16 21:47 UTC, closed without merging