Add unit test for ContactComputationManager
xuchenhan-tri/drake pull request #8
Opened 2021-05-07 00:41 UTC by xuchenhan-tri

2021-05-07 00:46 UTC, xuchenhan-tri reviewed
@amcastro-tri  Here is the unit test for `ContactComputationManager`. I also made some changes on how the attorney works. Take a look at your leisure.

Sherm suggested that we move `DeclareCacheAndPorts()` to another abstraction since `ContactComputationManager` handles the solver not the model. I think it's a good advice if we intend to push this to Drake master.

> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/8#-:-M_3GRCn3mlAI1ypRwzh:b-5cdiud)* status: 0 of 6 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-05-07 14:55 UTC, amcastro-tri requested changes
This is great @xuchenhan-tri. I added my comments. FYI,, don't let my "naming suggestions"  be a distraction from the main comments, I am open to other options (for as long as they are not border line annoyingly long to type)

> Reviewed 3 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/8#-:-M_6IaIjCUHWdNUUsgmM:b-kbdr2x)* status: 3 of 6 files reviewed, 12 unresolved discussions (waiting on @xuchenhan-tri)

___
*[multibody/plant/contact_computation_manager_impl.h, line 22 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/8#-M_6Guis02LkiZdG8Jo1:-M_6Guis02LkiZdG8Jo2:b-mos6ni) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2ae87b339fef9d1e86c7e37578ab1e65734ca2e/multibody/plant/contact_computation_manager_impl.h#L22)):*
> ```objc
> // @tparam_default_scalar
> template <typename T>
> class ContactComputationManagerImpl : public ContactComputationManager<T> {
> ```

I placed some notes in the test. Ideally IMO we'd like managers to inherit from the ContactComputatoinManager interface. That clearly communicates the APIs we must implement and flattens the hierarchy. That is, a manager "is a" ContactComputationManager.

Now, here something interesting happens. You add this layer as a workaround to "inject more functionality". IMO that's orthogonal to being a ContactComputationManager.
For cases like this, multiple inheritance is ok.

What I propose:
1. Make this class something like `MultibodyPlantAccess {}`. No inheritance, it is not a manager. That'd allow to inject MBP into any class, not only the managers.
2. Managers now inherit from both ContactComputationManager and MultibodyPlantAccess, two orthogonal features.

Last note. `foo_header_impl.h` is a bit indicative or either a PIMPL pattern or this [old habit we had at a time in Drake](https://github.com/RobotLocomotion/drake/issues/3141). Bottom line, Impl in the name might suggest something completely different of what you want to achieve.
___
*[multibody/plant/multibody_plant_access.h, line 20 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/8#-M_6GeOuE-JtkQli5y3O:-M_6GeOv0_r8mUCtb_Yq:b-s2feco) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2ae87b339fef9d1e86c7e37578ab1e65734ca2e/multibody/plant/multibody_plant_access.h#L20)):*
> ```objc
> // MultibodyPlant's private members and/or methods to ContactComputationManager.
> template <typename T>
> class MultibodyPlantContactComputationManagerAttorney {
> ```

super long name. What about `MultibodyPlantAttorney` (even if we don't quite use the attorney pattern).
___
*[multibody/plant/multibody_plant_access.h, line 26 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/8#-M_6G7xq1Lv0hgcqJITX:-M_6G7xq1Lv0hgcqJITY:b8fc4ra) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2ae87b339fef9d1e86c7e37578ab1e65734ca2e/multibody/plant/multibody_plant_access.h#L26)):*
> ```objc
>   MultibodyPlantContactComputationManagerAttorney() = delete;
> 
>   friend class ContactComputationManagerImpl<T>;
> ```

I am not a big fan of attorneys because of this back and forth with friendship. IMO too complicated for an `internal::` use case (might be ok for some extra careful user-facing API).

Also, I can see how any other implementations in `internal::` or unit tests could benefit from having MBP access. Therefore I would not limit this to only grant access to manager, but really to anyone who needs it. Thus I'd remove the friendship here and make these methods public. No need to be extra careful in `internal::`.
___
*[multibody/plant/test/contact_computation_manager_test.cc, line 18 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/8#-M_6CCNL3f1jPl3Ys1dh:-M_6CCNL3f1jPl3Ys1di:b8qkvdb) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2ae87b339fef9d1e86c7e37578ab1e65734ca2e/multibody/plant/test/contact_computation_manager_test.cc#L18)):*
> ```cpp
> 
> namespace multibody {
> ```

nit, all this is in `internal::` so you might as well add the `internal::` scope here and avoid writing everywhere below.
___
*[multibody/plant/test/contact_computation_manager_test.cc, line 36 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/8#-M_6B4ps7opev5LsU3DA:-M_6B4pt-3EbVc7jzhEA:b-n29v2d) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2ae87b339fef9d1e86c7e37578ab1e65734ca2e/multibody/plant/test/contact_computation_manager_test.cc#L36)):*
> ```cpp
>  intialized to zeros. The discrete update event increments each entry in the
>  discrete state vector by 1. This class has a single abstract output port that
>  reports the discrete states. This class has a single cache entry that caches
> ```

nit, I imagine the cache entry is for the master version? it's not here.
___
*[multibody/plant/test/contact_computation_manager_test.cc, line 39 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/8#-M_6BD7N0ZXXGQie_CUK:-M_6BD7N0ZXXGQie_CUL:b-o6a18d) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2ae87b339fef9d1e86c7e37578ab1e65734ca2e/multibody/plant/test/contact_computation_manager_test.cc#L39)):*
> ```cpp
>  the discrete state value times 2.   */
> class DummyContactComputationManager
>     : public internal::ContactComputationManagerImpl<double> {
> ```

while the docs in this test say we inherit from ContactComputationManager (that has all the relevant docs and defines the API we care about), the subtle reality is that we actually inherit from ContactComputationManagerImpl, that only talks about MBP access.
To me those are two orthogonal axes. In particular, ContactComputationManager is an interface. In cases like this IMO it does make sense to have multiple inheritance in order to express: "DummyContactComputationManager is a ContactComputationManager and, in addition, we "inject" extra functionality to access MBP's private methods".

I'll say more in the ContactComputationManagerImpl file, but here I think it looks nicer if we write:
```
class DummyContactComputationManager
    : public internal::ContactComputationManager, internal::MultibodyPlantAccess {
}
```

where `MultibodyPlantAccess` was what came first to my mind, at least short.
___
*[multibody/plant/test/contact_computation_manager_test.cc, line 46 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/8#-M_6Cy9X8RUNyvwEwNxr:-M_6Cy9X8RUNyvwEwNxs:bvgdpa6) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2ae87b339fef9d1e86c7e37578ab1e65734ca2e/multibody/plant/test/contact_computation_manager_test.cc#L46)):*
> ```cpp
> 
>  private:
>   friend class ContactComputationManagerTest;
> ```

why the friendship? to access indexes? 
If so, just have public accessors for them, since that is actually what we have in mind for these manager classes. It'd be a nice example here.
Unless I got it wrong of course.
___
*[multibody/plant/test/contact_computation_manager_test.cc, line 50 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/8#-M_6CLQS3qg0dGLMf_sm:-M_6CLQS3qg0dGLMf_sn:beznvw7) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2ae87b339fef9d1e86c7e37578ab1e65734ca2e/multibody/plant/test/contact_computation_manager_test.cc#L50)):*
> ```cpp
>   void DeclareStateCacheAndPorts(MultibodyPlant<double>* plant) final {
>     discrete_state_index_ =
>         this->DeclareDiscreteState(VectorXd::Zero(kNumDofs));
> ```

this looks nice, like if it was an extension of MBP, I like that.
___
*[multibody/plant/test/contact_computation_manager_test.cc, line 102 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/8#-M_6CVDd2KnQLLPLMCwB:-M_6CVDd2KnQLLPLMCwC:beluucc) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2ae87b339fef9d1e86c7e37578ab1e65734ca2e/multibody/plant/test/contact_computation_manager_test.cc#L102)):*
> ```cpp
> 
>   // Sets the cache entry value to be twice the the discrete state values.
>   void CalcCacheEntry(const Context<double>& context,
> ```

nit, not used.
___
*[multibody/plant/test/contact_computation_manager_test.cc, line 154 at r1](https://reviewable.io/reviews/xuchenhan-tri/drak [...]

2021-05-07 16:14 UTC, xuchen-han reviewed
> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/8)* status: 3 of 6 files reviewed, 12 unresolved discussions (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[multibody/plant/contact_computation_manager_impl.h, line 22 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/8#-M_6Guis02LkiZdG8Jo1:-M_6WbvI4dW-52O8ZQ56:bfpi11q) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2ae87b339fef9d1e86c7e37578ab1e65734ca2e/multibody/plant/contact_computation_manager_impl.h#L22)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I placed some notes in the test. Ideally IMO we'd like managers to inherit from the ContactComputatoinManager interface. That clearly communicates the APIs we must implement and flattens the hierarchy. That is, a manager "is a" ContactComputationManager.

Now, here something interesting happens. You add this layer as a workaround to "inject more functionality". IMO that's orthogonal to being a ContactComputationManager.
For cases like this, multiple inheritance is ok.

What I propose:
1. Make this class something like `MultibodyPlantAccess {}`. No inheritance, it is not a manager. That'd allow to inject MBP into any class, not only the managers.
2. Managers now inherit from both ContactComputationManager and MultibodyPlantAccess, two orthogonal features.

Last note. `foo_header_impl.h` is a bit indicative or either a PIMPL pattern or this [old habit we had at a time in Drake](https://github.com/RobotLocomotion/drake/issues/3141). Bottom line, Impl in the name might suggest something completely different of what you want to achieve.

</blockquote></details>

Completely agree. Two orthogonal inheritance is cleaner.
___
*[multibody/plant/test/contact_computation_manager_test.cc, line 18 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/8#-M_6CCNL3f1jPl3Ys1dh:-M_6ZzHa0Bp4w3msR-sP:b-fplo6i) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2ae87b339fef9d1e86c7e37578ab1e65734ca2e/multibody/plant/test/contact_computation_manager_test.cc#L18)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, all this is in `internal::` so you might as well add the `internal::` scope here and avoid writing everywhere below.
</blockquote></details>

I think the concrete ContactComputationManager would be outside of internal? So that one can config a manager and hook it up to MbP. E.g the CompliantContactComputationManager you have in your branch.
___
*[multibody/plant/test/contact_computation_manager_test.cc, line 39 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/8#-M_6BD7N0ZXXGQie_CUK:-M_6_oxl9ppWs6M1ZKmW:b5mo91b) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2ae87b339fef9d1e86c7e37578ab1e65734ca2e/multibody/plant/test/contact_computation_manager_test.cc#L39)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

while the docs in this test say we inherit from ContactComputationManager (that has all the relevant docs and defines the API we care about), the subtle reality is that we actually inherit from ContactComputationManagerImpl, that only talks about MBP access.
To me those are two orthogonal axes. In particular, ContactComputationManager is an interface. In cases like this IMO it does make sense to have multiple inheritance in order to express: "DummyContactComputationManager is a ContactComputationManager and, in addition, we "inject" extra functionality to access MBP's private methods".

I'll say more in the ContactComputationManagerImpl file, but here I think it looks nicer if we write:
```
class DummyContactComputationManager
    : public internal::ContactComputationManager, internal::MultibodyPlantAccess {
}
```

where `MultibodyPlantAccess` was what came first to my mind, at least short.

</blockquote></details>

Great idea, thanks. One thought: the inheritance of `DummyContactComputationManager` from `internal::MultibodyPlantAccess` should be `private` instead of `public`. Otherwise those private methods in MbP are spread further instead of concentrated at a single entry point, `MultibodyPlantAccess`.


<!-- Sent from Reviewable.io -->

2021-05-07 18:58 UTC, amcastro-tri requested changes
> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/8)* status: 3 of 6 files reviewed, 12 unresolved discussions (waiting on @xuchenhan-tri)

___
*[multibody/plant/test/contact_computation_manager_test.cc, line 18 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/8#-M_6CCNL3f1jPl3Ys1dh:-M_7Aa5L3B04Da49US_x:bf4uahq) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2ae87b339fef9d1e86c7e37578ab1e65734ca2e/multibody/plant/test/contact_computation_manager_test.cc#L18)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I think the concrete ContactComputationManager would be outside of internal? So that one can config a manager and hook it up to MbP. E.g the CompliantContactComputationManager you have in your branch.
</blockquote></details>

We can still do that even if everything is in `internal::`, it just so happens we do not provide any sort of support or guarantee on API stability for anyone wanting to use this. So, if we are the only ones to use this (+maybe some expert user out there?), I'd say we keep it `internal::` so we don't have to worry about deprecations and the like.

Say I land my contact solver in Drake, in `internal::`. Once we are happy with it we can make it available through some "other" public API that enables users to select contact solvers. No need for them to play with managers directly. 

This mechanism also works in things like Anzu.
___
*[multibody/plant/test/contact_computation_manager_test.cc, line 39 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/8#-M_6BD7N0ZXXGQie_CUK:-M_7BRFN06hKNLSvGso2:b4lujl7) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2ae87b339fef9d1e86c7e37578ab1e65734ca2e/multibody/plant/test/contact_computation_manager_test.cc#L39)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Great idea, thanks. One thought: the inheritance of `DummyContactComputationManager` from `internal::MultibodyPlantAccess` should be `private` instead of `public`. Otherwise those private methods in MbP are spread further instead of concentrated at a single entry point, `MultibodyPlantAccess`.
</blockquote></details>

nice, I like that.


<!-- Sent from Reviewable.io -->

2021-05-07 20:51 UTC, xuchenhan-tri reviewed
Thanks for the feedback @amcastro-tri. I made some changes accordingly.
One additional thought on `MultibodyPlantAccess`. Please see below.

> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/8#-:-M_7_wfo2oHxi-dGMpf3:b2hr4au)* status: 3 of 6 files reviewed, 12 unresolved discussions (waiting on @amcastro-tri)

___
*[multibody/plant/multibody_plant_access.h, line 20 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/8#-M_6GeOuE-JtkQli5y3O:-M_7Xsp04FC5IjpPiw_x:bs3no0d) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2ae87b339fef9d1e86c7e37578ab1e65734ca2e/multibody/plant/multibody_plant_access.h#L20)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

super long name. What about `MultibodyPlantAttorney` (even if we don't quite use the attorney pattern).
</blockquote></details>

Changed to `MultibodyAccess`
___
*[multibody/plant/multibody_plant_access.h, line 26 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/8#-M_6G7xq1Lv0hgcqJITX:-M_7YO0H36A0ofb-xUwn:b-1jm3jl) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2ae87b339fef9d1e86c7e37578ab1e65734ca2e/multibody/plant/multibody_plant_access.h#L26)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I am not a big fan of attorneys because of this back and forth with friendship. IMO too complicated for an `internal::` use case (might be ok for some extra careful user-facing API).

Also, I can see how any other implementations in `internal::` or unit tests could benefit from having MBP access. Therefore I would not limit this to only grant access to manager, but really to anyone who needs it. Thus I'd remove the friendship here and make these methods public. No need to be extra careful in `internal::`.

</blockquote></details>

I simplified the friendship logic a little, PTAL.

I'm not too excited about the idea of a single `MultibodyPlantAccess` that exposes a bunch of private MbP methods that different components grab pieces from. It breaks encapsulation. 

E.g. as Sherm pointed out, `DeclareStateCacheAndPorts()` doesn't seem to belong to the `ContactComputationManager` abstraction. There should be something else that help injecting additional (e.g. deformable) state/port/cache etc into MbP. For the sake of this example, call it `MultibodyModelManager`. Then we could have a `MultibodyPlantContactAccess` that only exposes a set of private MbP methods related to contact that `ContactComputationManager` privately inherit from, and a separate `MultibodyPlantModelAccess` that only expose private MbP methods related to model building that `MultibodyModelManager` privately inherits from.
___
*[multibody/plant/test/contact_computation_manager_test.cc, line 18 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/8#-M_6CCNL3f1jPl3Ys1dh:-M_7XzQ-7NEmTpkugCEE:b-g1hs46) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2ae87b339fef9d1e86c7e37578ab1e65734ca2e/multibody/plant/test/contact_computation_manager_test.cc#L18)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

We can still do that even if everything is in `internal::`, it just so happens we do not provide any sort of support or guarantee on API stability for anyone wanting to use this. So, if we are the only ones to use this (+maybe some expert user out there?), I'd say we keep it `internal::` so we don't have to worry about deprecations and the like.

Say I land my contact solver in Drake, in `internal::`. Once we are happy with it we can make it available through some "other" public API that enables users to select contact solvers. No need for them to play with managers directly. 

This mechanism also works in things like Anzu.
</blockquote></details>

Makes sense, done.
___
*[multibody/plant/test/contact_computation_manager_test.cc, line 36 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/8#-M_6B4ps7opev5LsU3DA:-M_7Y4g6AyrFmurK9CUh:bai136l) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2ae87b339fef9d1e86c7e37578ab1e65734ca2e/multibody/plant/test/contact_computation_manager_test.cc#L36)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, I imagine the cache entry is for the master version? it's not here.
</blockquote></details>

Removed this line.
___
*[multibody/plant/test/contact_computation_manager_test.cc, line 39 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/8#-M_6BD7N0ZXXGQie_CUK:-M_7Y87Y0iY8vVGVuL1_:b-896fix) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2ae87b339fef9d1e86c7e37578ab1e65734ca2e/multibody/plant/test/contact_computation_manager_test.cc#L39)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nice, I like that.
</blockquote></details>

Done.
___
*[multibody/plant/test/contact_computation_manager_test.cc, line 46 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/8#-M_6Cy9X8RUNyvwEwNxr:-M_79z7bA0U-YhO4ntGC:b-896fix) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2ae87b339fef9d1e86c7e37578ab1e65734ca2e/multibody/plant/test/contact_computation_manager_test.cc#L46)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

why the friendship? to access indexes? 
If so, just have public accessors for them, since that is actually what we have in mind for these manager classes. It'd be a nice example here.
Unless I got it wrong of course.
</blockquote></details>

Done.
___
*[multibody/plant/test/contact_computation_manager_test.cc, line 50 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/8#-M_6CLQS3qg0dGLMf_sm:-M_7Y9Nd0YGnsMVoGBgH:b-896fix) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2ae87b339fef9d1e86c7e37578ab1e65734ca2e/multibody/plant/test/contact_computation_manager_test.cc#L50)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

this looks nice, like if it was an extension of MBP, I like that.
</blockquote></details>

Done.
___
*[multibody/plant/test/contact_computation_manager_test.cc, line 102 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/8#-M_6CVDd2KnQLLPLMCwB:-M_7YA4SAjVeyqED7l6U:bss4a2b) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2ae87b339fef9d1e86c7e37578ab1e65734ca2e/multibody/plant/test/contact_computation_manager_test.cc#L102)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, not used.
</blockquote></details>

Removed.
___
*[multibody/plant/test/contact_computation_manager_test.cc, line 154 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/8#-M_6DKlH6faHJ5ycI-b0:-M_75yxP8dtP4SQQPW_B:b-75vk8z) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2ae87b339fef9d1e86c7e37578ab1e65734ca2e/multibody/plant/test/contact_computation_manager_test.cc#L154)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, I believe the bracket can be omitted when the result is an Eigen type. That is, Eigen vectors are the default.
</blockquote></details>

I get an error when the bracket is removed. Looks like the default is BasicVector not Eigen vector?
___
*[multibody/plant/test/contact_computation_manager_test.cc, line 162 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/8#-M_6DYGy9RdM0F9qbWxm:-M_7Xn8-At1rfhY1NioT:b-896fix) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2ae87b339fef9d1e86c7e37578ab1e65734ca2e/multibody/plant/test/contact_computation_manager_test.cc#L162)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

what we really want here is to make sure that MBP was wired correctly. This is more like testing the unit test.
Maybe you could set up a single step simulation and check like this:
If CalcContactResults was called. Maybe have a mutable flag (initial [...]

2021-05-10 13:51 UTC, amcastro-tri requested changes
I don't think I understood your point on the MultibodyModelManager stuff @xuchenhan-tri.
IMO this PR, as is, is great and solves the problems we do have today.

> Reviewed 1 of 6 files at r1, 4 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/8#-:-M_LXpn29MCs3XRxWd0k:b-lf5c6o)* status: 5 of 6 files reviewed, 5 unresolved discussions (waiting on @xuchenhan-tri)

___
*[multibody/plant/multibody_plant_access.h, line 26 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/8#-M_6G7xq1Lv0hgcqJITX:-M_LVhbcC-g7B3PD_wEU:b-7j9huq) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2ae87b339fef9d1e86c7e37578ab1e65734ca2e/multibody/plant/multibody_plant_access.h#L26)):*
> It breaks encapsulation.

fair, we can remove the additional friendship when/if we need it.

> DeclareStateCacheAndPorts() doesn't seem to belong to the ContactComputationManager abstraction.

I don't see why not?

> For the sake of this example, call it MultibodyModelManager. Then we could have a MultibodyPlantContactAccess that ....

Maybe?.... but what problem are you trying to solve?
I thought the problem we were trying to solve was: "lets come up with a clean solution that gives us 100% freedom to completely revamp the contact algorithms, including adding softsim two-way coupling". What you have in this PR is great. I don't see the MultibodyModelManager anywhere so really I don't understand how an extra level of indirection would help us here.
What you are describing seems like a more general solution for when, we actually have a use case? and here I should use plural, "use cases?". Otherwise a super elegant (?) solution for a single use case probably is too much work before we even know if we need it?
All this will live in internal, most likely forever. My vote is to keep things simple. You could also add a TODO for splitting this class into two or more.
___
*[multibody/plant/test/contact_computation_manager_test.cc, line 154 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/8#-M_6DKlH6faHJ5ycI-b0:-M_LUhZp3QZYIANfJV8F:b-eae75j) ([raw file](https://github.com/xuchenhan-tri/drake/blob/c2ae87b339fef9d1e86c7e37578ab1e65734ca2e/multibody/plant/test/contact_computation_manager_test.cc#L154)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I get an error when the bracket is removed. Looks like the default is BasicVector not Eigen vector?
</blockquote></details>

ah, it's abstract valued, that's why. See above for creating vector valued ports. Then it should work (that'd return a VectorBlock)
___
*[multibody/plant/test/contact_computation_manager_test.cc, line 63 at r2](https://reviewable.io/reviews/xuchenhan-tri/drake/8#-M_LTAWLC77zo7a03Xps:-M_LTAWLC77zo7a03Xpt:b4k3r2t) ([raw file](https://github.com/xuchenhan-tri/drake/blob/db96e5f25c14cf387c315599999374b68fe43178/multibody/plant/test/contact_computation_manager_test.cc#L63)):*
> ```cpp
>         this->DeclareDiscreteState(VectorXd::Zero(kNumDofs));
>     output_port_index_ =
>         this->DeclareAbstractOutputPort(
> ```

there is nice sugar for vector valued ports, like this:
```
DeclareVectorOutputPort(
  "dummy_output_port", 
  BasicVector<T>(kNumDofs),
  [this](const Context&, BasicVector<T>* output) {
    output->SetFromVector(context.get_discrete_state(discrete_state_index_).get_value());
  },
  {systems::System<double>::xd_ticket()})
```
___
*[multibody/plant/test/contact_computation_manager_test.cc, line 76 at r2](https://reviewable.io/reviews/xuchenhan-tri/drake/8#-M_LRI_IDaXzrwwbm7mp:-M_LRI_IDaXzrwwbm7mq:b-cpjdm7) ([raw file](https://github.com/xuchenhan-tri/drake/blob/db96e5f25c14cf387c315599999374b68fe43178/multibody/plant/test/contact_computation_manager_test.cc#L76)):*
> ```cpp
>                 // TODO(xuchenhan_tri): It may be worthwhile to expose the
>                 // discrete_state_ticket() method from MbP so that more
>                 // fine-grained ticket can be created.
> ```

nit, you can do it now with your `MultibodyPlantAccess`, it'd serve as a great proof of concept (and you'll get rid of a TODO :-) )
___
*[multibody/plant/test/contact_computation_manager_test.cc, line 119 at r2](https://reviewable.io/reviews/xuchenhan-tri/drake/8#-M_LRdNM5OX1a4tkPShJ:-M_LRdNM5OX1a4tkPShK:b-rii9j0) ([raw file](https://github.com/xuchenhan-tri/drake/blob/db96e5f25c14cf387c315599999374b68fe43178/multibody/plant/test/contact_computation_manager_test.cc#L119)):*
> ```cpp
>  protected:
>   void SetUp() override {
>     plant_.AddRigidBody("rigid body", SpatialInertia<double>());
> ```

oh nice!, you added MBP dofs as well, I like that, more comprehensive. 


<!-- Sent from Reviewable.io -->

2021-05-21 02:58 UTC, xuchenhan-tri commented
Closing this PR as the PR to Drake master is starting to converge.

2021-05-21 02:58 UTC, closed without merging